### ISSUE TITLE
tail with multiline bigger/longer than certain size/length gets skipped when used with forward and splunk

### ISSUE THREAD

**Issue by kiich** [fluent/fluent-bit#1219]
## Bug Report

**Describe the bug**
This is related to https://github.com/fluent/fluent-bit/issues/1214 and I have been able to reproduce this at will.

Using fluent-bit 1.0.4 in Kubernetes with a rather complicated set up of Pod + fluent-bit sidecar which sends to another fluent-bit running on all nodes that is running forward input which then outputs to Splunk server.

The whole set up works rather nicely except i've noticed that when the pod's log has a multiline line that consists of more than certain lines/size (not sure which), this line does not show up in my splunk. If i reduce the size/number of this multiline to a certain length/size, it starts appearing.

Regex in Rubular works so pretty confident the regex is fine.

**To Reproduce**
- Example log message if applicable:
```
"message"=>"c.h.cds.generic.client.util.YamlUtil - Error reading config resource harp-staging.yml. Returning empty configuration
[exceptionClass=com.xxx.cds.generic.client.util.ResourceUtil, exceptionMethod=inputStreamOf, exceptionID=e2ae699d, ]
com.xxx.cds.generic.client.exception.ConfigResourceNotFoundException: java.lang.IllegalArgumentException: resource harp-staging.yml not found.
	at com.xxx.cds.generic.client.util.ResourceUtil.inputStreamOf(ResourceUtil.java:19)
	at com.xxx.cds.generic.client.util.YamlUtil.toMap(YamlUtil.java:31)
	at com.xxx.cds.generic.client.core.ConfigFileUtil.getEnvConfigIfPresent(ConfigFileUtil.java:34)
	at com.xxx.cds.generic.client.core.ClientBuilder.readConfig(ClientBuilder.java:90)
	at com.xxx.cds.generic.client.core.ClientBuilder.build(ClientBuilder.java:79)
	at com.xxx.harp.client.HarpClientsConfiguration.asyncDataServicesClient(HarpClientsConfiguration.java:61)
	at com.xxx.harp.client.HarpClientsConfiguration$$EnhancerBySpringCGLIB$$7d122503.CGLIB$asyncDataServicesClient$0(<generated>)
	at com.xxx.harp.client.HarpClientsConfiguration$$EnhancerBySpringCGLIB$$7d122503$$FastClassBySpringCGLIB$$fef175a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
	at com.xxx.harp.client.HarpClientsConfiguration$$EnhancerBySpringCGLIB$$7d122503.asyncDataServicesClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123)"}, "index"=>"xxx_com"
```

This seems to work fine when I run fluentbit as container locally and using stdout, the output seems to capture all so I am wondering if it is my setup and its config that is causing this.

I have been tweaking the values below for `INPUT` for the tail as well as forward but it seems to not make difference for my setup:
```
        Multiline         On
        Multiline_Flush   5
        Parser_Firstline  common_log
        DB                /var/log/flb-commonlog.db
        Buffer_Chunk_Size 1MB # this i have increased to as much as 50MB as test
        Buffer_Max_Size   10MB # this i have increased to as much as 50MB as test
        Mem_Buf_Limit     10MB  # this i have increased to as much as 50MB as test
        Skip_Long_Lines   On
        Refresh_Interval  10
```

**Expected behavior**
All multiline lines appear in splunk

**Additional context**
If i truncate the multiline to say 50 lines, it appears in splunk with in_tail debug showing me:
```
[2019/03/22 01:44:48] [debug] [in_tail] file=/logs/50.log read=6006 lines=50
```
If it's say 100 lines, it does NOT appear in splunk but the in_tail debug on sidecar shows me:
```
[2019/03/22 01:46:10] [debug] [in_tail] file=/logs/100.log read=12223 lines=100
```

So from the point of `in_tail` it seems everything is fine?
I have played around with `Skip_Long_Lines` as well but after reading up on it, it seems that does not apply to multilines?

I don't have the debug of the forwarder because it is way too much debug and tricky to diagnose but can supply this also if you can tell me what to look for.

**Comment by kiich** [comment]
I forgot to add my regex for the parser
```
regex: ^\s*(?<time>\d+(?:-\d+){2}T\d+(?::\d+){2}\.\d+\+\d{4})\s*(?<level>\S+)\s+\[(build=)?(?<build>\S*)\]\s+\[(session_id=|sessionId=)?(?<session_id>[\w\.-]*)\]\s+\[(request_id=|requestId=)?(?<request_id>[\w\.-]*)\]\s+\[(application_id=|applicationId=)?(?<application_id>[\w\.-]*)\]\s+\[(?<thread_id>\S*)\]\s*(?<message>[\s\S]*?)(?=\g<time>|\Z)
```

is what I'm using - i did consider if its to do with the multiline regex thats causing something weird but i could not get any other regex to work with `Multiline` set to `On`
