### ISSUE TITLE
Scheduler: improve retries handling

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#127]
On a high load test, if many retries are issued, the Scheduler creates a timer file descriptor for each one, but easily these retries could not be scheduled at some point if we run out of file descriptors.

```
[2016/11/02 10:41:03] [  Error] timerfd: Too many open files, errno=24 at /home/edsiper/coding/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:175
```

Possible workarounds:

1. Let the user increase their file descriptor limits. 
2. Do not use a file descriptor for each retry, instead lookup a list of retries every second using just one timer.

The approach 1 will let the user same the issue before take some action, note that using timerfd() is good as we just get notifications upon a timeout, we don't query a list.

Approach 2 add some overhead as we need to iterate a list every second.

This needs more thinking...

**Comment by edsiper** [comment]
Current behavior is: if a 'retry' cannot be scheduled, the Task is dropped if no one else is using it.

**Comment by nokute78** [comment]
> Current behavior is: if a 'retry' cannot be scheduled, the Task is dropped if no one else is using it.

In my environment(`ulimit -n` returns 1024), segfault happened.
I can't reveal root cause yet.

## How to reproduce

I tested this command in offline environment and waited minutes to run out of file descriptor.
(multiple out_forwards and long retry_limits.)

`bin/fluent-bit -i cpu -t foo -o forward -m foo -p retry_limit=20  -o forward -m foo -p retry_limit=20 -o forward -m foo -p retry_limit=20 -o forward -m foo -p retry_limit=20`

## Tail of console  log

```
[2016/11/29 22:10:59] [error] [out_forward] no upstream connections available
[2016/11/29 22:10:59] [  Error] timerfd: Too many open files, errno=24 at /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:175
[2016/11/29 22:10:59] [ warn] [sched] retry for task 250 could not be scheduled
socket: Too many open files
[2016/11/29 22:11:00] [error] [io] could not create socket
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
[2016/11/29 22:11:00] [error] [io] TCP connection failed: 127.0.0.1:24224
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
[2016/11/29 22:11:00] [error] [io] TCP connection failed: 127.0.0.1:24224
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
[2016/11/29 22:11:00] [error] [io] TCP connection failed: 127.0.0.1:24224
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
[2016/11/29 22:11:00] [error] [io] TCP connection failed: 127.0.0.1:24224
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
[2016/11/29 22:11:00] [error] [io] TCP connection failed: 127.0.0.1:24224
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
[2016/11/29 22:11:00] [error] [io] TCP connection failed: 127.0.0.1:24224
[2016/11/29 22:11:00] [error] [out_forward] no upstream connections available
socket: Too many open files

Program received signal SIGSEGV, Segmentation fault.
0x000000000041d878 in flb_engine_dispatch_retry ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x000000000041d878 in flb_engine_dispatch_retry ()
#1  0x000000000041f8a3 in flb_sched_event_handler ()
#2  0x000000000041d337 in flb_engine_start ()
#3  0x0000000000415d94 in main ()
(gdb)  
```

**Comment by edsiper** [comment]
## troubleshooting

```
==15215== Warning: invalid file descriptor 27 in syscall open()
==15215== Warning: invalid file descriptor 27 in syscall timerfd_create()
==15215== Invalid write of size 1
==15215==    at 0x4C3403D: __GI_mempcpy (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15215==    by 0x581E2A5: __xpg_strerror_r (xpg-strerror.c:49)
==15215==    by 0x2787E7: mk_utils_libc_error (mk_utils.h:76)
==15215==    by 0x278B68: _mk_event_timeout_create (mk_event_epoll.c:175)
==15215==    by 0x278F69: mk_event_timeout_create (mk_event.c:126)
==15215==    by 0x13408D: flb_sched_request_create (flb_scheduler.c:132)
==15215==    by 0x1306E4: flb_engine_manager (flb_engine.c:216)
==15215==    by 0x130EA4: flb_engine_handle_event (flb_engine.c:290)
==15215==    by 0x130EA4: flb_engine_start (flb_engine.c:454)
==15215==    by 0x1280CA: main (fluent-bit.c:507)
==15215==  Address 0x5b76a42 is 18 bytes inside a block of size 104 free'd
==15215==    at 0x4C2DD6B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15215==    by 0x12F22F: flb_free (flb_mem.h:88)
==15215==    by 0x1306AB: flb_thread_destroy (flb_thread_libco.h:84)
==15215==    by 0x1306AB: flb_output_thread_destroy_id (flb_output.h:214)
==15215==    by 0x1306AB: flb_engine_manager (flb_engine.c:213)
==15215==    by 0x130EA4: flb_engine_handle_event (flb_engine.c:290)
==15215==    by 0x130EA4: flb_engine_start (flb_engine.c:454)
==15215==    by 0x1280CA: main (fluent-bit.c:507)
==15215==  Block was alloc'd at
==15215==    at 0x4C2CB3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15215==    by 0x13117F: flb_malloc (flb_mem.h:54)
==15215==    by 0x1314C3: flb_thread_new (flb_thread_libco.h:115)
==15215==    by 0x131C95: flb_output_thread (flb_output.h:363)
==15215==    by 0x131C95: tasks_start (flb_engine_dispatch.c:92)
==15215==    by 0x1321FB: flb_engine_dispatch (flb_engine_dispatch.c:178)
==15215==    by 0x12F915: flb_engine_flush (flb_engine.c:83)
==15215==    by 0x130E6D: flb_engine_handle_event (flb_engine.c:267)
==15215==    by 0x130E6D: flb_engine_start (flb_engine.c:454)
==15215==    by 0x1280CA: main (fluent-bit.c:507)
```

**Comment by edsiper** [comment]
@nokute78 

the latest fixes in master should address the issue, after the changes I cannot longer reproduce the problem.

Note: keeping this ticket open until the new strategy for schedule retries is implemented.

**Comment by nokute78** [comment]
@edsiper Great! 
I tested 13e1300e3cd9af0427cea75c7c2f0864bb5bce6c.
I also couldn't reproduce the issue. Thanks!

**Comment by edsiper** [comment]
Through commit f7c95089580eb5d30111fdc3976b83a37b9da3bd, now the scheduler only use file descriptors for retries that will be scheduled within the next 10 seconds, otherwise it use a different mechanism with a queue and a checker. 

This patch decrease the number of file descriptors required on critical environments where the data cannot be flushed and is required to retry.

e.g: 20 records flushed every second in an infinite retry (because of output backend is down) before the patch might use ~38 file descriptors, with this patch it get's down to 19.
