### ISSUE TITLE
Monkey metrics enpoint freezes entire fluent-bit

### ISSUE THREAD

**Issue by kabakaev** [fluent/fluent-bit#1310]
## Bug Report

FLB freezes under high load if the monitoring service is enabled with
```
    [SERVICE]
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
```

Disabling `HTTP_Server` also fixes the freeze.

See GDB output below.

**To Reproduce**

I've hit this freeze while reproducing the in_systemd race condition over reading a rotated journal file, as given in #1285.

Namely, under high load FLB was working fine probably until Prometheus came to scrape metrics. Then, FLB is trying to write to a pipe (file descriptor 57) and never finishes:
```bash
# strace -p 7 -f
[pid     7] write(57, "\203\245input\203\251systemd.0\202\247records\316\0\v\37\271"...
```

The call never get back from writing to that pipe.

It may be an issue of writing to FIFO, which is not being read any longer, or some network issue. The runtime environment in this case is docker-v18.06.1-ce under kubernetes-v1.13. Hence it's a lot of "magic" behind all system calls in comparison to directly running FLB in the host linux namespaces.

We don't see such issue under low or moderate flow of logs, even on thousands of [patched FLB-v1.0.5](https://github.com/c445/fluent-bit/tree/fix-for-743-and-904) instances with enabled metrics endpoint.

Both the current master branch and the very same production docker container referenced above are freezing under high load too.

**Additional context**
```bash
# root@fluent-bit-mmh6v:/# gdb
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) attach 7
Attaching to process 7
[New LWP 9]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: the debug information found in "/usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1" does not match "/usr/lib/x86_64-linux-gnu/liblz4.so.1" (CRC mismatch).

warning: the debug information found in "/lib/x86_64-linux-gnu/libpcre.so.3.13.3" does not match "/lib/x86_64-linux-gnu/libpcre.so.3" (CRC mismatch).

0x00007f7fb27a31cd in write () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) i thr
  Id   Target Id         Frame
* 1    Thread 0x7f7fb2b38cc0 (LWP 7) "fluent-bit" 0x00007f7fb27a31cd in write () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0x7f7faf5ff700 (LWP 9) "fluent-bit" 0x00007f7fb10b2303 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
(gdb) thr 1
[Switching to thread 1 (Thread 0x7f7fb2b38cc0 (LWP 7))]
#0  0x00007f7fb27a31cd in write () at ../sysdeps/unix/syscall-template.S:84
84	in ../sysdeps/unix/syscall-template.S
(gdb) bt full
#0  0x00007f7fb27a31cd in write () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x0000563a7f339755 in msg_write (fd=57, buf=0x7f7f7eb55000, count=499) at /tmp/src/lib/monkey/mk_server/mk_fifo.c:247
        bytes = 8
        total = 0
#2  0x0000563a7f339892 in mk_fifo_send (ctx=0x7f7fafa92a60, id=0, data=0x7f7f7eb55000, size=499)
    at /tmp/src/lib/monkey/mk_server/mk_fifo.c:303
        ret = 8
        head = 0x7f7f7bc0b0e8
        msg = {length = 499, flags = 0, queue_id = 0, data = 0x7ffda9336e3c "\b"}
        q = 0x7f7fafa3b038
        fw = 0x7f7f7bc0b080
#3  0x0000563a7f338ea0 in mk_mq_send (ctx=0x7f7fafa1e930, qid=0, data=0x7f7f7eb55000, size=499)
    at /tmp/src/lib/monkey/mk_server/mk_lib.c:720
No locals.
#4  0x0000563a7f04a425 in flb_hs_push_metrics (hs=0x7f7fafa23d10, data=0x7f7f7eb55000, size=499) at /tmp/src/src/http_server/flb_hs.c:42
No locals.
#5  0x0000563a7f0414d1 in collect_metrics (me=0x7f7fafa34100) at /tmp/src/src/flb_metrics_exporter.c:171
        keys = 3
        ctx = 0x7f7fafa18180
        mp_sbuf = {size = 499, data = 0x7f7f7eb55000 "\203\245input\203\251systemd.0\202\247records\316", alloc = 8192}
        mp_pck = {data = 0x7ffda9336ef0, callback = 0x563a7f040d8e <msgpack_sbuffer_write>}
#6  0x0000563a7f041605 in flb_me_fd_event (fd=48, me=0x7f7fafa34100) at /tmp/src/src/flb_metrics_exporter.c:220
No locals.
#7  0x0000563a7f03106a in flb_engine_handle_event (config=0x7f7fafa18180, mask=1, fd=48) at /tmp/src/src/flb_engine.c:269
        ret = -1
#8  flb_engine_start (config=0x7f7fafa18180) at /tmp/src/src/flb_engine.c:487
        __i = 1
        __ctx = 0x7f7fafa213b0
        ret = 0
        tmp = "24.0K\000\000\000\220\036\242\257\177\177\000"
        t_flush = {tm = {tv_sec = 1, tv_nsec = 0}}
        event = 0x7f7fafa34110
---Type <return> to continue, or q <return> to quit---
        evl = 0x7f7fafa1e138
#9  0x0000563a7efa8639 in main (argc=4, argv=0x7ffda9337118) at /tmp/src/src/fluent-bit.c:862
        opt = -1
        ret = 0
        last_plugin = -1
        cfg_file = 0x7f7fafa2b000 "_SYSTEMD_UNIT=docker.serviceonf"
        in = 0x0
        out = 0x0
        filter = 0x0
        long_opts = {{name = 0x563a7f353154 "storage_path", has_arg = 1, flag = 0x0, val = 98}, {name = 0x563a7f353161 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x563a7f353168 "daemon", has_arg = 0, flag = 0x0, val = 100}, {name = 0x563a7f35316f "flush", has_arg = 1,
            flag = 0x0, val = 102}, {name = 0x563a7f353175 "http", has_arg = 0, flag = 0x0, val = 72}, {name = 0x563a7f35317a "log_file", has_arg = 1, flag = 0x0, val = 108}, {name = 0x563a7f353183 "port", has_arg = 1, flag = 0x0, val = 80}, {name = 0x563a7f353188 "input",
            has_arg = 1, flag = 0x0, val = 105}, {name = 0x563a7f35305d "match", has_arg = 1, flag = 0x0, val = 109}, {name = 0x563a7f35318e "output", has_arg = 1, flag = 0x0, val = 111}, {name = 0x563a7f353195 "filter", has_arg = 1, flag = 0x0, val = 70}, {
            name = 0x563a7f35319c "parser", has_arg = 1, flag = 0x0, val = 82}, {name = 0x563a7f3531a3 "prop", has_arg = 1, flag = 0x0, val = 112}, {name = 0x563a7f3531a8 "plugin", has_arg = 1, flag = 0x0, val = 101}, {name = 0x563a7f353063 "tag", has_arg = 1, flag = 0x0,
            val = 116}, {name = 0x563a7f3531af "sp-task", has_arg = 1, flag = 0x0, val = 84}, {name = 0x563a7f3531b7 "version", has_arg = 0, flag = 0x0, val = 86}, {name = 0x563a7f3531bf "verbose", has_arg = 0, flag = 0x0, val = 118}, {name = 0x563a7f3531c7 "quiet", has_arg = 0,
            flag = 0x0, val = 113}, {name = 0x563a7f3531cd "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x563a7f3531d2 "coro_stack_size", has_arg = 1, flag = 0x0, val = 115}, {name = 0x563a7f3531e2 "sosreport", has_arg = 0, flag = 0x0, val = 83}, {
            name = 0x563a7f3531ec "http_server", has_arg = 0, flag = 0x0, val = 72}, {name = 0x563a7f3531f8 "http_listen", has_arg = 1, flag = 0x0, val = 76}, {name = 0x563a7f353204 "http_port", has_arg = 1, flag = 0x0, val = 80}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
(gdb)
```

**Comment by kabakaev** [comment]
Not reproducible on recent release.
