### ISSUE TITLE
Segfault at flb_input_chunk_destroy as failure of flb_input_chunk_get_tag() is not handled

### ISSUE THREAD

**Issue by manojna10** [fluent/fluent-bit#2875]
## Bug Report

if flb_input_chunk_get_tag() returns -1, its not handled in flb_input_chunk_destroy() resulting in SIGSEGV as shown below

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 29373]
0x00007f0c4dd5a1f5 in XXH3_hashLong_64b_default.constprop.9 () from /lib/libfluent-bit.so
(gdb) bt
#0  0x00007f0c4dd5a1f5 in XXH3_hashLong_64b_default.constprop.9 () at /lib/libfluent-bit.so
#1  0x00007f0c4dd08529 in flb_hash_del_ptr () at /lib/libfluent-bit.so
#2  0x00007f0c4dd0f9bc in flb_input_chunk_destroy () at /lib/libfluent-bit.so
#3  0x00007f0c4dd1d08c in flb_task_destroy () at /lib/libfluent-bit.so
#4  0x00007f0c4dd0fcee in flb_input_chunk_find_space_new_data () at /lib/libfluent-bit.so
#5  0x00007f0c4dd0fdc4 in flb_input_chunk_place_new_chunk () at /lib/libfluent-bit.so
#6  0x00007f0c4dd1047f in flb_input_chunk_append_raw () at /lib/libfluent-bit.so
#7  0x00007f0c4dd7ccf0 in in_lib_collect () at /lib/libfluent-bit.so
#8  0x00007f0c4dd0ef35 in flb_input_collector_fd () at /lib/libfluent-bit.so
#9  0x00007f0c4dd1b104 in flb_engine_start () at /lib/libfluent-bit.so
#10 0x00007f0c4dd061d1 in flb_lib_worker () at /lib/libfluent-bit.so
#11 0x00007f0c5779bea5 in start_thread () at /lib64/libpthread.so.0
#12 0x00007f0c4d9c98dd in clone () at /lib64/libc.so.6
(gdb)
**To Reproduce**
- Steps to reproduce the problem:
The server is down, so the logs are being stored in disk, after it reaches storage.total_limit_size, when its destroying old chunks, it seg faulting. 

I
**Expected behavior**
should not crash

**Your Environment**

* Version used: Repository at commit: https://github.com/fluent/fluent-bit/tree/4138b63901868dd5525ef0094dbc366488c92ae4
* Running as a library in centos 7
* 1 input plugin(lib), 1 output plugin(syslog)
* storage.type filesystem
* mem_buf_limit 50M
* storage.total_limit_size 50M
* Flush 1

**Comment by manojna10** [comment]
Root cause for Issue 1: when we schedule a retry if the chunk is up and if wr are over out configured memory limit, we put the chunks down which calls munmap which sets the chunks data size to 0. When we loop through all the chunks to find some space when disk limit is reached, these down chunks were considered as 0 bytes and removed as well. 
With my limited knowledge of the code I commented out the code that sets the data size to 0 and it seems to work fine for the first issue.

**Comment by edsiper** [comment]
cc: @JeffLuoo

**Comment by JeffLuoo** [comment]
@edsiper I will take a look into it.

**Comment by JeffLuoo** [comment]
@manojna10 
Hi I tried running the program with the following configuration but could not reproduce the error
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug
    storage.path               /var/log/fluent-bit-buffers/
    storage.sync               full
    storage.checksum           off
    storage.backlog.mem_limit  10M

[INPUT]
    Name cpu
    Tag  my_cpu

[OUTPUT]
    Name http
    Match *
    Host 0.0.0.0
    Port 80
    retry_limit  false
    storage.total_limit_size 5000
```

And the log 
```
[2020/12/20 20:42:20] [error] [src/flb_http_client.c:1133 errno=32] Broken pipe
[2020/12/20 20:42:20] [error] [output:http:http.0] could not flush records to 0.0.0.0:80 (http_do=-1)
[2020/12/20 20:42:20] [debug] [retry] new retry created for task_id=5 attempts=1
[2020/12/20 20:42:20] [ warn] [engine] failed to flush chunk '7789-1608496939.665535834.flb', retry in 7 seconds: task_id=5, input=cpu.0 > output=http.0
[2020/12/20 20:42:20] [debug] [input chunk] chunk 7789-1608496940.715545851.flb required 575 bytes and 400 bytes left in plugin http.0
[2020/12/20 20:42:20] [debug] [input chunk] remove route of chunk 7789-1608496932.315588725.flb with size 575 bytes to output plugin http.0 to place the incoming data with size 575 bytes
[2020/12/20 20:42:20] [debug] [task] drop task_id 6 with no active route from input plugin cpu.0
[2020/12/20 20:42:20] [debug] [task] destroy task=0x7fa8e8015dc0 (task_id=6)
[2020/12/20 20:42:20] [debug] [retry] task retry=0x7fa8e8014800, invalidated from the scheduler
[2020/12/20 20:42:20] [debug] [input chunk] update plugin http.0 fs_chunk_size by 575 bytes, the current fs_chunk_size is 4600 bytes
[2020/12/20 20:42:21] [debug] [task] created task=0x7fa8e8015800 id=6 OK
[2020/12/20 20:42:21] [debug] [http_client] not using http_proxy for header
[2020/12/20 20:42:21] [debug] [http_client] header=POST / HTTP/1.1
Host: 0.0.0.0:80
Content-Length: 575
Content-Type: application/msgpack
User-Agent: Fluent-Bit


[2020/12/20 20:42:21] [error] [src/flb_http_client.c:1133 errno=32] Broken pipe
[2020/12/20 20:42:21] [error] [output:http:http.0] could not flush records to 0.0.0.0:80 (http_do=-1)
[2020/12/20 20:42:21] [debug] [retry] new retry created for task_id=6 attempts=1
[2020/12/20 20:42:21] [ warn] [engine] failed to flush chunk '7789-1608496940.715545851.flb', retry in 9 seconds: task_id=6, input=cpu.0 > output=http.0
[2020/12/20 20:42:21] [debug] [input chunk] chunk 7789-1608496941.765552580.flb required 575 bytes and 400 bytes left in plugin http.0
[2020/12/20 20:42:21] [debug] [input chunk] remove route of chunk 7789-1608496933.365627725.flb with size 575 bytes to output plugin http.0 to place the incoming data with size 575 bytes
[2020/12/20 20:42:21] [debug] [task] drop task_id 7 with no active route from input plugin cpu.0
[2020/12/20 20:42:21] [debug] [task] destroy task=0x7fa8e8014d20 (task_id=7)
[2020/12/20 20:42:21] [debug] [retry] task retry=0x7fa8e8013fd0, invalidated from the scheduler
[2020/12/20 20:42:21] [debug] [input chunk] update plugin http.0 fs_chunk_size by 575 bytes, the current fs_chunk_size is 4600 bytes
[2020/12/20 20:42:22] [debug] [task] created task=0x7fa8e8014d20 id=7 OK
[2020/12/20 20:42:22] [debug] [http_client] not using http_proxy for header
[2020/12/20 20:42:22] [debug] [http_client] header=POST / HTTP/1.1
Host: 0.0.0.0:80
Content-Length: 575
Content-Type: application/msgpack
User-Agent: Fluent-Bit
```

Could you please share me a configuration file that I can use to reproduce the issue?

**Comment by manojna10** [comment]
Hi @JeffLuoo let me try reproducing it again and get back. thank you.

**Comment by JeffLuoo** [comment]
@manojna10 Thank you!

**Comment by manojna10** [comment]
@JeffLuoo I am unable to reproduce this issue. Closing this for now. Will reopen when I face the issue again. Thanks for looking into it.
