### ISSUE TITLE
[1.7 dev] crash on multi workers when remote server drops active connections

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#2926]
[GIT Master only]

When a remote endpoint abruptly close the connections, when using multiworkers mode the following crash happens:

```
[2021/01/08 23:55:24] [engine] caught signal (SIGSEGV)
#0  0x565181f1b0ae      in  __mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:87
#1  0x565181f1b0e5      in  mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:93
#2  0x565181f1bbef      in  destroy_conn() at src/flb_upstream.c:256
#3  0x565181f1c5ea      in  flb_upstream_conn_release() at src/flb_upstream.c:551
#4  0x565181facbb5      in  cb_splunk_flush() at plugins/out_splunk/splunk.c:225
#5  0x565181f08ae6      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:460
#6  0x565182217a46      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#7  0xffffffffffffffff  in  ???() at ???:0
```

Inspecting the core file with gdb:

```
#4  0x00005622357a30ae in __mk_list_del (prev=0x0, next=0x0) at /home/edsiper/fluent-bit/lib/monkey/include/monkey/mk_core/mk_list.h:87
#5  0x00005622357a30e6 in mk_list_del (entry=0x7f08b00073d0) at /home/edsiper/fluent-bit/lib/monkey/include/monkey/mk_core/mk_list.h:93
#6  0x00005622357a3bf0 in destroy_conn (u_conn=0x7f08b0007350) at /home/edsiper/fluent-bit/src/flb_upstream.c:256
#7  0x00005622357a45eb in flb_upstream_conn_release (conn=0x7f08b0007350) at /home/edsiper/fluent-bit/src/flb_upstream.c:551
#8  0x0000562235834bb6 in cb_splunk_flush (data=0x7f08b8076220, bytes=1188356, tag=0x7f08b802f4a0 "dummy.0", tag_len=7, i_ins=0x562237855bf0, out_context=0x7f08b802c2d0, config=0x56223784a2c0)
    at /home/edsiper/fluent-bit/plugins/out_splunk/splunk.c:225
#9  0x0000562235790ae7 in output_pre_cb_flush () at /home/edsiper/fluent-bit/include/fluent-bit/flb_output.h:460
#10 0x0000562235a9fa47 in co_init () at /home/edsiper/fluent-bit/lib/monkey/deps/flb_libco/amd64.c:117
#11 0x00005622378510f0 in ?? ()
```

for some reason, the connection node is not linked on any upstream list (available, busy or destroy), the node have prev=NULL and next=NULL

**Comment by edsiper** [comment]
@hsmatulisgoogle have you seen something similar in your tests ?

**Comment by edsiper** [comment]
The issue associated with keepalive connections. Having set -p net.keepalive=off does not lead to corruption.

work in process.

**Comment by edsiper** [comment]
```
==3720675== Thread 7 flb-out-splunk.0:
==3720675== Invalid read of size 8
==3720675==    at 0x17E624: flb_upstream_conn_release (flb_upstream.c:502)
==3720675==    by 0x20EE3E: cb_splunk_flush (splunk.c:225)
==3720675==    by 0x16AD56: output_pre_cb_flush (flb_output.h:460)
==3720675==    by 0x475526: co_init (amd64.c:117)
==3720675==    by 0x3A22656761737364: ???
==3720675==    by 0x7D22796D6D756421: ???
==3720675==  Address 0xbb6fab8 is 120 bytes inside a block of size 160 free'd
==3720675==    at 0x483DA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3720675==    by 0x17D4C6: flb_free (flb_mem.h:122)
==3720675==    by 0x17EB7A: flb_upstream_conn_pending_destroy (flb_upstream.c:644)
==3720675==    by 0x17EBFD: flb_upstream_conn_pending_destroy_list (flb_upstream.c:662)
==3720675==    by 0x16BAA9: output_thread (flb_output_thread.c:261)
==3720675==    by 0x17F9AA: step_callback (flb_worker.c:44)
==3720675==    by 0x487858F: start_thread (pthread_create.c:463)
==3720675==    by 0x4F41222: clone (clone.S:95)
==3720675==  Block was alloc'd at
==3720675==    at 0x483ED99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
```

**Comment by edsiper** [comment]
I think I found the root cause of the problem. Upstream connections are actually linked to the parent output instance and protected through a Mutex, but there are a few cases where an available persistent connection might be assigned to a different worker thread, looks like the connection context is registered in more than one event loop at a time generating the corruption.

Still troubleshooting this...

**Comment by edsiper** [comment]
Several changes implemented and the issue is gone:

- coroutines are listed only on either output plugin linked list, or if in a worker, in a thread-storage list; they are fully isolated, all mutexes are removed.
- similar to co-routines upstream connections are handled either in an instance or per worker through a thread-storage list, no more mutexes or race conditions are faced.

all fixes are in GIT master.
