### ISSUE TITLE
[external issue] crash with "concurrent map iteration and map write" in GKE

### ISSUE THREAD

**Issue by danielhoherd** [fluent/fluent-bit#2956]
## Bug Report

**Describe the bug**

On some nodes, fluentbit frequently crashes with error `concurrent map iteration and map write`. Depending on workload, fluentbit sometimes crashes several hundred times a day on busy nodes due to this problem.

**To Reproduce**
- Example log message if applicable:
Here is the first ~100 lines of a ~1450 line trace. I can provide a full trace if needed.
```
I0119 21:52:11.445255       1 stackdriver.go:94] Stackdriver sink is configured for project: REDACTED, cluster-name: REDACTED, instance: REDACTED
I0119 21:52:11.445285       1 server.go:47] Configured Fluent Bit GKE plugin server to run on the port 2021
W0119 21:52:12.029482       1 cache.go:66] Failed to refresh a cache: failed to refresh a cache: too frequent updates of the cache
… ~20 of these lines …
W0119 21:52:57.002245       1 cache.go:66] Failed to refresh a cache: failed to refresh a cache: too frequent updates of the cache
fatal error: concurrent map iteration and map write

goroutine 2091 [running]:
runtime.throw(0x1160bc7, 0x26)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000659240 sp=0xc000659210 pc=0x4376d2
runtime.mapiternext(0xc0000c4c00)
	/usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc0006592c0 sp=0xc000659240 pc=0x410d14
reflect.mapiternext(0xc0000c4c00)
	/usr/local/go/src/runtime/map.go:1337 +0x2b fp=0xc0006592d8 sp=0xc0006592c0 pc=0x467c8b
reflect.(*MapIter).Next(0xc00025eac0, 0x18a)
	/usr/local/go/src/reflect/value.go:1276 +0xd6 fp=0xc000659300 sp=0xc0006592d8 pc=0x4a2376
google.golang.org/protobuf/internal/impl.appendMap(0xc000c7c800, 0x1c3, 0x71a, 0xfd96c0, 0xc0005549e0, 0x195, 0xc00015b040, 0xc000126490, 0xc00079c102, 0x2, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/internal/impl/codec_map.go:275 +0x105 fp=0xc0006593b8 sp=0xc000659300 pc=0xccce85
google.golang.org/protobuf/internal/impl.encoderFuncsForMap.func2(0xc000c7c800, 0x15d, 0x71a, 0xc0005549e0, 0xc000126490, 0x7fa2ab14e502, 0xc000c7c800, 0x15d, 0x71a, 0x0, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/internal/impl/codec_map.go:57 +0xbd fp=0xc000659440 sp=0xc0006593b8 pc=0xcf821d
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(0xc000560138, 0xc000c7c800, 0x0, 0x71a, 0xc0005549a0, 0xc0004ad302, 0x10100c000659538, 0x0, 0x71a, 0xc000c7c800, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/internal/impl/encode.go:138 +0x10a fp=0xc0006594d8 sp=0xc000659440 pc=0xcde2aa
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal(0xc000560138, 0x12cfe40, 0xc0005549a0, 0xc000c7c800, 0x0, 0x71a, 0x2, 0x44f04c, 0x800, 0xf91ec0, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/internal/impl/encode.go:106 +0x8c fp=0xc000659540 sp=0xc0006594d8 pc=0xcde0ec
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal-fm(0x12cfe40, 0xc0005549a0, 0xc000c7c800, 0x0, 0x71a, 0x2, 0x203000, 0xc000659618, 0x40b985, 0xff4140, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/internal/impl/encode.go:99 +0x52 fp=0xc0006595b0 sp=0xc000659540 pc=0xd043d2
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0xc0005dc500, 0x0, 0x48c, 0x12cfe40, 0xc0005549a0, 0x129e6c0, 0xc0005549a0, 0x500, 0xc0005dc500, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/proto/encode.go:166 +0x2c7 fp=0xc000659668 sp=0xc0006595b0 pc=0xc6e007
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1000001, 0xc0005dc500, 0x0, 0x48c, 0x129e6c0, 0xc0005549a0, 0x7fa2d21f3108, 0x0, 0x10, 0xc0002bd800, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x98 fp=0xc0006596d0 sp=0xc000659668 pc=0xc6dbb8
github.com/golang/protobuf/proto.marshalAppend(0xc0005dc500, 0x0, 0x48c, 0x7fa2ab2e8298, 0xc0005549a0, 0xc000659700, 0x478994, 0x1945140, 0x0, 0x110f1c0, ...)
	/go/src/gke-logmon/fluent-bit/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xc7 fp=0xc000659770 sp=0xc0006596d0 pc=0xd0e447
github.com/golang/protobuf/proto.(*Buffer).Marshal(...)
	/go/src/gke-logmon/fluent-bit/vendor/github.com/golang/protobuf/proto/buffer.go:111
google.golang.org/grpc/encoding/proto.marshal(0x10ab160, 0xc0005549a0, 0xc000a88c60, 0x0, 0x0, 0x0, 0xc000659878, 0xda4ac5)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/encoding/proto/proto.go:59 +0x111 fp=0xc0006597f0 sp=0xc000659770 pc=0xd749b1
google.golang.org/grpc/encoding/proto.codec.Marshal(0x10ab160, 0xc0005549a0, 0x203000, 0x1, 0x11b6110, 0x203000, 0x203000)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/encoding/proto/proto.go:74 +0xb3 fp=0xc000659870 sp=0xc0006597f0 pc=0xd74b53
google.golang.org/grpc/encoding/proto.(*codec).Marshal(0x1992d58, 0x10ab160, 0xc0005549a0, 0x190b068, 0xc000659978, 0x40d950, 0xc00025ea40, 0x20)
	<autogenerated>:1 +0x46 fp=0xc0006598b8 sp=0xc000659870 pc=0xd75426
google.golang.org/grpc.encode(0x7fa2ab146858, 0x1992d58, 0x10ab160, 0xc0005549a0, 0x0, 0xc00007a800, 0x7fa2d21f3108, 0x0, 0x1003032223a)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/rpc_util.go:538 +0x52 fp=0xc000659918 sp=0xc0006598b8 pc=0xd9ea12
google.golang.org/grpc.prepareMsg(0x10ab160, 0xc0005549a0, 0x7fa2ab146858, 0x1992d58, 0x0, 0x0, 0x0, 0x0, 0x3265363363366235, 0xc0003e4290, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/stream.go:1541 +0x107 fp=0xc0006599b8 sp=0xc000659918 pc=0xda9f67
google.golang.org/grpc.(*clientStream).SendMsg(0xc0009945a0, 0x10ab160, 0xc0005549a0, 0x0, 0x0)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/stream.go:722 +0x165 fp=0xc000659b48 sp=0xc0006599b8 pc=0xda60a5
google.golang.org/grpc.invoke(0x12be5e0, 0xc000a80de0, 0x1171c46, 0x33, 0x10ab160, 0xc0005549a0, 0x1039760, 0xc000a80e10, 0xc000359180, 0xc0003e42d0, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/call.go:70 +0xe4 fp=0xc000659bd0 sp=0xc000659b48 pc=0xd8fd24
google.golang.org/grpc.(*ClientConn).Invoke(0xc000359180, 0x12be5e0, 0xc000a80de0, 0x1171c46, 0x33, 0x10ab160, 0xc0005549a0, 0x1039760, 0xc000a80e10, 0x0, ...)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/grpc/call.go:37 +0x1b3 fp=0xc000659c70 sp=0xc000659bd0 pc=0xd8fb13
google.golang.org/genproto/googleapis/logging/v2.(*loggingServiceV2Client).WriteLogEntries(0xc0003e4540, 0x12be5e0, 0xc000a80de0, 0xc0005549a0, 0x0, 0x0, 0x0, 0x10, 0x20, 0xc00025e840)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/genproto/googleapis/logging/v2/logging.pb.go:1294 +0xd4 fp=0xc000659cf8 sp=0xc000659c70 pc=0xe4d934
cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries.func1(0x12be5e0, 0xc000a80de0, 0x11b4350, 0x0, 0x0, 0x0, 0xc000888dc0, 0x40e2b8)
	/go/src/gke-logmon/fluent-bit/vendor/cloud.google.com/go/logging/apiv2/logging_client.go:226 +0x84 fp=0xc000659d60 sp=0xc000659cf8 pc=0xe5a544
github.com/googleapis/gax-go/v2.invoke(0x12be5e0, 0xc000a80de0, 0xc000659eb0, 0x11b4350, 0x0, 0x0, 0x0, 0x11b5448, 0x0, 0x0)
	/go/src/gke-logmon/fluent-bit/vendor/github.com/googleapis/gax-go/v2/invoke.go:70 +0x90 fp=0xc000659dd0 sp=0xc000659d60 pc=0xdafdf0
github.com/googleapis/gax-go/v2.Invoke(0x12be5e0, 0xc000a80de0, 0xc000888eb0, 0xc0003e4500, 0x1, 0x1, 0xc000a80de0, 0xc0004e2ed0)
	/go/src/gke-logmon/fluent-bit/vendor/github.com/googleapis/gax-go/v2/invoke.go:48 +0xf6 fp=0xc000659e48 sp=0xc000659dd0 pc=0xdafb76
cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries(0xc000203770, 0x12be5e0, 0xc000a80de0, 0xc0005549a0, 0x0, 0x0, 0x1, 0x0, 0xf6eac0, 0xc00025e800)
	/go/src/gke-logmon/fluent-bit/vendor/cloud.google.com/go/logging/apiv2/logging_client.go:224 +0x1b7 fp=0xc000659ee0 sp=0xc000659e48 pc=0xe58977
cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc000733300, 0xc000a73ac0, 0x2, 0x2)
	/go/src/gke-logmon/fluent-bit/vendor/cloud.google.com/go/logging/logging.go:860 +0x151 fp=0xc000659f60 sp=0xc000659ee0 pc=0xe614b1
cloud.google.com/go/logging.(*Client).Logger.func2(0xf6eac0, 0xc00025e800)
	/go/src/gke-logmon/fluent-bit/vendor/cloud.google.com/go/logging/logging.go:464 +0x5a fp=0xc000659f90 sp=0xc000659f60 pc=0xe621ba
google.golang.org/api/support/bundler.(*Bundler).handle(0xc0007b46e0, 0xc000a80d20)
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/api/support/bundler/bundler.go:324 +0x71 fp=0xc000659fd0 sp=0xc000659f90 pc=0xe5d4f1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000659fd8 sp=0xc000659fd0 pc=0x46e701
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle
	/go/src/gke-logmon/fluent-bit/vendor/google.golang.org/api/support/bundler/bundler.go:179 +0x1ad

goroutine 1 [chan receive, 3 minutes]:
main.main()
	/go/src/gke-logmon/fluent-bit/main.go:172 +0x42c

goroutine 33 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x19602a0)
	/go/src/gke-logmon/fluent-bit/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/go/src/gke-logmon/fluent-bit/vendor/github.com/golang/glog/glog.go:410 +0x274
```

- Steps to reproduce the problem: run a cluster (or in our case a single GKE node-pool within a cluster) with LOTS of short-lived pod creations occurring.

**Expected behavior**

fluent-bit does not crash frequently

**Your Environment**
* Version used: fluent-bit:v1.3.11-gke.0
* Configuration: default GKE config
* Environment name and version: k8s 1.14 through 1.17, same behavior on all
* Server type and version: n1-standard-16, n1-standard-32
* Operating System and version: default available COS
* Filters and plugins: no special configs or plugins

**Additional context**

The main down-side here is we miss logs on affected machines for a brief period of time. We are interrupted by alerts that go off when any daemonset has a high restart rate.

**Comment by edsiper** [comment]
@hsmatulisgoogle I think this is GKE specific issue since the connector in use is not part of upstream project, can you take a look or advice ?

**Comment by hsmatulisgoogle** [comment]
This looks like a GKE specific issue, but I am not familiar with that part of the codebase

**Comment by edsiper** [comment]
@danielhoherd since the crash is in a custom plugin by Google, I'd suggest you open a ticket with Google team directly for assistance, we don't have access to that code.

**Comment by edsiper** [comment]
Closing the ticket since it's not associated with Fluent Bit code base
