### ISSUE TITLE
Fluent bit forwards invalid chunked data to fluentd

### ISSUE THREAD

**Issue by apollo13** [fluent/fluent-bit#3089]
## Bug Report

**Describe the bug**
I have fluent bit configured to write chunks onto the filesystem; after a restart it tries to resend a chunkfile:
```
[2021/02/18 14:35:45] [ info] [input:storage_backlog:storage_backlog.5] queueing tail.4:3394-1613485990.88176579.flb
[2021/02/18 14:35:49] [error] [output:forward:forward.0] cannot get ack
[2021/02/18 14:35:49] [ warn] [engine] failed to flush chunk '3394-1613485990.88176579.flb', retry in 9 seconds: task_id=1, input=storage_backlog.5 > output=forward.0 (out_id=0)
[2021/02/18 14:35:58] [error] [output:forward:forward.0] cannot get ack
[2021/02/18 14:35:58] [ warn] [engine] failed to flush chunk '3394-1613485990.88176579.flb', retry in 86 seconds: task_id=1, input=storage_backlog.5 > output=forward.0 (out_id=0)
```
I have saved the chunk file and can provide it to maintainers on request (I rather not paste it publicly). Fluent Bit version is 1.7.0. I have used tcpdump to record forwarded data and decoded it from msgpack. The messages are as follows:

```
['audit.system',
 [[ExtType(code=0, data=b'`+\xd7\xa6\x05 A\x80'),
   {'id': '59931',
    'message': 'pid=3670 uid=0 auid=1000 ses=1167 '
               "subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login "
               'id=1000 exe="/usr/sbin/sshd" hostname=10.7.22.120 '
               "addr=10.7.22.120 terminal=ssh res=success'",
    'source': 'XXX',
    'type': 'USER_LOGIN'}],
  [ExtType(code=0, data=b'`+\xd7\xa6\x05 A\x80'),
   {'id': '59932',
    'message': 'pid=3670 uid=0 auid=1000 ses=1167 '
               "subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login "
               'id=1000 exe="/usr/sbin/sshd" hostname=10.7.22.120 '
               "addr=10.7.22.120 terminal=ssh res=success'",
    'source': 'XXX',
    'type': 'USER_START'}],
  [ExtType(code=0, data=b'`+\xd7\xa6\x05>\xc6\x00'),
   {'id': '59933',
    'message': 'pid=3670 uid=0 auid=1000 ses=1167 '
               "subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy "
               'kind=server '
               'fp=XXX '
               'direction=? spid=4302 suid=1000  exe="/usr/sbin/sshd" '
               "hostname=? addr=? terminal=? res=success'",
    'source': 'XXX',
    'type': 'CRYPTO_KEY_USER'}],
  [ExtType(code=0, data=b'`+\xd7\xa6\t\x0fV\x00'),
   {'id': '59934',
    'message': 'pid=4311 uid=1000 auid=1000 ses=1167 '
               'subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 '
               "msg='op=PAM:accounting grantors=pam_unix,pam_localuser "
               'acct="admin" exe="/usr/bin/sudo" hostname=? addr=? terminal=? '
               "res=success'",
    'source': 'XXX',
    'type': 'USER_ACCT'}],
  [ExtType(code=0, data=b'`+\xd7\xa6\t\x0fV\x00'),
   {'id': '59935',
    'message': 'pid=4311 uid=1000 auid=1000 ses=1167 '
               'subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 '
               'msg=\'cwd="/home/admin" '
               'cmd=XXX '
               "terminal=? res=success'",
    'source': 'XXX',
    'type': 'USER_CMD'}],
  [ExtType(code=0, data=b'`+\xd7\xa6\t-\xda\x80'),
   {'id': '59936',
    'message': 'pid=4311 uid=0 auid=1000 ses=1167 '
               'subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 '
               "msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix "
               'acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? '
               "res=success'",
    'source': 'XXX',
    'type': 'CRED_REFR'}],
  [ExtType(code=0, data=b'`+\xd7\xa6\tj\xe3\x80'),
   {'id': '59937',
    'message': 'pid=4311 uid=0 auid=1000 ses=1167 '
               'subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 '
               "msg='op=PAM:session_open "
               'grantors=pam_keyinit,pam_keyinit,pam_limits,pam_systemd,pam_unix '
               'acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? '
               "res=success'",
    'source': 'XXX',
    'type': 'USER_START'}],
  0,
  0,
# Many many zeroes
  0,
  0],
 {'chunk': '03c074179db0aa7c2cce91eb9e9121a1', 'size': 1732}]
```

I have checked that the number of items is indeed 1732; all of them but the first few are zero. This causes the remote fluentd to reject the message:

```
2021-02-18 15:13:51 +0100 [warn]: #0 emit transaction failed: error_class=ArgumentError error="record must be a Hash: Integer" location="/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:826:in `metadata'" tag="audit.system"
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:826:in `metadata'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:953:in `block in handle_stream_with_custom_format'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/event.rb:196:in `block in each'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/event.rb:195:in `each'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/event.rb:195:in `each'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:952:in `handle_stream_with_custom_format'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:880:in `execute_chunking'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:808:in `emit_buffered'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:97:in `emit_stream'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/in_forward.rb:338:in `on_message'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/server.rb:613:in `on_read_without_connection'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:123:in `on_readable'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:186:in `on_readable'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-02-18 15:13:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-02-18 15:13:51 +0100 [error]: #0 [input_forward] unexpected error on reading data host="10.7.220.110" port=57202 error_class=ArgumentError error="record must be a Hash: Integer"
```

- Steps to reproduce the problem:

I am not sure how to reproduce it, I do have a chunk file that I can provide on request that cause fluent-bit to emit those broken (?) messages. I am also not sure whether the plugin is on the client side or on the server side. Reading the protocol spec I think that fluent-bit should not send those "0" entries, those are not valid "events" (time + record combo)

**Your Environment**

* Version used: 1.7.0
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):  bare metal
* Server type and version: Fluentd 4.0.1
* Operating System and version: CentOS 7
* Filters and plugins:

**Comment by edsiper** [comment]
@apollo13 thanks for reporting this issue.

would you please email me the chunk file: edsiper at gmail.com . thanks

**Comment by edsiper** [comment]
note: please also share your full configuration

**Comment by apollo13** [comment]
Configuration:
```
[SERVICE]
    Daemon Off
    Parsers_File parsers.conf
    # Plugins_File plugins.conf
    Log_File /var/log/td-agent-bit.log
    Log_Level trace
    Grace 5

    storage.path /var/lib/flb-storage/
    storage.sync normal
    storage.metrics on

    HTTP_Server  On
    HTTP_Listen  127.0.0.1
    HTTP_PORT    2020

[INPUT]
    Name tail
    Path /var/opt/ra/log/ra-gate-audit-general.log
    DB /var/lib/flb-storage/audit.ra-gate.log.db
    Tag audit.ra-gate
    Key message
    Multiline On
    Parser_Firstline audit-firstline
    storage.type filesystem
    mem_buf_limit 5M

[INPUT]
    Name tail
    Path /var/opt/ro/log/ro-gate-audit-general.log
    DB /var/lib/flb-storage/audit.ro-gate.log.db
    Tag audit.ro-gate
    Key message
    Multiline On
    Parser_Firstline audit-firstline
    storage.type filesystem
    mem_buf_limit 5M

[INPUT]
    Name tail
    Path /var/opt/cm/log/cm-audit-general.log
    DB /var/lib/flb-storage/audit.cm.log.db
    Tag audit.cm
    Key message
    Multiline On
    Parser_Firstline audit-firstline
    storage.type filesystem
    mem_buf_limit 5M


[INPUT]
    Name forward
    storage.type filesystem
    mem_buf_limit 5M

[INPUT]
    Name tail
    Path /var/log/audit/audit.log
    DB /var/lib/flb-storage/audit.system.log.db
    Tag audit.system
    Key message
    Parser auditd
    storage.type filesystem
    mem_buf_limit 5M

[OUTPUT]
    # TODO: TLS
    Name forward
    Match *
    Host upstream
    Port 24225
    Require_ack_response true
    # Do not loose any data!
    Retry_Limit False

[FILTER]
    Name record_modifier
    Match *
    Record source ${HOSTNAME}
```

**Comment by edsiper** [comment]
## Resolution

I've found that the provided chunk was not corrupted. The thing is that the chunk on runtime always contains more space to store future data, if Fluent Bit was killed or forcedly stopped this remaining space contains extra zeros, so then in a further start of Fluent Bit this becomes invalid data.

I've pushed the following fixes:

- 854762a1  in_storage_backlog: remove failed chunks from queue on load (#3089)
- 075645d0 input_chunk: validate chunks and adjust size if required (#3089)
- 69ab1a31 mp: new function to validate chunk content

The new behavior adds an extra validation of backlog chunks, they are fully validated, and if extra data is found, if they are zeros, the chunk is adjusted, otherwise, if it contains corrupted info it's just discarded.

**Comment by edsiper** [comment]
I will release these changes as part of v1.7.1.

thanks again for your help
