### ISSUE TITLE
Segfault in TLS with Fluent Bit 1.7.3

### ISSUE THREAD

**Issue by zhonghui12** [fluent/fluent-bit#3331]
## Bug Report

**Describe the bug**

Our customers report a segfault in Fluent Bit 1.7.2 and here is the core-dump info:
```
(gdb) where
#0  0x00007f3c997a41bb in abort () from /lib64/libc.so.6
#1  0x0000000000445f99 in flb_signal_handler (signal=11) at /tmp/fluent-bit-1.7.2/src/fluent-bit.c:510
#2  0x00007f3c9511ebed in runtime.sigfwd () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:337
#3  0x00007f3c7b9f2e08 in ?? ()
#4  0x00007f3c9510531a in runtime.sigfwdgo (sig=11, info=0x7f3c7b9f32f0, ctx=0x7f3c7b9f31c0, ~r3=<optimized out>) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:662
#5  0x00007f3c951044c0 in runtime.sigtrampgo (sig=<optimized out>, info=0x7f3c7b9f32f0, ctx=0x7f3c7b9f31c0) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:289
#6  0x00007f3c9511ec43 in runtime.sigtramp () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:357
#7  0x00007f3c8e155ddd in runtime.sigfwd () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:337
#8  0x00007f3c7b9f2f58 in ?? ()
#9  0x00007f3c8e13c50a in runtime.sigfwdgo (sig=11, info=0x7f3c7b9f32f0, ctx=0x7f3c7b9f31c0, ~r3=<optimized out>) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:662
#10 0x00007f3c8e13b6b0 in runtime.sigtrampgo (sig=<optimized out>, info=0x7f3c7b9f32f0, ctx=0x7f3c7b9f31c0) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:289
#11 0x00007f3c8e155e33 in runtime.sigtramp () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:357
#12 0x00007f3c837a361d in runtime.sigfwd () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:337
#13 0x00007f3c7b9f30a8 in ?? ()
#14 0x00007f3c83789a7a in runtime.sigfwdgo (sig=11, info=0x7f3c7b9f32f0, ctx=0x7f3c7b9f31c0, ~r3=<optimized out>) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:662
#15 0x00007f3c83788c20 in runtime.sigtrampgo (sig=<optimized out>, info=0x7f3c7b9f32f0, ctx=0x7f3c7b9f31c0) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:289
#16 0x00007f3c837a3673 in runtime.sigtramp () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:357
#17 <signal handler called>
#18 0x000000000044fc86 in tcache_dalloc_large (slow_path=false, binind=<optimized out>, ptr=0x7f3c7a009278, tcache=<optimized out>, tsd=<optimized out>)
    at /tmp/fluent-bit-1.7.2/lib/jemalloc-5.2.1/include/jemalloc/internal/tcache_inlines.h:210
#19 arena_dalloc_large (slow_path=false, szind=0, tcache=<optimized out>, ptr=0x7f3c7a009278, tsdn=<optimized out>) at /tmp/fluent-bit-1.7.2/lib/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:276
#20 arena_dalloc (slow_path=false, alloc_ctx=<synthetic pointer>, tcache=<optimized out>, ptr=0x7f3c7a009278, tsdn=<optimized out>)
    at /tmp/fluent-bit-1.7.2/lib/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:323
#21 idalloctm (slow_path=false, is_internal=false, alloc_ctx=<synthetic pointer>, tcache=<optimized out>, ptr=0x7f3c7a009278, tsdn=<optimized out>)
    at /tmp/fluent-bit-1.7.2/lib/jemalloc-5.2.1/include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#22 ifree (slow_path=false, tcache=<optimized out>, ptr=0x7f3c7a009278, tsd=0x7f3c7b9f44b0) at /tmp/fluent-bit-1.7.2/lib/jemalloc-5.2.1/src/jemalloc.c:2586
#23 je_free_default (ptr=0x7f3c7a009278) at /tmp/fluent-bit-1.7.2/lib/jemalloc-5.2.1/src/jemalloc.c:2790
#24 0x00007f3c9a743e7b in asn1_primitive_free () from /lib64/libcrypto.so.1.1
#25 0x00007f3c9a7442d9 in asn1_template_free () from /lib64/libcrypto.so.1.1
#26 0x00007f3c9a7440e7 in asn1_item_embed_free () from /lib64/libcrypto.so.1.1
#27 0x00007f3c9a7442d9 in asn1_template_free () from /lib64/libcrypto.so.1.1
#28 0x00007f3c9a7440e7 in asn1_item_embed_free () from /lib64/libcrypto.so.1.1
#29 0x00007f3c9a744205 in ASN1_item_free () from /lib64/libcrypto.so.1.1
#30 0x00007f3c9a883747 in OPENSSL_sk_pop_free () from /lib64/libcrypto.so.1.1
#31 0x00007f3c9abb568e in SSL_free () from /lib64/libssl.so.1.1
#32 0x00000000004efd19 in tls_session_destroy (session=0x7f3c7ab18c90) at /tmp/fluent-bit-1.7.2/src/tls/openssl.c:338
#33 0x00000000004f088a in flb_tls_session_destroy (tls=0x7f3c7aa89c40, u_conn=0x7f3c7aa3ae80) at /tmp/fluent-bit-1.7.2/src/tls/flb_tls.c:394
#34 0x00000000004e2768 in destroy_conn (u_conn=0x7f3c7aa3ae80) at /tmp/fluent-bit-1.7.2/src/flb_upstream.c:345
#35 0x00000000004e33a6 in flb_upstream_conn_pending_destroy (u=0x7f3c7aa6fa40) at /tmp/fluent-bit-1.7.2/src/flb_upstream.c:712
#36 0x00000000004e34df in flb_upstream_conn_pending_destroy_list (list=0x7f3c968197c0) at /tmp/fluent-bit-1.7.2/src/flb_upstream.c:758
#37 0x00000000004dc9a0 in flb_engine_start (config=0x7f3c96819500) at /tmp/fluent-bit-1.7.2/src/flb_engine.c:691
#38 0x00000000004c24db in flb_lib_worker (data=0x7f3c96818000) at /tmp/fluent-bit-1.7.2/src/flb_lib.c:493
#39 0x00007f3c9b24440b in start_thread () from /lib64/libpthread.so.0
#40 0x00007f3c9985c09f in clone () from /lib64/libc.so.6
```

**Your Environment**

* Version used: 1.7.2
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
Also, I have found a commit to fix the issue in TLS: https://github.com/fluent/fluent-bit/commit/4816eeea33428514a82aeb26f945146f6ef86732. Just wonder if it is related. Thanks.

**Comment by edsiper** [comment]
I would advise trying to reproduce with v1.7.3. If the issue is reproducible, provide detailed steps to reproduce it.

**Comment by zhonghui12** [comment]
Update: this problem doesn't occur in Fluent Bit 1.6.x. Our customers are trying the Fluent Bit 1.7.3 now and will post the update later

**Comment by randym13** [comment]
This issue occurs and can be reproduced when the Splunk HECs become non-responsive.  In our case, the indexers were at 100% CPU for several hours.  

Here is the new strack trace from 1.7.3:
```
(gdb) where
#0  0x00007f900bc661bb in abort () from /lib64/libc.so.6
#1  0x0000000000445f99 in flb_signal_handler (signal=11) at /tmp/fluent-bit-1.7.3/src/fluent-bit.c:510
#2  0x00007f900771ebed in runtime.sigfwd () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:337
#3  0x00007f8fefc7d708 in ?? ()
#4  0x00007f900770531a in runtime.sigfwdgo (sig=11, info=0x7f8fefc7dbf0, ctx=0x7f8fefc7dac0, ~r3=<optimized out>) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:662
#5  0x00007f90077044c0 in runtime.sigtrampgo (sig=<optimized out>, info=0x7f8fefc7dbf0, ctx=0x7f8fefc7dac0) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:289
#6  0x00007f900771ec43 in runtime.sigtramp () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:357
#7  0x00007f8fff70988d in runtime.sigfwd () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:337
#8  0x00007f8fefc7d858 in ?? ()
#9  0x00007f8fff6effba in runtime.sigfwdgo (sig=11, info=0x7f8fefc7dbf0, ctx=0x7f8fefc7dac0, ~r3=<optimized out>) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:662
#10 0x00007f8fff6ef160 in runtime.sigtrampgo (sig=<optimized out>, info=0x7f8fefc7dbf0, ctx=0x7f8fefc7dac0) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:289
#11 0x00007f8fff7098e3 in runtime.sigtramp () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:357
#12 0x00007f8ff65a361d in runtime.sigfwd () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:337
#13 0x00007f8fefc7d9a8 in ?? ()
#14 0x00007f8ff6589a7a in runtime.sigfwdgo (sig=11, info=0x7f8fefc7dbf0, ctx=0x7f8fefc7dac0, ~r3=<optimized out>) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:662
#15 0x00007f8ff6588c20 in runtime.sigtrampgo (sig=<optimized out>, info=0x7f8fefc7dbf0, ctx=0x7f8fefc7dac0) at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/signal_unix.go:289
#16 0x00007f8ff65a3673 in runtime.sigtramp () at /home/.gimme/versions/go1.13.linux.amd64/src/runtime/sys_linux_amd64.s:357
#17 <signal handler called>
#18 0x00007f900cbfc4f0 in asn1_string_embed_free () from /lib64/libcrypto.so.1.1
#19 0x00007f900cc05e7b in asn1_primitive_free () from /lib64/libcrypto.so.1.1
#20 0x00007f900cc062d9 in asn1_template_free () from /lib64/libcrypto.so.1.1
#21 0x00007f900cc060e7 in asn1_item_embed_free () from /lib64/libcrypto.so.1.1
#22 0x00007f900cc062d9 in asn1_template_free () from /lib64/libcrypto.so.1.1
#23 0x00007f900cc060e7 in asn1_item_embed_free () from /lib64/libcrypto.so.1.1
#24 0x00007f900cc06205 in ASN1_item_free () from /lib64/libcrypto.so.1.1
#25 0x00007f900cd45747 in OPENSSL_sk_pop_free () from /lib64/libcrypto.so.1.1
#26 0x00007f900d07768e in SSL_free () from /lib64/libssl.so.1.1
#27 0x00000000004efdd4 in tls_session_destroy (session=0x7f8feefccdf8) at /tmp/fluent-bit-1.7.3/src/tls/openssl.c:338
#28 0x00000000004f0945 in flb_tls_session_destroy (tls=0x7f8feee89c40, u_conn=0x7f8feee3ae80) at /tmp/fluent-bit-1.7.3/src/tls/flb_tls.c:394
#29 0x00000000004e275b in destroy_conn (u_conn=0x7f8feee3ae80) at /tmp/fluent-bit-1.7.3/src/flb_upstream.c:370
#30 0x00000000004e3445 in flb_upstream_conn_pending_destroy (u=0x7f8feee6fa40) at /tmp/fluent-bit-1.7.3/src/flb_upstream.c:760
#31 0x00000000004e359a in flb_upstream_conn_pending_destroy_list (list=0x7f9008e19680) at /tmp/fluent-bit-1.7.3/src/flb_upstream.c:810
#32 0x00000000004dc92a in flb_engine_start (config=0x7f9008e193c0) at /tmp/fluent-bit-1.7.3/src/flb_engine.c:691
#33 0x00000000004c24db in flb_lib_worker (data=0x7f9008e18000) at /tmp/fluent-bit-1.7.3/src/flb_lib.c:493
#34 0x00007f900d70640b in start_thread () from /lib64/libpthread.so.0
#35 0x00007f900bd1e09f in clone () from /lib64/libc.so.6
```

Here is what the logs looked like before the segmentation fault:

```
[2021/04/08 07:45:01] [ warn] [output:splunk:splunk.1] http_status=503:
{"text":"Server is busy","code":9,"invalid-event-number":0}
[2021/04/08 07:45:01] [ warn] [engine] failed to flush chunk '1-1617867893.408165922.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:46:06] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:46:06] [ warn] [engine] failed to flush chunk '1-1617867953.411414056.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:46:13] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:46:13] [ warn] [engine] failed to flush chunk '1-1617867963.412847568.flb', retry in 8 seconds: task_id=1, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:49:03] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:49:03] [ warn] [engine] failed to flush chunk '1-1617868133.458722038.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:49:03] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:49:03] [ warn] [engine] failed to flush chunk '1-1617868133.458722038.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:52:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:52:56] [ warn] [engine] failed to flush chunk '1-1617868373.548047560.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:55:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:55:56] [ warn] [engine] failed to flush chunk '1-1617868553.617232375.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:56:01] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:56:01] [ warn] [engine] failed to flush chunk '1-1617868556.997277514.flb', retry in 9 seconds: task_id=1, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:55:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:55:56] [ warn] [engine] failed to flush chunk '1-1617868553.617232375.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:56:01] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:56:01] [ warn] [engine] failed to flush chunk '1-1617868556.997277514.flb', retry in 9 seconds: task_id=1, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:56:24] [ warn] [output:splunk:splunk.1] http_status=503:
{"text":"Server is busy","code":9,"invalid-event-number":0}
[2021/04/08 07:56:24] [ warn] [engine] chunk '1-1617868556.997277514.flb' cannot be retried: task_id=1, input=forward.0 > output=splunk.1
[2021/04/08 07:56:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:56:56] [ warn] [engine] failed to flush chunk '1-1617868613.639277904.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 07:57:06] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 07:57:06] [ warn] [engine] failed to flush chunk '1-1617868616.248166064.flb', retry in 11 seconds: task_id=1, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:00:58] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:00:58] [ warn] [engine] failed to flush chunk '1-1617868853.734887957.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:01:59] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:01:59] [ warn] [engine] failed to flush chunk '1-1617868913.749959195.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:06:11] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:06:11] [ warn] [engine] failed to flush chunk '1-1617869163.847293431.flb', retry in 7 seconds: task_id=1, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:07:28] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:07:28] [ warn] [engine] failed to flush chunk '1-1617869243.880928559.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:08:11] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:08:11] [ warn] [engine] failed to flush chunk '1-1617869283.894601322.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:07:28] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:07:28] [ warn] [engine] failed to flush chunk '1-1617869243.880928559.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:08:16] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:08:16] [ warn] [engine] failed to flush chunk '1-1617869291.997157206.flb', retry in 7 seconds: task_id=1, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:09:40] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:09:40] [ warn] [engine] failed to flush chunk '1-1617869363.931705383.flb', retry in 11 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:12:57] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:12:57] [ warn] [engine] failed to flush chunk '1-1617869574.14037048.flb', retry in 9 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:16:26] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:16:26] [ warn] [engine] failed to flush chunk '1-1617869784.98177378.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:16:46] [error] [upstream] connection #31 to hec-e1.pisplunk.aws-nonprod.cloud.com:443 timed out after 10 seconds
[2021/04/08 08:21:01] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:21:01] [ warn] [engine] failed to flush chunk '1-1617870054.215997990.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:21:01] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:21:01] [ warn] [engine] failed to flush chunk '1-1617870054.215997990.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:22:59] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:22:59] [ warn] [engine] failed to flush chunk '1-1617870174.268074161.flb', retry in 11 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:26:32] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:26:32] [ warn] [engine] failed to flush chunk '1-1617870384.360624134.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:26:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:26:56] [ warn] [engine] failed to flush chunk '1-1617870414.374693118.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:27:11] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:27:11] [ warn] [engine] failed to flush chunk '1-1617870416.297460473.flb', retry in 6 seconds: task_id=6, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:27:16] [error] [upstream] connection #32 to hec-e1.pisplunk.aws-nonprod.cloud.com:443 timed out after 10 seconds
[2021/04/08 08:28:26] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:28:26] [ warn] [engine] failed to flush chunk '1-1617870504.403320910.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:29:31] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:29:31] [ warn] [engine] failed to flush chunk '1-1617870566.995072860.flb', retry in 10 seconds: task_id=6, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:29:26] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:29:26] [ warn] [engine] failed to flush chunk '1-1617870564.432995129.flb', retry in 11 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:32:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:32:56] [ warn] [engine] failed to flush chunk '1-1617870774.527648689.flb', retry in 7 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:38:56] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:38:56] [ warn] [engine] failed to flush chunk '1-1617871134.665274118.flb', retry in 6 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:40:15] [ warn] [output:splunk:splunk.1] http_status=503:
{"text":"Server is busy","code":9,"invalid-event-number":0}
[2021/04/08 08:40:15] [ warn] [engine] failed to flush chunk '1-1617871204.697957322.flb', retry in 7 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:41:09] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:41:09] [ warn] [engine] failed to flush chunk '1-1617871254.722309487.flb', retry in 8 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:43:02] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:43:02] [ warn] [engine] failed to flush chunk '1-1617871374.769964784.flb', retry in 10 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:49:41] [ warn] [output:splunk:splunk.1] http_status=503:
{"text":"Server is busy","code":9,"invalid-event-number":0}
[2021/04/08 08:49:41] [ warn] [engine] failed to flush chunk '1-1617871774.953887077.flb', retry in 11 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 08:51:26] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 08:51:26] [ warn] [engine] failed to flush chunk '1-1617871884.996530234.flb', retry in 11 seconds: task_id=0, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 09:01:26] [ warn] [output:splunk:splunk.1] http_status=0
[2021/04/08 09:01:26] [ warn] [engine] failed to flush chunk '1-1617872485.276514603.flb', retry in 11 seconds: task_id=6, input=forward.0 > output=splunk.1 (out_id=1)
[2021/04/08 09:01:31] [engine] caught signal (SIGSEGV)
```

**Comment by edsiper** [comment]
@randym13 which specific Fluent Bit distribution channel are you using ? DEB? RPM? docker image (if so..which)?, custom ?

**Comment by randym13** [comment]
> @randym13 which specific Fluent Bit distribution channel are you using ? DEB? RPM? docker image (if so..which)?, custom ?

docker -  amazon/aws-for-fluent-bit:2.13.0

**Comment by marckamerbeek** [comment]
Looks a lot like the problems we've seen with Elastic. [See 3301](https://github.com/fluent/fluent-bit/issues/3301)

@atheriel mentioned that the response buffer keeps growing until some sort of ending bit comes along. But that ending bit is not coming. The buffer grows untill Buffer_Size of es output pluging or an OOMKilled will happen if the Buffer_Size is set to False.

**Comment by zhonghui12** [comment]
Hello @edsiper, any update on this issue?

**Comment by edsiper** [comment]
I'd encourage you to try out v1.7.4 since this issue could be related to the scheduler file descriptor problem recently fixed. If the issue persists on v1.7.4 we will start the troubleshooting process.

**Comment by PettitWesley** [comment]
AWS for Fluent Bit has been updated to include 1.7.4: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.14.0

**Comment by edsiper** [comment]
If the issue persists on v1.7.4, let's open a new ticket and reference this one.

**Comment by lubingfeng** [comment]
@edsiper  any plan to get this addressed? Another end user also reported this issue.
