### ISSUE TITLE
SEGV in flb_filter_do

### ISSUE THREAD

**Issue by hligit** [fluent/fluent-bit#3681]
## Bug Report

**Describe the bug**
fluent-bit crashes with SEGV.

```
#0  __GI_abort () at abort.c:107
#1  0x000055e1215f8f01 in flb_signal_handler ()
#2  0x00007f6e01704dbd in runtime.sigfwd () at /usr/local/go/src/runtime/sys_linux_amd64.s:378
#3  0x00007f6dd65fb1a0 in ?? ()
#4  0x00007f6e016e3ec5 in runtime.sigfwdgo (sig=11, info=0x7f6dd65fb3b0, ctx=0x7f6dd65fb280, ~r3=<optimized out>)
    at /usr/local/go/src/runtime/signal_unix.go:1021
#5  0x00007f6e016e26f4 in runtime.sigtrampgo (sig=11, info=0x7f6dd65fb3b0, ctx=0x7f6dd65fb280)
    at /usr/local/go/src/runtime/signal_unix.go:416
#6  0x00007f6e01704e23 in runtime.sigtramp () at /usr/local/go/src/runtime/sys_linux_amd64.s:399
#7  <signal handler called>
#8  0x000055e12167cb28 in flb_filter_do ()
#9  0x000055e1216a4597 in flb_input_chunk_append_raw ()
#10 0x000055e1216b903f in flb_tail_file_chunk ()
#11 0x000055e1216b5e8e in in_tail_collect_static ()
#12 0x000055e12167c7f9 in flb_input_collector_fd ()
#13 0x000055e121689c31 in flb_engine_start ()
#14 0x000055e121673d81 in flb_lib_worker ()
#15 0x00007f6e03a95fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#16 0x00007f6e033e94cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**To Reproduce**

Not able to reproduce with a minimal test config. Happens all the time only on one of our production server.

- Example log message if applicable:
```
Fluent Bit v1.7.8
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/06/24 06:35:52] [ info] [engine] started (pid=1)
[2021/06/24 06:35:52] [ info] [storage] version=1.1.1, initializing...
[2021/06/24 06:35:52] [ info] [storage] root path '/fluent-bit/storage/chunk'
[2021/06/24 06:35:52] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=256
[2021/06/24 06:35:52] [ info] [storage] backlog input plugin: storage_backlog.3
[2021/06/24 06:35:52] [ info] [input:systemd:systemd] seek_cursor=s=81cef6df0de44c75b42ecadcfd694a85;i=549... OK
[2021/06/24 06:35:52] [ info] [input:storage_backlog:storage_backlog.3] queue memory limit: 7.6M
[2021/06/24 06:35:52] [ info] [input:storage_backlog:storage_backlog.3] register systemd.0/1-1624500531.557586764.flb
[2021/06/24 06:35:52] [ info] [input:storage_backlog:storage_backlog.3] register systemd.0/1-1624500536.409436599.flb
......
<snap> hundreds lines of register like above
......
[2021/06/24 06:35:52] [ info] [input:storage_backlog:storage_backlog.3] register tail.2/1-1624516245.13441862.flb
[2021/06/24 06:35:52] [ info] [filter:kubernetes:kubernetes_filter] https=1 host=kubernetes.aaa.bbb port=443
[2021/06/24 06:35:52] [ info] [filter:kubernetes:kubernetes_filter] local POD info OK
[2021/06/24 06:35:52] [ info] [filter:kubernetes:kubernetes_filter] testing connectivity with API server...
[2021/06/24 06:35:52] [ warn] [filter:kubernetes:kubernetes_filter] could not get meta for POD ip-n-n-n-n.ap-southeast-2.compute.internal
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter stream = '<snap>'"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter region = 'ap-southeast-2'"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter data_keys = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter partition_key = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter role_arn = '<snap>'"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter endpoint = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter sts_endpoint = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter append_newline = "
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter time_key = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter time_key_format = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter experimental_concurrency = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter experimental_concurrency_retries = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter log_key = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter aggregation = 'True'"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter compression = 'gzip'"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] plugin parameter replace_dots = ''"
time="2021-06-24T06:35:52Z" level=info msg="[kinesis 0] no partition key provided. A random one will be generated."
[2021/06/24 06:35:52] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2021/06/24 06:35:52] [ info] [sp] stream processor started
[2021/06/24 06:35:52] [ info] [input:tail:tail_kube_container_logs] inotify_fs_add(): inode=1573022 watch_fd=1 name=/var/log/containers/canal-node-zn96f_kube-system_calico-node-8ec31bb5a72369340bf57d3e1535f6580c10169049978537ef8692c75f68d4c6.log
...
<snap> A few lines similar as above
...
[2021/06/24 06:35:53] [engine] caught signal (SIGSEGV)
```

**Your Environment**

* Version used: 1.7.8
* Configuration:
fluent-bit is built with flags
```
    -DFLB_DEBUG=Off 
    -DFLB_TRACE=Off 
    -DFLB_JEMALLOC=On 
    -DFLB_TLS=On 
    -DFLB_SHARED_LIB=Off 
    -DFLB_EXAMPLES=Off 
    -DFLB_HTTP_SERVER=On 
    -DFLB_IN_SYSTEMD=On
```
* Environment name and version: kubernetes v1.19
* Server type and version: AWS EC2
* Operating System and version: Flatcar Linux 2765.2.5
* Filters and plugins:
 input: tail, systemd
 filter: lua, record_modifier, parser, kubernetes
 output: kinesis

**Additional context**

**Comment by hligit** [comment]
@patrickshan helped me tested fluent-bit v1.7.9 with a detailed backtrace.

```
(gdb) bt full
#0  0x00005555556eff72 in cb_modifier_filter (data=0x7fffca870aa2, bytes=107050,
    tag=0x7fffca438a40 "kube.var.log.containers.sn-root-pod-5db4b6d876-szhqm_ns_pod-0e607ea46e7e97b234ad074942f07d412a24acb16278f66dbecf894effba4926.log",
    tag_len=159, out_buf=0x7fffcb1fae08, out_size=0x7fffcb1fadf8, f_ins=0x7ffff706daa0, context=0x7fffca4f4fe0, config=0x7ffff7010680)
    at /src/fluent-bit/plugins/filter_record_modifier/filter_modifier.c:306
        ctx = 0x100000001
        is_modified = 1 '\001'
        off = 4294967297
        i = -1174095776
        removed_map_num = 144
        map_num = 1
        bool_map = {TO_BE_REMAINED <repeats 128 times>}
        tm = {tm = {tv_sec = 1625188504, tv_nsec = 566305429}}
        mod_rec = 0x100000001
        tmp_sbuf = {size = 0, data = 0x0, alloc = 0}
        tmp_pck = {data = 0x7fffcb1fab10, callback = 0x5555556ef260 <msgpack_sbuffer_write>}
        result = {zone = 0x7fffca458e28, data = {type = MSGPACK_OBJECT_ARRAY, via = {boolean = 2, u64 = 140733193388034, i64 = 140733193388034, f64 = 6.9531436082560066e-310, array = {size = 2,
                ptr = 0x7fffba036808}, map = {size = 2, ptr = 0x7fffba036808}, str = {size = 2, ptr = 0x7fffba036808 "\t"}, bin = {size = 2, ptr = 0x7fffba036808 "\t"}, ext = {type = 2 '\002',
                size = 32767, ptr = 0x7fffba036808 "\t"}}}}
        obj = 0x7fffba036820
        kv = 0x100000001
        tmp = 0x2
        head = 0x100000001
#1  0x000055555562d12a in flb_filter_do (ic=0x7fffca415500, data=0x7fffc7500280, bytes=65756,
    tag=0x7fffca43aa20 "kube.var.log.containers.sn-root-pod-5db4b6d876-szhqm_ns_pod-0e607ea46e7e97b234ad074942f07d412a24acb16278f66dbecf894effba4926.log",
    tag_len=159, config=0x7ffff7010680) at /src/fluent-bit/src/flb_filter.c:118
```

**Comment by hligit** [comment]
It's probably worth mentioning that the log triggering the crash is generated using [zap](https://github.com/uber-go/zap), and contains large number of duplicated key/value pairs in JSON. Related zap issue https://github.com/uber-go/zap/issues/622.
