### ISSUE TITLE
Loki Output, labels/label_keys Corrupts Memory

### ISSUE THREAD

**Issue by richardburakowski** [fluent/fluent-bit#3796]
## Bug Report

**Describe the bug**
Bulk loading log files into Loki, I've noticed some odd corruptions and I believe I've narrowed it down to label processing.
With the docker image loading will produce some small amount of corruption while built from source produces a SIGABRT.
Removing `labels` I don't see any errors.

**To Reproduce**
```
[INPUT]
    Name    Dummy
    Tag     dummy.log
    Dummy   {"job_name":"fluent-bit", "log":"some logged event body text"}
    Rate    1000
[OUTPUT]
    Name    loki
    Match   *
    Host    10.0.20.226
    labels  $job_name
```

```
Fluent Bit v1.8.1
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/07/19 23:13:04] [ info] [engine] started (pid=498067)
[2021/07/19 23:13:04] [ info] [storage] version=1.1.1, initializing...
[2021/07/19 23:13:04] [ info] [storage] in-memory
[2021/07/19 23:13:04] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/07/19 23:13:04] [ info] [cmetrics] version=0.1.1
[2021/07/19 23:13:04] [ info] [output:loki:loki.0] configured, hostname=10.0.20.226:3100
[2021/07/19 23:13:04] [ info] [sp] stream processor started
malloc(): mismatching next->prev_size (unsorted)
Aborted (core dumped)
```
**Your Environment**
* Version used: v1.8.1 from source.  Also reproduced in HEAD
* Operating System and version: Arch
* Filters and plugins: Loki

**Comment by edsiper** [comment]
@richardburakowski 

thanks for raising this issue. would you please provide details about compiler name and version ? I just tried locally but it didn't fail

**Comment by richardburakowski** [comment]
Is there a preferred build env I can try in a vm?
```
$ cmake --version
cmake version 3.21.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
```
$ cmake ../
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Found Journald: /usr/lib/libsystemd.so  
-- Found Monkey: /usr/local/include  
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/bin/bison (found version "3.7.6") 
-- Enabling FLB_REGEX since FLB_PARSER requires
```

**Comment by richardburakowski** [comment]
An example backtrace
```
#0  0x00007f2c0eb1fd22 in raise () from /usr/lib/libc.so.6
#1  0x00007f2c0eb09862 in abort () from /usr/lib/libc.so.6
#2  0x00007f2c0eb61d28 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f2c0eb6992a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f2c0eb6d09c in _int_malloc () from /usr/lib/libc.so.6
#5  0x00007f2c0eb6e4e1 in malloc () from /usr/lib/libc.so.6
#6  0x000055c027d2cf94 in msgpack_sbuffer_write (data=0x7f2c08010b90, buf=0x7f2c08010aa3 <incomplete sequence \337>, len=5) at /wrk/fluent-bit/lib/msgpack-c/include/msgpack/sbuffer.h:81
#7  0x000055c027d2cdb8 in msgpack_pack_map (x=0x7f2c08010b60, n=65536) at /wrk/fluent-bit/lib/msgpack-c/include/msgpack/pack_template.h:753
#8  0x000055c027d2d4dc in flb_mp_map_header_init (mh=0x7f2c08010b70, mp_pck=0x7f2c08010b60) at /wrk/fluent-bit/src/flb_mp.c:241
#9  0x000055c027d2dc35 in flb_mp_accessor_keys_remove (mpa=0x7f2c08007b60, map=0x7f2c08012ed0, out_buf=0x7f2c08010c00, out_size=0x7f2c08010c08) at /wrk/fluent-bit/src/flb_mp.c:474
#10 0x000055c027da348a in pack_record (ctx=0x7f2c08007720, mp_pck=0x7f2c08010d00, rec=0x7f2c08012ed0) at /wrk/fluent-bit/plugins/out_loki/loki.c:888
#11 0x000055c027da3ec5 in loki_compose_payload (ctx=0x7f2c08007720, tag=0x7f2c080081d0 "dummy.log", tag_len=9, data=0x7f2c0d7d0010, bytes=243198) at /wrk/fluent-bit/plugins/out_loki/loki.c:1143
#12 0x000055c027da3fb9 in cb_loki_flush (data=0x7f2c0d7d0010, bytes=243198, tag=0x7f2c080081d0 "dummy.log", tag_len=9, i_ins=0x55c028a3a8b0, out_context=0x7f2c08007720, config=0x55c028a28300) at /wrk/fluent-bit/plugins/out_loki/loki.c:1170
#13 0x000055c027cff462 in output_pre_cb_flush () at /wrk/fluent-bit/include/fluent-bit/flb_output.h:490
#14 0x000055c02802edc7 in co_init () at /wrk/fluent-bit/lib/monkey/deps/flb_libco/amd64.c:117
#15 0x0000000000000000 in ?? ()
```

**Comment by richardburakowski** [comment]
```
==133464== Invalid read of size 1
==133464==    at 0x2165BA: pack_label_key (loki.c:281)
==133464==    by 0x2167EF: pack_labels (loki.c:324)
==133464==    by 0x218E49: loki_compose_payload (loki.c:1132)
==133464==    by 0x218FB8: cb_loki_flush (loki.c:1170)
==133464==    by 0x174461: output_pre_cb_flush (flb_output.h:490)
==133464==    by 0x4A3DC6: co_init (amd64.c:117)
==133464==    by 0x67F7CF76000D791: ???
==133464==    by 0x626F6AA882BAEE37: ???
==133464==  Address 0x6ceacba is 8,186 bytes inside a block of size 8,192 free'd
==133464==    at 0x484383F: realloc (vg_replace_malloc.c:1192)
==133464==    by 0x215890: msgpack_sbuffer_write (sbuffer.h:81)
==133464==    by 0x2156A9: msgpack_pack_str_body (pack_template.h:784)
==133464==    by 0x21659B: pack_label_key (loki.c:278)
==133464==    by 0x2167EF: pack_labels (loki.c:324)
==133464==    by 0x218E49: loki_compose_payload (loki.c:1132)
==133464==    by 0x218FB8: cb_loki_flush (loki.c:1170)
==133464==    by 0x174461: output_pre_cb_flush (flb_output.h:490)
==133464==    by 0x4A3DC6: co_init (amd64.c:117)
==133464==    by 0x67F7CF76000D791: ???
==133464==    by 0x626F6AA882BAEE37: ???
==133464==  Block was alloc'd at
==133464==    at 0x483E6D5: malloc (vg_replace_malloc.c:379)
==133464==    by 0x215890: msgpack_sbuffer_write (sbuffer.h:81)
==133464==    by 0x2154AB: msgpack_pack_map (pack_template.h:745)
==133464==    by 0x218C17: loki_compose_payload (loki.c:1070)
==133464==    by 0x218FB8: cb_loki_flush (loki.c:1170)
==133464==    by 0x174461: output_pre_cb_flush (flb_output.h:490)
==133464==    by 0x4A3DC6: co_init (amd64.c:117)
==133464==    by 0x67F7CF76000D791: ???
==133464==    by 0x626F6AA882BAEE37: ???
```
fwiw, seems to run indefinitely under valgrind.

**Comment by nokute78** [comment]
Note: similar issue is #3279
