### ISSUE TITLE
Multiline support for csv logs

### ISSUE THREAD

**Issue by kishaningithub** [fluent/fluent-bit#3827]
The logs that we read is of the csv format. Eg

```csv
1617104831727,"","processId2",20,"taskId2",234
1617104831727,"java.lang.RuntimeException: Something has gone wrong, aborting!
                   at com.myproject.module.MyProject.badMethod(MyProject.java:22)
                   at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
                   at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
                   at com.myproject.module.MyProject.someMethod(MyProject.java:10)
                   at com.myproject.module.MyProject.main(MyProject.java:6)","processId2",20,"taskId2",234
1617104831727,,"processId2",20,"taskId2",234
```

If you observe above we have a single csv record which spans across multiple lines

If we can add "csv" to the [list of existing parsers](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing) it would be a hugle value add in my opinion

### Alternatives

Alternatives are to use a custom regex (haven't yet arrived at a regex which can match a multiline csv record)

**Comment by kishaningithub** [comment]
notstale

**Comment by kishaningithub** [comment]
Notstale

**Comment by kishaningithub** [comment]
Notstale

**Comment by kishaningithub** [comment]
Notstale

**Comment by kishaningithub** [comment]
Not stale
