### ISSUE TITLE
New Multiline Parser does not work with more than one multiline log in v1.8.2

### ISSUE THREAD

**Issue by arpantw** [fluent/fluent-bit#3840]
## Bug Report

Multiline parsing does not work as expected in fluent-bit v1.8.2 with multiline core.
It only parsed first multiline correctly as shown in documentation, but if there are more logs it is not working as expected.

**Steps to reproduce the problem**
- Setup configuration as per https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#configuration-example
- Change test.log to have more multiline logs as shown:
```
single line...
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
another line...`
single line...
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
another line...
```

**Expected behavior**
```
[[0] tail.0: [0.000000000, {"log"=>"single line...
"}]
[1] tail.0: [1626634867.472226330, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
"}]
[2] tail.0: [1626634867.472226330, {"log"=>"another line...
"}]
[3] tail.0: [0.000000000, {"log"=>"single line...
"}]
[4] tail.0: [1626634867.472226330, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
"}]
[5] tail.0: [1626634867.472226330, {"log"=>"another line...
"}]
```
**Current behavior**
```
[0] tail.0: [0.0000000000, {"log"=>"single line...
                                           "}]
[1] tail.0: [0.000000000, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
                                                        at com.myproject.module.MyProject.badMethod(MyProject.java:22)
                                                        at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
                                                        at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
                                                        at com.myproject.module.MyProject.someMethod(MyProject.java:10)
                                                        at com.myproject.module.MyProject.main(MyProject.java:6)
                                                    "}]
[2] tail.0: [0.000000000, {"log"=>"another line...
                                                    "}]
[3] tail.0: [0.000000000, {"log"=>"single line...
                                                    "}]
[4] tail.0: [0.000000000, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
                                                    "}]
[5] tail.0: [0.000000000, {"log"=>"    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
                                                        at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
                                                        at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
                                                        at com.myproject.module.MyProject.someMethod(MyProject.java:10)
                                                        at com.myproject.module.MyProject.main(MyProject.java:6)
                                                    "}]
[6] tail.0: [0.000000000, {"log"=>"another line...
                                                    "}]
```
As we can see the first multiline log was parsed properly, but the next multiline log was broken into two.

* Version used: v1.8.2
* Plugins: Tail plugin

**Comment by psyhomb** [comment]
Thanks for opening this issue, I'm experiencing exactly the same problem.

**Comment by edsiper** [comment]
thanks for raising this isssue. 

We are working in the fixed. I will make sure to integrate these test examples in the CI

**Comment by edsiper** [comment]
FYI: upcoming solution on PR #3843

**Comment by psyhomb** [comment]
I have built and tested the latest version 1.9.0 (multiline-2 branch) of fluent-bit and I can confirm that this bug is fixed in this version. 🎉 
When we can expect an official release of the version 1.9.0?

Thank you

**Comment by itshikanov** [comment]
> I have built and tested the latest version 1.9.0 (multiline-2 branch) of fluent-bit and I can confirm that this bug is fixed in this version. tada
> @edsiper when we can expect an official release of version 1.9.0?
> 
> Thank you

I'm check multiline-2 and master branch, build from source. The Problem exist. 
I'm get some result like here:
https://github.com/fluent/fluent-bit/issues/3901#issuecomment-904671242

**Comment by kishaningithub** [comment]
Notstale
