### ISSUE TITLE
chunk '1-1628064536.33654680.flb' cannot be retried: task_id=0, input=tail.0 > output=es.0

### ISSUE THREAD

**Issue by joenzx** [fluent/fluent-bit#3910]
## Bug Report

**Describe the bug**
The collected data cannot be output in ES.
The following warning appears for container logs
[ warn] [engine] chunk '1-1628064536.33654680.flb' cannot be retried: task_id=0, input=tail.0 > output=es.0

**To Reproduce**
jerr.log
```
2021-08-02 18:27:14.847 Exception in thread "dev" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
```
- Steps to reproduce the problem:
fluent-bit.conf
[SERVICE]
flush 1
log_level debug
parsers_file /fluent-bit/etc/parsers_multiline.conf

[INPUT]
name tail
path /fluent-bit/log/jerr.log
read_from_head true
multiline.parser multiline-regex-test
[OUTPUT]
name                 es
Match                *
Host                   ...
Port                   9200
Buffer_Size        20MB
Index                 j-dev-id
Type                  _doc
http_user          user
http_passwd     pwd

parsers_multiline.conf
[MULTILINE_PARSER]
        name          multiline-regex
        type            regex
        flush_timeout 1000
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules   |   state name   | regex pattern                   | next state name
        # --------|----------------|--------------------------------------------------
        rule         "start_state"   "/(\d+-\d+-\d+\s\d+:\d+:\d+\.\d+)(.*)/"  "cont"
        rule         "cont"          "/^(?!\d+-\d+-\d+\s\d+:\d+:\d+\.\d+)/"   "cont"

**Your Environment**
fluent-bit :  1.8.3
docker-v:   20.10.7

**Additional context**
Each time the container is run, the collected log cannot be output to ES.

**Comment by joenzx** [comment]
The problem of es
