### ISSUE TITLE
Segfault on file transition in je_large_dalloc() called from flb_tail_file_remove()

### ISSUE THREAD

**Issue by jiscfoo** [fluent/fluent-bit#4137]
## Bug Report

**Describe the bug**
When a specific input file (not happy to make this public as it contains private data) rotates, the next file causes a segfault 

**To Reproduce**
1. Ingest logfile
2. Cycle logfile to logfile2 (cp logfile2 logfile)

logfile is handled as a multiline file with custom parser and pos stored

Running under `gdb`:
```
[2021/09/29 10:39:04] [debug] [input:tail:tail.0] inode=3468209 file=/local/shibd.log promote to TAIL_EVENT
[2021/09/29 10:39:04] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3468209 watch_fd=1 name=/local/shibd.log
[2021/09/29 10:39:08] [debug] [task] created task=0x7f77f3637a00 id=0 OK
[2021/09/29 10:39:08] [debug] [out coro] cb_destroy coro_id=0
[2021/09/29 10:39:08] [debug] [task] destroy task=0x7f77f3637a00 (task_id=0)
[2021/09/29 10:39:11] [debug] [input chunk] skip ingesting data with 0 bytes
[2021/09/29 10:39:15] [debug] [input chunk] skip ingesting data with 0 bytes
[2021/09/29 10:39:16] [debug] [input:tail:tail.0] inode=3468209 events: IN_ATTRIB
[2021/09/29 10:39:16] [debug] [input:tail:tail.0] inode=3468209 file has been deleted: /local/shibd.log
[2021/09/29 10:39:16] [debug] [input:tail:tail.0] db: file deleted from database: /local/shibd.log
[2021/09/29 10:39:16] [debug] [input:tail:tail.0] inode=3468209 removing file name /local/shibd.log

Thread 2 "flb-pipeline" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f77f43ff700 (LWP 22)]
je_large_dalloc (tsdn=tsdn@entry=0x7f77f43f54a0, extent=0x0)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/src/large.c:361
361	/tmp/fluent-bit/lib/jemalloc-5.2.1/src/large.c: No such file or directory.
```

**Expected behavior**
Normally this cycling works fine but for this pair of files it segfaults.

It does not segfault if I concatenate the two files together and ingest that instead.

**Screenshots**
full backtrace
```
#0  je_large_dalloc (tsdn=tsdn@entry=0x7f77f43f54a0, extent=0x0)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/src/large.c:361
#1  0x0000564ec131bfcd in arena_dalloc_large (slow_path=<optimized out>,
    szind=<optimized out>, tcache=<optimized out>, ptr=<optimized out>,
    tsdn=<optimized out>)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:281
#2  arena_dalloc (slow_path=<optimized out>, alloc_ctx=<optimized out>,
    tcache=<optimized out>, ptr=<optimized out>, tsdn=<optimized out>)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:323
#3  idalloctm (slow_path=<optimized out>, is_internal=<optimized out>,
    alloc_ctx=<optimized out>, tcache=<optimized out>, ptr=<optimized out>,
    tsdn=<optimized out>)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#4  ifree (slow_path=<optimized out>, tcache=<optimized out>,
    ptr=<optimized out>, tsd=<optimized out>)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/src/jemalloc.c:2589
#5  je_free_default (ptr=<optimized out>)
    at /tmp/fluent-bit/lib/jemalloc-5.2.1/src/jemalloc.c:2799
#6  0x0000564ec13f3ad0 in msgpack_sbuffer_destroy (sbuf=0x7f77f362e388)
    at /tmp/fluent-bit/lib/msgpack-c/include/msgpack/sbuffer.h:41
#7  0x0000564ec13f6b0e in flb_tail_file_remove (file=0x7f77f362e300)
    at /tmp/fluent-bit/plugins/in_tail/tail_file.c:1024
#8  0x0000564ec13f0988 in tail_fs_event (ins=0x7f77f4849440,
    config=0x7f77f4832e00, in_context=0x7f77f3656000)
    at /tmp/fluent-bit/plugins/in_tail/tail_fs_inotify.c:234
#9  0x0000564ec1398be5 in flb_input_collector_fd (fd=26, config=0x7f77f4832e00)
    at /tmp/fluent-bit/src/flb_input.c:1107
#10 0x0000564ec13ab284 in flb_engine_handle_event (config=0x7f77f4832e00,
    mask=1, fd=26) at /tmp/fluent-bit/src/flb_engine.c:411
#11 flb_engine_start (config=0x7f77f4832e00)
    at /tmp/fluent-bit/src/flb_engine.c:686
#12 0x0000564ec138d7ff in flb_lib_worker (data=0x7f77f480b340)
    at /tmp/fluent-bit/src/flb_lib.c:627
#13 0x00007f77f62f1fa3 in start_thread (arg=<optimized out>)
    at pthread_create.c:486
#14 0x00007f77f59d24cf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Your Environment**
* Version used: 1.8.7
* Configuration: Built custom docker container using `Dockerfile.x86_64-master_debug` against the v1.8.7 tag
* Environment name and version: Docker version 20.10.7 on macos 
* Server type and version: macos 11.5.2
* Operating System and version: macos 11.5.2
* Filters and plugins:

```
[SERVICE]
    Parsers_File local-parsers.conf
    log_level trace

[PARSER] # in local-parsers.conf
	Name   shib-sp-shibd
	Format regex
	Regex ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?<priority>\S+) (?<component>\S+) \[(?<thread>\d+)\] \[(?<tag>[^\]]+)\]: (?<message>.*)
	Time_Key time
	Time_Format %F %T

[INPUT]
    Name                tail
    Path                /local/shibd.log
    DB                  /state/pos.db
    Multiline           on
    Parser_Firstline    shib-sp-shibd
    Path_Key            source
    Tag                 shib-sp.*
    Skip_empty_lines    true
    Read_from_Head true

[OUTPUT]
    Name file
    Match shib-sp.**
    path /out
```

Possibly relevant:
```
(gdb) frame 6
#6  0x0000564ec13f3ad0 in msgpack_sbuffer_destroy (sbuf=0x7f77f362e388)
    at /tmp/fluent-bit/lib/msgpack-c/include/msgpack/sbuffer.h:41
41	/tmp/fluent-bit/lib/msgpack-c/include/msgpack/sbuffer.h: No such file or directory.
```
```c
// sbuffer.h 39-42
static inline void msgpack_sbuffer_destroy(msgpack_sbuffer* sbuf)
{
    free(sbuf->data);
}
```

```
(gdb) print *sbuf
$1 = {size = 11223,
  data = 0x7f77f3778ac0 "\206\247message\332+Vdecoded SAML message:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\" Destination=\"https://test.ukfederation.org.uk/Shibboleth.ss"..., alloc = 14592}
```

**Comment by jiscfoo** [comment]
Running under valgrind rather than gdb shows this while ingesting the first file:
```
[2021/09/29 11:09:53] [debug] [input:tail:tail.0] inode=3468173 file=/local/shibd.log promote to TAIL_EVENT
[2021/09/29 11:09:53] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3468173 watch_fd=1 name=/local/shibd.log
==1== Warning: client switching stacks?  SP change: 0x71f5648 --> 0x820a280
==1==          to suppress, use: --max-stackframe=16862264 or greater
==1== Warning: client switching stacks?  SP change: 0x820a1f8 --> 0x71f5648
==1==          to suppress, use: --max-stackframe=16862128 or greater
==1== Warning: client switching stacks?  SP change: 0x71f5648 --> 0x820a1f8
==1==          to suppress, use: --max-stackframe=16862128 or greater
==1==          further instances of this message will not be shown.
[2021/09/29 11:09:53] [debug] [task] created task=0x5e43c80 id=0 OK
[2021/09/29 11:09:54] [debug] [out coro] cb_destroy coro_id=0
[2021/09/29 11:09:54] [debug] [task] destroy task=0x5e43c80 (task_id=0)
```

Then, when the file cycles:
```
[2021/09/29 11:10:11] [debug] [input:tail:tail.0] inode=3468173 events: IN_ATTRIB
[2021/09/29 11:10:11] [debug] [input:tail:tail.0] inode=3468173 file has been deleted: /local/shibd.log
[2021/09/29 11:10:11] [debug] [input:tail:tail.0] db: file deleted from database: /local/shibd.log
[2021/09/29 11:10:11] [debug] [input:tail:tail.0] inode=3468173 removing file name /local/shibd.log
==1== Thread 2 flb-pipeline:
==1== Invalid free() / delete / delete[] / realloc()
==1==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1==    by 0x278ACF: msgpack_sbuffer_destroy (sbuffer.h:41)
==1==    by 0x27BB0D: flb_tail_file_remove (tail_file.c:1024)
==1==    by 0x275987: tail_fs_event (tail_fs_inotify.c:234)
==1==    by 0x21DBE4: flb_input_collector_fd (flb_input.c:1107)
==1==    by 0x230283: flb_engine_handle_event (flb_engine.c:411)
==1==    by 0x230283: flb_engine_start (flb_engine.c:686)
==1==    by 0x2127FE: flb_lib_worker (flb_lib.c:627)
==1==    by 0x484FFA2: start_thread (pthread_create.c:486)
==1==    by 0x51B44CE: clone (clone.S:95)
==1==  Address 0x8a74fa0 is 0 bytes inside a block of size 14,592 free'd
==1==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1==    by 0x276E85: msgpack_sbuffer_destroy (sbuffer.h:41)
==1==    by 0x27825F: flb_tail_mult_flush (tail_multiline.c:491)
==1==    by 0x27830E: file_pending_flush (tail_multiline.c:516)
==1==    by 0x2784EF: flb_tail_mult_pending_flush (tail_multiline.c:568)
==1==    by 0x21DBE4: flb_input_collector_fd (flb_input.c:1107)
==1==    by 0x230283: flb_engine_handle_event (flb_engine.c:411)
==1==    by 0x230283: flb_engine_start (flb_engine.c:686)
==1==    by 0x2127FE: flb_lib_worker (flb_lib.c:627)
==1==    by 0x484FFA2: start_thread (pthread_create.c:486)
==1==    by 0x51B44CE: clone (clone.S:95)
==1==  Block was alloc'd at
==1==    at 0x4837D7B: realloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1==    by 0x276F82: msgpack_sbuffer_write (sbuffer.h:81)
==1==    by 0x276DA4: msgpack_pack_str_body (pack_template.h:784)
==1==    by 0x277952: flb_tail_mult_append_raw (tail_multiline.c:238)
==1==    by 0x277C4B: flb_tail_mult_process_content (tail_multiline.c:348)
==1==    by 0x27A140: process_content (tail_file.c:428)
==1==    by 0x27C3EC: flb_tail_file_chunk (tail_file.c:1197)
==1==    by 0x274489: in_tail_collect_static (tail.c:140)
==1==    by 0x21DBE4: flb_input_collector_fd (flb_input.c:1107)
==1==    by 0x230283: flb_engine_handle_event (flb_engine.c:411)
==1==    by 0x230283: flb_engine_start (flb_engine.c:686)
==1==    by 0x2127FE: flb_lib_worker (flb_lib.c:627)
==1==    by 0x484FFA2: start_thread (pthread_create.c:486)
==1==
[2021/09/29 11:10:11] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=3468173 watch_fd=1
[2021/09/29 11:10:48] [debug] [input:tail:tail.0] scanning path /local/shibd.log
[2021/09/29 11:10:48] [debug] [input:tail:tail.0] inode=3468174 with offset=0 appended as /local/shibd.log
[2021/09/29 11:10:48] [debug] [input:tail:tail.0] scan_glob add(): /local/shibd.log, inode 3468174
[2021/09/29 11:10:48] [debug] [input:tail:tail.0] 1 new files found on path '/local/shibd.log'
[2021/09/29 11:10:52] [debug] [input:tail:tail.0] inode=3468174 file=/local/shibd.log promote to TAIL_EVENT
[2021/09/29 11:10:52] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3468174 watch_fd=2 name=/local/shibd.log
```

**Comment by jiscfoo** [comment]
Apologies… my test case didn't quite simulate file rotation correctly, although the stack trace is similar…! This test does:

```bash
mv shibd.log shibd.log.1 ; cp newlog shibd.log
```

Output:
```
fluent-bit_1  | [2021/09/29 11:43:15] [debug] [input:tail:tail.0] inode=3468116 events: IN_MOVE_SELF
fluent-bit_1  | [2021/09/29 11:43:15] [debug] [input:tail:tail.0] inode=3468116 rotated IN_MOVE SELF '/local/shibd.log'
fluent-bit_1  | [2021/09/29 11:43:15] [debug] [input:tail:tail.0] inode=3468116 rotated /local/shibd.log -> /local/shibd.log.1
fluent-bit_1  | [2021/09/29 11:43:15] [ info] [input:tail:tail.0] inode=3468116 handle rotation(): /local/shibd.log => /local/shibd.log.1
fluent-bit_1  | [2021/09/29 11:43:15] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=3468116 watch_fd=1
fluent-bit_1  | [2021/09/29 11:43:15] [ info] [input:tail:tail.0] inotify_fs_add(): inode=3468116 watch_fd=2 name=/local/shibd.log.1
fluent-bit_1  | [2021/09/29 11:43:17] [debug] [input chunk] skip ingesting data with 0 bytes
fluent-bit_1  | [2021/09/29 11:43:20] [debug] [input:tail:tail.0] inode=3468116 purge rotated file /local/shibd.log.1 (offset=1001148 / size = 1001148)
fluent-bit_1  | [2021/09/29 11:43:20] [debug] [input:tail:tail.0] inode=3468116 removing file name /local/shibd.log.1
fluent-bit_1  | [2021/09/29 11:43:20] [debug] [input:tail:tail.0] db: file deleted from database: /local/shibd.log.1
fluent-bit_1  | [2021/09/29 11:43:20] [engine] caught signal (SIGSEGV)
fluent-bit_1  | #0  0x55ac96d3f1c2      in  atomic_load_p() at lib/jemalloc-5.2.1/include/jemalloc/internal/atomic.h:62
fluent-bit_1  | #1  0x55ac96d3f1c2      in  extent_arena_get() at lib/jemalloc-5.2.1/include/jemalloc/internal/extent_inlines.h:51
fluent-bit_1  | #2  0x55ac96d3f1c2      in  je_large_dalloc() at lib/jemalloc-5.2.1/src/large.c:361
fluent-bit_1  | #3  0x55ac96d00fcc      in  arena_dalloc_large() at lib/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:281
fluent-bit_1  | #4  0x55ac96d00fcc      in  arena_dalloc() at lib/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:323
fluent-bit_1  | #5  0x55ac96d00fcc      in  idalloctm() at lib/jemalloc-5.2.1/include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
fluent-bit_1  | #6  0x55ac96d00fcc      in  ifree() at lib/jemalloc-5.2.1/src/jemalloc.c:2589
fluent-bit_1  | #7  0x55ac96d00fcc      in  je_free_default() at lib/jemalloc-5.2.1/src/jemalloc.c:2799
fluent-bit_1  | #8  0x55ac96dd8acf      in  msgpack_sbuffer_destroy() at lib/msgpack-c/include/msgpack/sbuffer.h:41
fluent-bit_1  | #9  0x55ac96ddbb0d      in  flb_tail_file_remove() at plugins/in_tail/tail_file.c:1024
fluent-bit_1  | #10 0x55ac96ddd7ac      in  flb_tail_file_purge() at plugins/in_tail/tail_file.c:1616
fluent-bit_1  | #11 0x55ac96d7dbe4      in  flb_input_collector_fd() at src/flb_input.c:1107
fluent-bit_1  | #12 0x55ac96d90283      in  flb_engine_handle_event() at src/flb_engine.c:411
fluent-bit_1  | #13 0x55ac96d90283      in  flb_engine_start() at src/flb_engine.c:686
fluent-bit_1  | #14 0x55ac96d727fe      in  flb_lib_worker() at src/flb_lib.c:627
fluent-bit_1  | #15 0x7ff359e43fa2      in  start_thread() at 4T1/glibc-2.28/nptl/pthread_create.c:486
fluent-bit_1  | #16 0x7ff3595244ce      in  ???() at sysv/linux/x86_64/clone.S:95
fluent-bit_1  | #17 0xffffffffffffffff  in  ???() at ???:0
```

**Comment by edsiper** [comment]
@jiscfoo 

is it possible you could share your log files that trigger this issue ? I suspect there is corruption around the content of the file and the parser being applied. If you cannot make the content of the files public I am happy to receive them privately for troubleshooting

**Comment by jiscfoo** [comment]
@edsiper I'm trying to get authorisation to release a redacted set of log files (which still trigger the segfault). They're 1M each. What's the best way to get these over to you? (I've left you a note on Slack)
