### ISSUE TITLE
Frequent crash when multiline on and file rotation

### ISSUE THREAD

**Issue by wubn2000** [fluent/fluent-bit#4177]
## Bug Report

**Describe the bug**

When turn on the multiline parser, ( the one I used is 
[PARSER]
    Name    multiline_stats
    Format  regex
    Regex   /^(?<key>\d{10,}.*)/
), if monitoring on a rotate log file, it always crashed around the rotation, with info like:

*** Error in `./fluent-bit': double free or corruption (out): 0x00007f66c2f65e80 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f66fea7e329]
./fluent-bit[0x4b73ea]
./fluent-bit(flb_tail_file_remove+0x13e)[0x4ba469]
./fluent-bit(flb_tail_file_purge+0x293)[0x4bc068]
./fluent-bit(flb_input_collector_fd+0x3b2)[0x4614bd]
./fluent-bit(flb_engine_start+0x707)[0x472660]  
./fluent-bit[0x456cf5]
 
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
Note here is one message, with the last field as a multiline field:

1633801021538,"customer2788",13,2788,1623239523,"java.lang.RuntimeException: Something has gone wrong, aborting! 
 at com.myproject.module.MyProject.badMethod(MyProject.java:22) 
 at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18) 
  at com.myproject.module.MyProject.anotherMethod(MyProject.java:14) 
 at com.myproject.module.MyProject.someMethod(MyProject.java:10) 
 at com.myproject.module.MyProject.main(MyProject.java:6)","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim ven."
- Steps to reproduce the problem:

keep appending this message to a file, when the size reaches a threshold (can be 500k), do file rotation by cleaning the file to be empty and keep appending the message again. With a few times, It always crashed.
 
**Expected behavior**

The fluentbit should not crash.

**Screenshots**

**Your Environment**

* Version used: 1.8.8
* Configuration: 
* [INPUT]
    Name              tail
    Path              /data/test/stats-0.csv
    Path_Key          file_name
    Tag               stats
    Buffer_Chunk_Size 32KB
    Buffer_Max_Size   128KB
    Skip_Long_Lines   On
    Multiline         On
    Parser_Firstline  multiline_stats
    Multiline_Flush   5
    Rotate_Wait               35
    Refresh_Interval 1
    Read_from_head    true
    Mem_Buf_Limit     500MB
    storage.type      filesystem
    DB                /data/tail-0.db
    DB.locking        true
[SERVICE]
    Flush     1
    Daemon    off
    Log_Level info
    Parsers_File parser.example.conf
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_PORT                 2020
    storage.path              /data/storage
    storage.backlog.mem_limit 500M
    storage.max_chunks_up     200

@INCLUDE inputs.example.conf

[OUTPUT]
    Name            stdout

* Environment name and version (e.g. Kubernetes? What version?): ec2 machine
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by wubn2000** [comment]
Thanks Wesley, just opened one there.

**Comment by PettitWesley** [comment]
Valgrind logs for crash: https://github.com/aws/aws-for-fluent-bit/issues/255#issuecomment-940552520
