### ISSUE TITLE
multiline parser not works

### ISSUE THREAD

**Issue by lichuan6** [fluent/fluent-bit#4384]
## Bug Report

**Describe the bug**
Hi, I'm trying [multiline parser](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing) with the following config to parse logs, which contain normal logs(json format), go panic logs and java exceptions, but the logs seem not parsed correctly.

`fluent-bit.conf`:

```conf
[SERVICE]
    flush                 1
    log_level             debug
    # parsers_file          parsers_multiline.conf

[INPUT]
    name                  tail
    path                   test.log
    read_from_head        true

[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      docker,cri,go,java
#    multiline.parser      docker,go, java
#    multiline.parser      docker, go, multiline-regex-test
#    multiline.parser      go, multiline-regex-test

[OUTPUT]
    name                  stdout
    match                 *

```

`test.log`:

```
{"log":"W1130 16:47:23.125742       1 metadata.go:191] Failed to parse the outpost arn: \n","stream":"stderr","time":"2021-11-30T16:47:23.126093742Z"}
single line...
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
another line...
panic: my panic

goroutine 4 [running]:
panic(0x45cb40, 0x47ad70)
  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
main.main.func1(0xc420024120)
  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
created by main.main
  foo.go:5 +0x58

goroutine 1 [chan receive]:
runtime.gopark(0x4739b8, 0xc420024178, 0x46fcd7, 0xc, 0xc420028e17, 0x3)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc420053e30 sp=0xc420053e00 pc=0x42503c
runtime.goparkunlock(0xc420024178, 0x46fcd7, 0xc, 0x1000f010040c217, 0x3)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc420053e70 sp=0xc420053e30 pc=0x42512e
runtime.chanrecv(0xc420024120, 0x0, 0xc420053f01, 0x4512d8)
  /usr/local/go/src/runtime/chan.go:506 +0x304 fp=0xc420053f20 sp=0xc420053e70 pc=0x4046b4
runtime.chanrecv1(0xc420024120, 0x0)
  /usr/local/go/src/runtime/chan.go:388 +0x2b fp=0xc420053f50 sp=0xc420053f20 pc=0x40439b
main.main()
  foo.go:9 +0x6f fp=0xc420053f80 sp=0xc420053f50 pc=0x4512ef
runtime.main()
  /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc420053fe0 sp=0xc420053f80 pc=0x424bad
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420053fe8 sp=0xc420053fe0 pc=0x44b4d1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4739b8, 0x4ad720, 0x47001e, 0xf, 0x14, 0x1)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003e768 sp=0xc42003e738 pc=0x42503c
runtime.goparkunlock(0x4ad720, 0x47001e, 0xf, 0xc420000114, 0x1)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003e7a8 sp=0xc42003e768 pc=0x42512e
runtime.forcegchelper()
  /usr/local/go/src/runtime/proc.go:238 +0xcc fp=0xc42003e7e0 sp=0xc42003e7a8 pc=0x424e5c
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003e7e8 sp=0xc42003e7e0 pc=0x44b4d1
created by runtime.init.4
  /usr/local/go/src/runtime/proc.go:227 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4739b8, 0x4ad7e0, 0x46fdd2, 0xd, 0x419914, 0x1)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003ef60 sp=0xc42003ef30 pc=0x42503c
runtime.goparkunlock(0x4ad7e0, 0x46fdd2, 0xd, 0x14, 0x1)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003efa0 sp=0xc42003ef60 pc=0x42512e
runtime.bgsweep(0xc42001e150)
  /usr/local/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42003efd8 sp=0xc42003efa0 pc=0x419973
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003efe0 sp=0xc42003efd8 pc=0x44b4d1
created by runtime.gcenable
  /usr/local/go/src/runtime/mgc.go:216 +0x58
one more line, no multiline
```

**To Reproduce**

```
~/fluent-bit-1.8.10/build/bin/fluent-bit -c fluent-bit.conf
Fluent Bit v1.8.10
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/02 04:06:55] [ info] Configuration:
[2021/12/02 04:06:55] [ info]  flush time     | 1.000000 seconds
[2021/12/02 04:06:55] [ info]  grace          | 5 seconds
[2021/12/02 04:06:55] [ info]  daemon         | 0
[2021/12/02 04:06:55] [ info] ___________
[2021/12/02 04:06:55] [ info]  inputs:
[2021/12/02 04:06:55] [ info]      tail
[2021/12/02 04:06:55] [ info] ___________
[2021/12/02 04:06:55] [ info]  filters:
[2021/12/02 04:06:55] [ info]      multiline.0
[2021/12/02 04:06:55] [ info] ___________
[2021/12/02 04:06:55] [ info]  outputs:
[2021/12/02 04:06:55] [ info]      stdout.0
[2021/12/02 04:06:55] [ info] ___________
[2021/12/02 04:06:55] [ info]  collectors:
[2021/12/02 04:06:55] [ info] [engine] started (pid=29850)
[2021/12/02 04:06:55] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/12/02 04:06:55] [debug] [storage] [cio stream] new stream registered: tail.0
[2021/12/02 04:06:55] [ info] [storage] version=1.1.5, initializing...
[2021/12/02 04:06:55] [ info] [storage] in-memory
[2021/12/02 04:06:55] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/02 04:06:55] [ info] [cmetrics] version=0.2.2
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] inotify watch fd=23
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] scanning path test.log
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] inode=136321366 with offset=0 appended as test.log
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] scan_glob add(): test.log, inode 136321366
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] 1 new files found on path 'test.log'
[2021/12/02 04:06:55] [debug] [stdout:stdout.0] created event channels: read=25 write=26
[2021/12/02 04:06:55] [debug] [router] match rule tail.0:stdout.0
[2021/12/02 04:06:55] [ info] [sp] stream processor started
[2021/12/02 04:06:55] [debug] [input:tail:tail.0] inode=136321366 file=test.log promote to TAIL_EVENT
[2021/12/02 04:06:55] [ info] [input:tail:tail.0] inotify_fs_add(): inode=136321366 watch_fd=1 name=test.log
[2021/12/02 04:06:56] [debug] [task] created task=0x7f362801ad50 id=0 OK
[0] tail.0: [1638389215.477762484, {"log"=>"{"log":"W1130 16:47:23.125742       1 metadata.go:191] Failed to parse the outpost arn: \n","stream":"stderr","time":"2021-11-30T16:47:23.126093742Z"}single line...Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!    at com.myproject.module.MyProject.badMethod(MyProject.java:22)    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)    at com.myproject.module.MyProject.someMethod(MyProject.java:10)    at com.myproject.module.MyProject.main(MyProject.java:6)another line...panic: my panicgoroutine 4 [running]:panic(0x45cb40, 0x47ad70)  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7cmain.main.func1(0xc420024120)  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339runtime.goexit()  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1created by main.main  foo.go:5 +0x58"}]
[1] tail.0: [1638389215.477849245, {"log"=>"goroutine 1 [chan receive]:runtime.gopark(0x4739b8, 0xc420024178, 0x46fcd7, 0xc, 0xc420028e17, 0x3)  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc420053e30 sp=0xc420053e00 pc=0x42503cruntime.goparkunlock(0xc420024178, 0x46fcd7, 0xc, 0x1000f010040c217, 0x3)  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc420053e70 sp=0xc420053e30 pc=0x42512eruntime.chanrecv(0xc420024120, 0x0, 0xc420053f01, 0x4512d8)  /usr/local/go/src/runtime/chan.go:506 +0x304 fp=0xc420053f20 sp=0xc420053e70 pc=0x4046b4runtime.chanrecv1(0xc420024120, 0x0)  /usr/local/go/src/runtime/chan.go:388 +0x2b fp=0xc420053f50 sp=0xc420053f20 pc=0x40439bmain.main()  foo.go:9 +0x6f fp=0xc420053f80 sp=0xc420053f50 pc=0x4512efruntime.main()  /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc420053fe0 sp=0xc420053f80 pc=0x424badruntime.goexit()  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420053fe8 sp=0xc420053fe0 pc=0x44b4d1"}]
[2] tail.0: [1638389215.477855405, {"log"=>"goroutine 2 [force gc (idle)]:runtime.gopark(0x4739b8, 0x4ad720, 0x47001e, 0xf, 0x14, 0x1)  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003e768 sp=0xc42003e738 pc=0x42503cruntime.goparkunlock(0x4ad720, 0x47001e, 0xf, 0xc420000114, 0x1)  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003e7a8 sp=0xc42003e768 pc=0x42512eruntime.forcegchelper()  /usr/local/go/src/runtime/proc.go:238 +0xcc fp=0xc42003e7e0 sp=0xc42003e7a8 pc=0x424e5cruntime.goexit()  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003e7e8 sp=0xc42003e7e0 pc=0x44b4d1created by runtime.init.4  /usr/local/go/src/runtime/proc.go:227 +0x35"}]
[3] tail.0: [1638389215.477859795, {"log"=>"goroutine 3 [GC sweep wait]:runtime.gopark(0x4739b8, 0x4ad7e0, 0x46fdd2, 0xd, 0x419914, 0x1)  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003ef60 sp=0xc42003ef30 pc=0x42503cruntime.goparkunlock(0x4ad7e0, 0x46fdd2, 0xd, 0x14, 0x1)  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003efa0 sp=0xc42003ef60 pc=0x42512eruntime.bgsweep(0xc42001e150)  /usr/local/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42003efd8 sp=0xc42003efa0 pc=0x419973runtime.goexit()  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003efe0 sp=0xc42003efd8 pc=0x44b4d1created by runtime.gcenable  /usr/local/go/src/runtime/mgc.go:216 +0x58one more line, no multiline"}]
[4] tail.0: [1638389215.477770954, {"log"=>"panic: my panic

goroutine 4 [running]:
panic(0x45cb40, 0x47ad70)
  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
main.main.func1(0xc420024120)
  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
created by main.main
  foo.go:5 +0x58

goroutine 1 [chan receive]:
runtime.gopark(0x4739b8, 0xc420024178, 0x46fcd7, 0xc, 0xc420028e17, 0x3)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc420053e30 sp=0xc420053e00 pc=0x42503c
runtime.goparkunlock(0xc420024178, 0x46fcd7, 0xc, 0x1000f010040c217, 0x3)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc420053e70 sp=0xc420053e30 pc=0x42512e
runtime.chanrecv(0xc420024120, 0x0, 0xc420053f01, 0x4512d8)
  /usr/local/go/src/runtime/chan.go:506 +0x304 fp=0xc420053f20 sp=0xc420053e70 pc=0x4046b4
runtime.chanrecv1(0xc420024120, 0x0)
  /usr/local/go/src/runtime/chan.go:388 +0x2b fp=0xc420053f50 sp=0xc420053f20 pc=0x40439b
main.main()
  foo.go:9 +0x6f fp=0xc420053f80 sp=0xc420053f50 pc=0x4512ef
runtime.main()
  /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc420053fe0 sp=0xc420053f80 pc=0x424bad
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420053fe8 sp=0xc420053fe0 pc=0x44b4d1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4739b8, 0x4ad720, 0x47001e, 0xf, 0x14, 0x1)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003e768 sp=0xc42003e738 pc=0x42503c
runtime.goparkunlock(0x4ad720, 0x47001e, 0xf, 0xc420000114, 0x1)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003e7a8 sp=0xc42003e768 pc=0x42512e
runtime.forcegchelper()
  /usr/local/go/src/runtime/proc.go:238 +0xcc fp=0xc42003e7e0 sp=0xc42003e7a8 pc=0x424e5c
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003e7e8 sp=0xc42003e7e0 pc=0x44b4d1
created by runtime.init.4
  /usr/local/go/src/runtime/proc.go:227 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4739b8, 0x4ad7e0, 0x46fdd2, 0xd, 0x419914, 0x1)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003ef60 sp=0xc42003ef30 pc=0x42503c
runtime.goparkunlock(0x4ad7e0, 0x46fdd2, 0xd, 0x14, 0x1)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003efa0 sp=0xc42003ef60 pc=0x42512e
runtime.bgsweep(0xc42001e150)
  /usr/local/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42003efd8 sp=0xc42003efa0 pc=0x419973
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003efe0 sp=0xc42003efd8 pc=0x44b4d1
created by runtime.gcenable
  /usr/local/go/src/runtime/mgc.go:216 +0x58"}]
[5] tail.0: [1638389215.477768634, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)"}]
[2021/12/02 04:06:56] [debug] [out coro] cb_destroy coro_id=0
[2021/12/02 04:06:56] [debug] [task] destroy task=0x7f362801ad50 (task_id=0)

```

- Steps to reproduce the problem:

**Your Environment**
* Version used: `1.8.10`
* Operating System and version: `Linux`

**Comment by nokute78** [comment]
Thank you for reporting.
v1.8.11 also doesn't work.
However [current master](https://github.com/fluent/fluent-bit/tree/0fbca8d3c4b95c949e285891f2ee458ac6e4aa3a) seems to work correctly.

```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/19 08:56:03] [ info] Configuration:
[2021/12/19 08:56:03] [ info]  flush time     | 1.000000 seconds
[2021/12/19 08:56:03] [ info]  grace          | 5 seconds
[2021/12/19 08:56:03] [ info]  daemon         | 0
[2021/12/19 08:56:03] [ info] ___________
[2021/12/19 08:56:03] [ info]  inputs:
[2021/12/19 08:56:03] [ info]      tail
[2021/12/19 08:56:03] [ info] ___________
[2021/12/19 08:56:03] [ info]  filters:
[2021/12/19 08:56:03] [ info]      multiline.0
[2021/12/19 08:56:03] [ info] ___________
[2021/12/19 08:56:03] [ info]  outputs:
[2021/12/19 08:56:03] [ info]      stdout.0
[2021/12/19 08:56:03] [ info] ___________
[2021/12/19 08:56:03] [ info]  collectors:
[2021/12/19 08:56:03] [ info] [engine] started (pid=23292)
[2021/12/19 08:56:03] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/12/19 08:56:03] [debug] [storage] [cio stream] new stream registered: tail.0
[2021/12/19 08:56:03] [ info] [storage] version=1.1.5, initializing...
[2021/12/19 08:56:03] [ info] [storage] in-memory
[2021/12/19 08:56:03] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/19 08:56:03] [ info] [cmetrics] version=0.2.2
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] inotify watch fd=23
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] scanning path test.log
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] inode=1451244 with offset=0 appended as test.log
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] scan_glob add(): test.log, inode 1451244
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] 1 new files found on path 'test.log'
[2021/12/19 08:56:03] [debug] [stdout:stdout.0] created event channels: read=25 write=26
[2021/12/19 08:56:03] [debug] [router] match rule tail.0:stdout.0
[2021/12/19 08:56:03] [ info] [sp] stream processor started
[2021/12/19 08:56:03] [debug] [input chunk] update output instances with new chunk size diff=3336
[2021/12/19 08:56:03] [debug] [input:tail:tail.0] inode=1451244 file=test.log promote to TAIL_EVENT
[2021/12/19 08:56:03] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1451244 watch_fd=1 name=test.log
[0] tail.0: [1638290843.126093742, {"log"=>"W1130 16:47:23.125742       1 metadata.go:191] Failed to parse the outpost arn: 
[2021/12/19 08:56:03] [debug] [task] created task=0x7ff6f4022650 id=0 OK
", "stream"=>"stderr", "time"=>"2021-11-30T16:47:23.126093742Z"}]
[1] tail.0: [1639871763.092303972, {"log"=>"single line..."}]
[2] tail.0: [1639871763.092304754, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)"}]
[3] tail.0: [1639871763.092308130, {"log"=>"another line..."}]
[4] tail.0: [1639871763.092308621, {"log"=>"panic: my panic

goroutine 4 [running]:
panic(0x45cb40, 0x47ad70)
  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
main.main.func1(0xc420024120)
  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
created by main.main
  foo.go:5 +0x58

goroutine 1 [chan receive]:
runtime.gopark(0x4739b8, 0xc420024178, 0x46fcd7, 0xc, 0xc420028e17, 0x3)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc420053e30 sp=0xc420053e00 pc=0x42503c
runtime.goparkunlock(0xc420024178, 0x46fcd7, 0xc, 0x1000f010040c217, 0x3)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc420053e70 sp=0xc420053e30 pc=0x42512e
runtime.chanrecv(0xc420024120, 0x0, 0xc420053f01, 0x4512d8)
  /usr/local/go/src/runtime/chan.go:506 +0x304 fp=0xc420053f20 sp=0xc420053e70 pc=0x4046b4
runtime.chanrecv1(0xc420024120, 0x0)
  /usr/local/go/src/runtime/chan.go:388 +0x2b fp=0xc420053f50 sp=0xc420053f20 pc=0x40439b
main.main()
  foo.go:9 +0x6f fp=0xc420053f80 sp=0xc420053f50 pc=0x4512ef
runtime.main()
  /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc420053fe0 sp=0xc420053f80 pc=0x424bad
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420053fe8 sp=0xc420053fe0 pc=0x44b4d1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4739b8, 0x4ad720, 0x47001e, 0xf, 0x14, 0x1)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003e768 sp=0xc42003e738 pc=0x42503c
runtime.goparkunlock(0x4ad720, 0x47001e, 0xf, 0xc420000114, 0x1)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003e7a8 sp=0xc42003e768 pc=0x42512e
runtime.forcegchelper()
  /usr/local/go/src/runtime/proc.go:238 +0xcc fp=0xc42003e7e0 sp=0xc42003e7a8 pc=0x424e5c
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003e7e8 sp=0xc42003e7e0 pc=0x44b4d1
created by runtime.init.4
  /usr/local/go/src/runtime/proc.go:227 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4739b8, 0x4ad7e0, 0x46fdd2, 0xd, 0x419914, 0x1)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc42003ef60 sp=0xc42003ef30 pc=0x42503c
runtime.goparkunlock(0x4ad7e0, 0x46fdd2, 0xd, 0x14, 0x1)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc42003efa0 sp=0xc42003ef60 pc=0x42512e
runtime.bgsweep(0xc42001e150)
  /usr/local/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc42003efd8 sp=0xc42003efa0 pc=0x419973
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003efe0 sp=0xc42003efd8 pc=0x44b4d1
created by runtime.gcenable
  /usr/local/go/src/runtime/mgc.go:216 +0x58"}]
[5] tail.0: [1639871763.092337016, {"log"=>"one more line, no multiline"}]
[2021/12/19 08:56:03] [debug] [out flush] cb_destroy coro_id=0
[2021/12/19 08:56:03] [debug] [task] destroy task=0x7ff6f4022650 (task_id=0)
^C[2021/12/19 08:56:04] [engine] caught signal (SIGINT)
[2021/12/19 08:56:04] [ info] [input] pausing tail.0
[2021/12/19 08:56:04] [ warn] [engine] service will shutdown in max 5 seconds
[2021/12/19 08:56:04] [ info] [engine] service has stopped (0 pending tasks)
[2021/12/19 08:56:04] [debug] [input:tail:tail.0] inode=1451244 removing file name test.log
[2021/12/19 08:56:04] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1451244 watch_fd=1
```
