### ISSUE TITLE
Use tailf (multiline.parse) to print the log, the last one will not be output

### ISSUE THREAD

**Issue by cheesetree** [fluent/fluent-bit#4458]
## Bug Report

**Describe the bug**

Use tailf (multiline.parse) to print the log, the last one will not be output
**To Reproduce**
- Rubular link if applicable:
- 
- Example log message if applicable:
```
fluent-bit.conf
[SERVICE]
    flush        1
    log_level    info
    parsers_file parsers_multiline.conf

[INPUT]
    name             tail
    path             test.log
    read_from_head   true
    multiline.parser multiline-regex-test

[OUTPUT]
    name             stdout
    match            *

parsers_multiline.conf
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule      "start_state"   "/(Dec \d+ \d+\:\d+\:\d+)(.*)/"  "cont"
    rule      "cont"          "/^\s+at.*/"                     "cont"

test.log
single line...
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
Dec 15 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)

```
- Steps to reproduce the problem:
td-agent-bit -c fluent-bit.conf

**Expected behavior**

print Complete log
**Screenshots**

Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/15 16:07:31] [Warning] [config] I cannot open /home/fluentbit/plugins.conf file
[2021/12/15 16:07:31] [ info] Configuration:
[2021/12/15 16:07:31] [ info]  flush time     | 5.000000 seconds
[2021/12/15 16:07:31] [ info]  grace          | 5 seconds
[2021/12/15 16:07:31] [ info]  daemon         | 0
[2021/12/15 16:07:31] [ info] ___________
[2021/12/15 16:07:31] [ info]  inputs:
[2021/12/15 16:07:31] [ info]      tail
[2021/12/15 16:07:31] [ info] ___________
[2021/12/15 16:07:31] [ info]  filters:
[2021/12/15 16:07:31] [ info] ___________
[2021/12/15 16:07:31] [ info]  outputs:
[2021/12/15 16:07:31] [ info]      stdout.0
[2021/12/15 16:07:31] [ info] ___________
[2021/12/15 16:07:31] [ info]  collectors:
[2021/12/15 16:07:31] [ info] [engine] started (pid=28213)
[2021/12/15 16:07:31] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/12/15 16:07:31] [debug] [storage] [cio stream] new stream registered: tail.0
[2021/12/15 16:07:31] [ info] [storage] version=1.1.5, initializing...
[2021/12/15 16:07:31] [ info] [storage] in-memory
[2021/12/15 16:07:31] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/15 16:07:31] [ info] [cmetrics] version=0.2.2
[2021/12/15 16:07:31] [ info] [input:tail:tail.0] multiline core started
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] inotify watch fd=24
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] scanning path /home/fluentbit/tt2.log
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] inode=9583685 with offset=0 appended as /home/fluentbit/tt2.log
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] scan_glob add(): /home/fluentbit/tt2.log, inode 9583685
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] 1 new files found on path '/home/fluentbit/tt2.log'
[2021/12/15 16:07:31] [debug] [stdout:stdout.0] created event channels: read=26 write=27
[2021/12/15 16:07:31] [debug] [router] match rule tail.0:stdout.0
[2021/12/15 16:07:31] [ info] [sp] stream processor started
[2021/12/15 16:07:31] [debug] [input:tail:tail.0] inode=9583685 file=/home/fluentbit/tt2.log promote to TAIL_EVENT
[2021/12/15 16:07:31] [ info] [input:tail:tail.0] inotify_fs_add(): inode=9583685 watch_fd=1 name=/home/fluentbit/tt2.log
[2021/12/15 16:07:32] [debug] [input:tail:tail.0] scanning path /home/fluentbit/tt2.log
[2021/12/15 16:07:32] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /home/fluentbit/tt2.log, inode 9583685
[2021/12/15 16:07:32] [debug] [input:tail:tail.0] 0 new files found on path '/home/fluentbit/tt2.log'
[2021/12/15 16:07:33] [debug] [input:tail:tail.0] scanning path /home/fluentbit/tt2.log
[2021/12/15 16:07:33] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /home/fluentbit/tt2.log, inode 9583685
[2021/12/15 16:07:33] [debug] [input:tail:tail.0] 0 new files found on path '/home/fluentbit/tt2.log'
[2021/12/15 16:07:34] [debug] [input:tail:tail.0] scanning path /home/fluentbit/tt2.log
[2021/12/15 16:07:34] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /home/fluentbit/tt2.log, inode 9583685
[2021/12/15 16:07:34] [debug] [input:tail:tail.0] 0 new files found on path '/home/fluentbit/tt2.log'
[2021/12/15 16:07:35] [debug] [input:tail:tail.0] scanning path /home/fluentbit/tt2.log
[2021/12/15 16:07:35] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /home/fluentbit/tt2.log, inode 9583685
[2021/12/15 16:07:35] [debug] [input:tail:tail.0] 0 new files found on path '/home/fluentbit/tt2.log'
[0] tail.0: [1639555651.989975658, {"log"=>"ngle line...
"}]
[1] tail.0: [1639555651.990012852, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
"}]
[2021/12/15 16:07:36] [debug] [task] created task=0x7fc11c037500 id=0 OK
**Your Environment**

* Version used: 1.8.11
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: centos7.9
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Is there a new line at the end? Tail waits for a new line to push the data into the pipeline.

**Comment by cheesetree** [comment]
no new line，If a new line is generated, the line that was not read last time will be output。
If the last line does not match [multiline.parse], it will be output, just like your examplep[https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing]

**Comment by cheesetree** [comment]
> Is there a new line at the end? Tail waits for a new line to push the data into the pipeline.
no new line，If a new line is generated, the line that was not read last time will be output。
If the last line does not match [multiline.parse], it will be output, just like your examplep[https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing]

**Comment by cheesetree** [comment]
> Is there a new line at the end? Tail waits for a new line to push the data into the pipeline.

no new line，If a new line is generated, the line that was not read last time will be output。
If the last line does not match [multiline.parse], it will be output, just like your examplep[https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing]

**Comment by cheesetree** [comment]
@patrick-stephens

**Comment by patrick-stephens** [comment]
I'm not really sure I follow: if there is no new line at the end or the start of a new matching multiline, i.e. `Dec` then how does Fluent Bit know it's finished matching all the lines? So it waits for more as there could be an arbitrary number of lines to match between each starting tag. If it doesn't match then we know it's finished.
