### ISSUE TITLE
multiline parser does not work for Containerd

### ISSUE THREAD

**Issue by xiaoping8385** [fluent/fluent-bit#4508]
## Bug Report

**Describe the bug**
Hi there, I configure my fluent-bit as :
```
[INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/test.log
        DB                /var/log/flb_kube.db
        multiline.parser  docker, cri
[FILTER]
        Name                   multiline
        Match                  *
        multiline.key_content  log
        multiline.parser       go, java
```
and 
the initial container.log is like ：

```single line...
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
another line...
panic: my panic

goroutine 4 [running]:
panic(0x45cb40, 0x47ad70)
  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
main.main.func1(0xc420024120)
  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
created by main.main
  foo.go:5 +0x58

goroutine 1 [chan receive]:
runtime.gopark(0x4739b8, 0xc420024178, 0x46fcd7, 0xc, 0xc420028e17, 0x3)
  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc420053e30 sp=0xc420053e00 pc=0x42503c
runtime.goparkunlock(0xc420024178, 0x46fcd7, 0xc, 0x1000f010040c217, 0x3)
  /usr/local/go/src/runtime/proc.go:286 +0x5e fp=0xc420053e70 sp=0xc420053e30 pc=0x42512e
runtime.chanrecv(0xc420024120, 0x0, 0xc420053f01, 0x4512d8)
  /usr/local/go/src/runtime/chan.go:506 +0x304 fp=0xc420053f20 sp=0xc420053e70 pc=0x4046b4
runtime.chanrecv1(0xc420024120, 0x0)
```
which I copied from the official doc sample.

As I was running it in containerd container, so the output log under /var/log/containers/ is like 
```
2021-12-22T02:36:56.941050368Z stdout F single line...
2021-12-22T02:36:56.941096311Z stdout F Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
2021-12-22T02:36:56.941101802Z stdout F     at com.myproject.module.MyProject.badMethod(MyProject.java:22)
2021-12-22T02:36:56.9411043Z stdout F     at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
2021-12-22T02:36:56.94110682Z stdout F     at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
2021-12-22T02:36:56.941109302Z stdout F     at com.myproject.module.MyProject.someMethod(MyProject.java:10)
2021-12-22T02:36:56.94111173Z stdout F     at com.myproject.module.MyProject.main(MyProject.java:6)
2021-12-22T02:36:56.941114604Z stdout F another line...
2021-12-22T02:36:56.941116989Z stdout F panic: my panic
2021-12-22T02:36:56.94111914Z stdout F 
2021-12-22T02:36:56.941122703Z stdout F goroutine 4 [running]:
2021-12-22T02:36:56.941125769Z stdout F panic(0x45cb40, 0x47ad70)
2021-12-22T02:36:56.941128769Z stdout F   /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
2021-12-22T02:36:56.941131055Z stdout F main.main.func1(0xc420024120)
2021-12-22T02:36:56.941133533Z stdout F   foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
2021-12-22T02:36:56.941135853Z stdout F runtime.goexit()
2021-12-22T02:36:56.941138281Z stdout F   /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
2021-12-22T02:36:56.941140724Z stdout F created by main.main
2021-12-22T02:36:56.941142941Z stdout F   foo.go:5 +0x58
2021-12-22T02:36:56.941145054Z stdout F 
2021-12-22T02:36:56.9411473
```
I expected to see those mulitiline logs  be concatenated but I only get the first mulitiline message been successfully handled and not the next.
the output was like:
```
Fluent Bit v1.8.10
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[0] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116297444, {"time"=>"2021-12-22T02:05:41.116297444Z", "stream"=>"stdout", "_p"=>"F", "log"=>"single line..."}]
[1] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116334376, {"time"=>"2021-12-22T02:05:41.116334376Z", "stream"=>"stdout", "_p"=>"F", "log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)"}]
[2] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116360318, {"time"=>"2021-12-22T02:05:41.116360318Z", "stream"=>"stdout", "_p"=>"F", "log"=>"another line..."}]
[3] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116363462, {"time"=>"2021-12-22T02:05:41.116363462Z", "stream"=>"stdout", "_p"=>"F", "log"=>"panic: my panic"}]
[4] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138743.404566405, {"log"=>"2021-12-22T02:05:41.116366563Z stdout F "}]
[5] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116370499, {"time"=>"2021-12-22T02:05:41.116370499Z", "stream"=>"stdout", "_p"=>"F", "log"=>"goroutine 4 [running]:"}]
[6] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116374103, {"time"=>"2021-12-22T02:05:41.116374103Z", "stream"=>"stdout", "_p"=>"F", "log"=>"panic(0x45cb40, 0x47ad70)"}]
[7] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116378042, {"time"=>"2021-12-22T02:05:41.116378042Z", "stream"=>"stdout", "_p"=>"F", "log"=>"  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c"}]
[8] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116381702, {"time"=>"2021-12-22T02:05:41.116381702Z", "stream"=>"stdout", "_p"=>"F", "log"=>"main.main.func1(0xc420024120)"}]
[9] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116385381, {"time"=>"2021-12-22T02:05:41.116385381Z", "stream"=>"stdout", "_p"=>"F", "log"=>"  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339"}]
[10] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116388793, {"time"=>"2021-12-22T02:05:41.116388793Z", "stream"=>"stdout", "_p"=>"F", "log"=>"runtime.goexit()"}]
[11] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116392343, {"time"=>"2021-12-22T02:05:41.116392343Z", "stream"=>"stdout", "_p"=>"F", "log"=>"  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1"}]
[12] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116395781, {"time"=>"2021-12-22T02:05:41.116395781Z", "stream"=>"stdout", "_p"=>"F", "log"=>"created by main.main"}]
[13] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116399251, {"time"=>"2021-12-22T02:05:41.116399251Z", "stream"=>"stdout", "_p"=>"F", "log"=>"  foo.go:5 +0x58"}]
[14] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138743.404566405, {"log"=>"2021-12-22T02:05:41.116402724Z stdout F "}]
[15] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116406309, {"time"=>"2021-12-22T02:05:41.116406309Z", "stream"=>"stdout", "_p"=>"F", "log"=>"goroutine 1 [chan receive]:"}]
[16] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116409950, {"time"=>"2021-12-22T02:05:41.11640995Z", "stream"=>"stdout", "_p"=>"F", "log"=>"runtime.gopark(0x4739b8, 0xc420024178, 0x46fcd7, 0xc, 0xc420028e17, 0x3)"}]
[17] kube.var.log.containers.test-log_default_count-e54975ff8223b51518793c17dd5a41c6c44e60acba86bef349637b0ab82bc5fd.log: [1640138741.116413696, {"time"=>"2021-12-22T02:05:41.116413696Z", "stream"=>"stdout", "_p"=>"F", "log"=>"  /usr/local/go/src/runtime/proc.go:280 +0x12c fp=0xc420053e30 sp=0xc420053e00 pc=0x42503c"}]
```

**To Reproduce**
Run fluent-bit  with above configuration

**Expected behavior**
both two multiline messages should be handled correctly

**Screenshots**

**Your Environment**

* Version used:1.8.10
* Configuration:see above
* Environment name and version (e.g. Kubernetes? What version?):kubernetes 1.21
* Operating System and version:ubuntu
* Filters and plugins: tail, filter

**Comment by nokute78** [comment]
It is fixed on master, but it isn't released yet.
Issue: https://github.com/fluent/fluent-bit/issues/4034
Patch: https://github.com/fluent/fluent-bit/pull/4375

I tested it on [master](https://github.com/fluent/fluent-bit/tree/89574f9970c928dcf7f69f6b45d9bf180ef8eee9).
```
[INPUT]
        Name              tail
        Tag               kube.*
        Path              a.log
        multiline.parser  docker, cri
        Read_From_Head    true

[FILTER]
        Name                   multiline
        Match                  *
        multiline.key_content  log
        multiline.parser       go, java

[OUTPUT]
        Name stdout
```

a.log:
```
2021-12-22T02:36:56.941050368Z stdout F single line...
2021-12-22T02:36:56.941096311Z stdout F Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
2021-12-22T02:36:56.941101802Z stdout F     at com.myproject.module.MyProject.badMethod(MyProject.java:22)
2021-12-22T02:36:56.9411043Z stdout F     at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
2021-12-22T02:36:56.94110682Z stdout F     at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
2021-12-22T02:36:56.941109302Z stdout F     at com.myproject.module.MyProject.someMethod(MyProject.java:10)
2021-12-22T02:36:56.94111173Z stdout F     at com.myproject.module.MyProject.main(MyProject.java:6)
2021-12-22T02:36:56.941114604Z stdout F another line...
2021-12-22T02:36:56.941116989Z stdout F panic: my panic
2021-12-22T02:36:56.94111914Z stdout F 
2021-12-22T02:36:56.941122703Z stdout F goroutine 4 [running]:
2021-12-22T02:36:56.941125769Z stdout F panic(0x45cb40, 0x47ad70)
2021-12-22T02:36:56.941128769Z stdout F   /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
2021-12-22T02:36:56.941131055Z stdout F main.main.func1(0xc420024120)
2021-12-22T02:36:56.941133533Z stdout F   foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
2021-12-22T02:36:56.941135853Z stdout F runtime.goexit()
2021-12-22T02:36:56.941138281Z stdout F   /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
2021-12-22T02:36:56.941140724Z stdout F created by main.main
2021-12-22T02:36:56.941142941Z stdout F   foo.go:5 +0x58
2021-12-22T02:36:56.941145054Z stdout F 

```

Output:
```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/28 08:39:29] [ info] [engine] started (pid=11343)
[2021/12/28 08:39:29] [ info] [storage] version=1.1.5, initializing...
[2021/12/28 08:39:29] [ info] [storage] in-memory
[2021/12/28 08:39:29] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/28 08:39:29] [ info] [cmetrics] version=0.2.2
[2021/12/28 08:39:29] [ info] [input:tail:tail.0] multiline core started
[2021/12/28 08:39:29] [ info] [sp] stream processor started
[2021/12/28 08:39:29] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1453992 watch_fd=1 name=a.log
[0] kube.a.log: [1640140616.941050368, {"time"=>"2021-12-22T02:36:56.941050368Z", "stream"=>"stdout", "_p"=>"F", "log"=>"single line..."}]
[1] kube.a.log: [1640140616.941096311, {"time"=>"2021-12-22T02:36:56.941096311Z", "stream"=>"stdout", "_p"=>"F", "log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)"}]
[2] kube.a.log: [1640140616.941114604, {"time"=>"2021-12-22T02:36:56.941114604Z", "stream"=>"stdout", "_p"=>"F", "log"=>"another line..."}]
[3] kube.a.log: [1640140616.941116989, {"time"=>"2021-12-22T02:36:56.941116989Z", "stream"=>"stdout", "_p"=>"F", "log"=>"panic: my panic

goroutine 4 [running]:
panic(0x45cb40, 0x47ad70)
  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
main.main.func1(0xc420024120)
  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
created by main.main
  foo.go:5 +0x58

"}]
^C[2021/12/28 08:39:34] [engine] caught signal (SIGINT)
[2021/12/28 08:39:34] [ info] [input] pausing tail.0
[2021/12/28 08:39:34] [ warn] [engine] service will shutdown in max 5 seconds
[2021/12/28 08:39:35] [ info] [engine] service has stopped (0 pending tasks)
[2021/12/28 08:39:35] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1453992 watch_fd=1
```

**Comment by xiaoping8385** [comment]
@lecaros does 1.8.12 contain this fix?

**Comment by lecaros** [comment]
Hi @xiaoping8385, no, it's only available for the future 1.9 release.

**Comment by Antiarchitect** [comment]
Just tried 1.9.0 have no errors but logs are not going. Config is:

```
    [INPUT]
        name              tail
        tag               k8s
        path              /var/log/containers/*.log
        db                /var/log/core-node-log-collector-containers-logs.db
        key               raw
        path_key          source
        multiline.parser  cri
        ignore_older      1d
        mem_buf_limit     256MB
        refresh_interval  10
        skip_long_lines   on
```

**Comment by lecaros** [comment]
I've just tried the test case from https://github.com/fluent/fluent-bit/issues/4508#issuecomment-1001800654, and it doesn't work. @nokute78, can you please confirm whether it works for you?

**Comment by nokute78** [comment]
The test case from https://github.com/fluent/fluent-bit/issues/4508#issuecomment-1001800654 didn't work from https://github.com/fluent/fluent-bit/commit/a7414f0209357970d4f09414c20d6eaac0045dcc
It worked correctly on [Previous commit](https://github.com/fluent/fluent-bit/commit/355a6c8c779494a23d73a6479a62b6dada609066) .
The PR is https://github.com/fluent/fluent-bit/pull/4583 .

Note: The unit test of multiline on [current master](https://github.com/fluent/fluent-bit/tree/67b144340b46bbc2585363cc1fb2de6b662e7b36) works correctly.
I think it also means the changing ingestion way may affect it.


Cc @edsiper
