### ISSUE TITLE
multiline parser in EKS not working correctly ( breaking at mid trace ) 

### ISSUE THREAD

**Issue by UsamaMehboob** [fluent/fluent-bit#4608]
## Bug Report

**using multine filter on java trace but it breaks mid trace**

Below is the output of my processed logs, you can see it starts nicely with timestamp as it should owing to the multine parser but then it breaks midway at the exception which does not make sense. 
**To Reproduce**
- Example log message if applicable:
```
#######
processed output logs
########
[5] kube.var.log.containers.log-img-7c96c47944-zngq9_default_log-img-9fee0000afb84d16a4e5af3a658b6e3ea8e866b8276db176ed54365259306f67.log: [1642005766.558141400, {"log"=>"2022-01-12T16:21:01,947Z ERROR [http-nio-8080-exec-4] c.v.s.w.c.IgniteRestController: Failed to parse query. Syntax error in SQL statement "FAILING10[*] "; expected "FROM, {"; SQL statement:
failing10 [42001-197]
java.sql.SQLException: Failed to parse query. Syntax error in SQL statement "FAILING10[*] "; expected "FROM, {"; SQL statement:
failing10 [42001-197]
	at org.apache.ignite.internal.jdbc.thin.JdbcThinConnection.sendRequest(JdbcThinConnection.java:1009)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinStatement.execute0(JdbcThinStatement.java:234)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinPreparedStatement.executeWithArguments(JdbcThinPreparedStatement.java:252)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinPreparedStatement.executeQuery(JdbcThinPreparedStatement.java:78)
	at com.veeva.source.ignite.ResultIterable.<init>(ResultIterable.java:38)
	at com.veeva.source.ignite.IgniteService.query(IgniteService.java:461)
	at com.veeva.source.ignite.IgniteService.query(IgniteService.java:442)
	at com.veeva.source.web.controller.IgniteRestController.runIgniteSql(IgniteRestController.java:87)
	at com.veeva.source.web.controller.IgniteRestController$$FastClassBySpringCGLIB$$dfee0119.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.veeva.source.web.controller.IgniteRestController$$EnhancerBySpringCGLIB$$7c27e2aa.runIgniteSql(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
", "stream"=>"stdout", "time"=>"2022-01-12T16:42:46.5581414Z", "kubernetes"=>{"pod_name"=>"log-img-7c96c47944-zngq9", "namespace_name"=>"default", "pod_id"=>"90a64561-094c-4517-89a9-6caf767dc53b", "host"=>"docker-desktop", "container_name"=>"log-img", "docker_id"=>"9fee0000afb84d16a4e5af3a658b6e3ea8e866b8276db176ed54365259306f67", "container_hash"=>"sha256:a6836c9451865df5983727202c785cd57b73d00f640e46598a3977c82c824778", "container_image"=>"log-img:latest"}}]
[6] kube.var.log.containers.log-img-7c96c47944-zngq9_default_log-img-9fee0000afb84d16a4e5af3a658b6e3ea8e866b8276db176ed54365259306f67.log: [1642005766.558141400, {"log"=>"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
```
- Steps to reproduce the problem:
any Pod that is emitting my sample log and with my configs should help you to reproduce the problem.
**Expected behavior**

All java stack traces should be merged
**Screenshots**

**Your Environment**

* fluent-bit version 1.8.11 (  Helm chart ) 
* EKS 1.20
* amazon eks ami
* multiline filter:

**Additional context**

```
####fluent-configs###
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/log*.log
        Tag kube.*
        Mem_Buf_Limit 5MB
        Buffer_Chunk_Size 256k
        Buffer_Max_Size 2M
        Multiline.parser            docker

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                   multiline
        Match                  kube.*
        Multiline.Key_Content  log
        Multiline.Parser       iots-components-multiline  
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        merge_log On
        merge_log_key log_processed
        Keep_Log On
        Labels Off
        Annotations Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off    

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name stdout
        Match kube.*
    [OUTPUT]
        Name es
        Match kube.*
        Host opensearch-cluster-master
        net.keepalive On
        HTTP_User admin
        HTTP_Passwd admin
        index test-logs
        port 9200
        tls On
        tls.verify Off
        Buffer_Size 25M
        Retry_Limit False

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [MULTILINE_PARSER]
        Name          iots-components-multiline
        Type          regex
        Flush_timeout 1000
        #Rule      "start_state"   "/^\[.*/"                            "cont"
        #Rule      "cont"          "/^[^\[].*/"                         "cont"      
        Rule      "start_state"   "/^(\d{4}-\d{2}-\d{2}T\d{2}\:\d{2}\:\d{2},\d{3})(.*)/"       "cont"
        Rule      "cont"          "/^(?!\d{4}-\d{2}-\d{2}T\d{2}\:\d{2}\:\d{2},\d{3})(.*)/"     "cont"
```

sample logs https://pastebin.com/raw/pd78X8L6

**Comment by lecaros** [comment]
Hi @UsamaMehboob,
I couldn't get this reproduced as in 
```

at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
", "stream"=>"stdout", "time"=>"2022-01-12T16:42:46.5581414Z", "kubernetes"=>{"pod_name"=>"log-img-7c96c47944-zngq9", "namespace_name"=>"default", "pod_id"=>"90a64561-094c-4517-89a9-6caf767dc53b", "host"=>"docker-desktop", "container_name"=>"log-img", "docker_id"=>"9fee0000afb84d16a4e5af3a658b6e3ea8e866b8276db176ed54365259306f67", "container_hash"=>"sha256:a6836c9451865df5983727202c785cd57b73d00f640e46598a3977c82c824778", "container_image"=>"log-img:latest"}}]
[6] kube.var.log.containers.log-img-7c96c47944-zngq9_default_log-img-9fee0000afb84d16a4e5af3a658b6e3ea8e866b8276db176ed54365259306f67.log: [1642005766.558141400, {"log"=>"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)

````


Are you still able to reproduce this locally? If yes, please share your config and input file if different from the shared in pastebin.
