### ISSUE TITLE
Enable global regex flag in Parser

### ISSUE THREAD

**Issue by TimSin** [fluent/fluent-bit#4627]
As explained in the thread at https://github.com/fluent/fluent-bit/issues/4551, I'm trying parse Java logs from a k8s cluster. Whilst I have an almost fully functional config, I'm left with logging information from the k8s logs in the logging entries sent to my output (note additional `  2022-01-18T18:43:21.697964822Z stderr F ` entries in stack trace):

```
com.yyyy.exception.NotFoundException: Project with id XXX not found
  2022-01-18T18:43:21.697964822Z stderr F 	at com.yyyy.ProjectController.getProject(ProjectController.java:135)
  2022-01-18T18:43:21.698208916Z stderr F 	at jdk.internal.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
  2022-01-18T18:43:21.698536694Z stderr F 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  2022-01-18T18:43:21.698681894Z stderr F 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```
The Parser filter feature removes these from the first line, but because the regex only runs on the first line, the others are left with the additional text that needs to be removed. I'm not familiar with the architecture of fluent bit, but the ability to enabling the `global` flag on a regex would solve this issue I think.

Alternatively, the ability to chain parsers as suggested in the original ticket might also work in this situation. Any other suggestions welcome.

**Comment by ajurge** [comment]
It would be great to have a generic solution for this issue, please see  my comment: https://github.com/fluent/fluent-bit/issues/4551#issuecomment-1084499580
