### ISSUE TITLE
mulltilline parser doesn't concatenate logs line right

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#4687]
## Bug Report

**Describe the bug**
mulltilline parser doesn't concatenate logs line right

**To Reproduce**
### shared log file
```
sophieyfang_google_com@debian10-meow:~$ cat java.log 
javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
    ... 27 common frames omitted
java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.base/java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:229)
	... 12 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
```
#### version1
```
sophieyfang_google_com@debian10-meow:~$ cat fluentbit-java.conf 
[SERVICE]
    flush                 1
    log_level             info

[INPUT]
    name                  tail
    path                  java.log
    read_from_head        true
    multiline.parser      java


[OUTPUT]
    name                  stdout
    match                 *
```
```
sophieyfang_google_com@debian10-meow:~$ /opt/google-cloud-ops-agent/subagents/fluent-bit/bin/fluent-bit --config fluentbit-java.conf 
Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/01/25 18:16:31] [ info] [engine] started (pid=8270)
[2022/01/25 18:16:31] [ info] [storage] version=1.1.5, initializing...
[2022/01/25 18:16:31] [ info] [storage] in-memory
[2022/01/25 18:16:31] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/01/25 18:16:31] [ info] [cmetrics] version=0.2.2
[2022/01/25 18:16:31] [ info] [input:tail:tail.0] multiline core started
[2022/01/25 18:16:31] [ info] [input:tail:tail.0] inotify_fs_add(): inode=138414 watch_fd=1 name=java.log
[0] tail.0: [1643134591.015290789, {"log"=>"javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
    ... 27 common frames omitted
"}]
[1] tail.0: [1643134591.015320461, {"log"=>"java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[2] tail.0: [1643134591.015358721, {"log"=>"com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.base/java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
```

#### Version2
```
sophieyfang_google_com@debian10-meow:~$ cat fluentbit-java.conf 
[SERVICE]
    flush                 1
    log_level             info
    parsers_file          parsers_multiline_java.conf

[INPUT]
    name                  tail
    path                  java.log
    read_from_head        true
    multiline.parser      java,multiline-regex-test


[OUTPUT]
    name                  stdout
    match                 *
sophieyfang_google_com@debian10-meow:~$ cat parsers_multiline_java.conf
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\\r\\n]/" "java_after_exception"
    rule "java_after_exception" "/^[\\t ]*nested exception is:[\\t ]*/" "java_start_exception"
    rule "java_after_exception" "/^[\\r\\n]*$/" "java_after_exception"
    rule "java_after_exception, java" "/^[\\t ]+(?:eval )?at /" "java"
    rule "java_after_exception, java" "/^[\\t ]+--- End of inner exception stack trace ---$/" "java"
    rule "java_after_exception, java" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java"
    rule "java_after_exception, java" "/^[\\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule "java_after_exception, java" "/^[\\t ]*... \\d+ (?:more|common frames omitted)/" "java" 
```

```
sophieyfang_google_com@debian10-meow:~$ /opt/google-cloud-ops-agent/subagents/fluent-bit/bin/fluent-bit --config fluentbit-java.conf 
Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/01/25 18:17:37] [ info] [engine] started (pid=8277)
[2022/01/25 18:17:37] [ info] [storage] version=1.1.5, initializing...
[2022/01/25 18:17:37] [ info] [storage] in-memory
[2022/01/25 18:17:37] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/01/25 18:17:37] [ info] [cmetrics] version=0.2.2
[2022/01/25 18:17:37] [ info] [input:tail:tail.0] multiline core started
[2022/01/25 18:17:37] [ info] [input:tail:tail.0] inotify_fs_add(): inode=138414 watch_fd=1 name=java.log
[0] tail.0: [1643134657.434022796, {"log"=>"javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
    ... 27 common frames omitted
"}]
[1] tail.0: [1643134657.434092399, {"log"=>"java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[2] tail.0: [1643134657.434073797, {"log"=>"java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[3] tail.0: [1643134657.434095165, {"log"=>"com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
"}]
[4] tail.0: [1643134657.434095165, {"log"=>"Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[5] tail.0: [1643134657.434094559, {"log"=>"com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.base/java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[6] tail.0: [1643134657.434197097, {"log"=>"com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
"}]
```

#### Version 3
```
sophieyfang_google_com@debian10-meow:~$ cat fluentbit-java.conf 
[SERVICE]
    flush                 1
    log_level             info
    parsers_file          parsers_multiline_java.conf

[INPUT]
    name                  tail
    path                  java.log
    read_from_head        true
    multiline.parser      multiline-regex-test


[OUTPUT]
    name                  stdout
    match                 *
sophieyfang_google_com@debian10-meow:~$ cat parsers_multiline_java.conf
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\\r\\n]/" "java_after_exception"
    rule "java_after_exception" "/^[\\t ]*nested exception is:[\\t ]*/" "java_start_exception"
    rule "java_after_exception" "/^[\\r\\n]*$/" "java_after_exception"
    rule "java_after_exception, java" "/^[\\t ]+(?:eval )?at /" "java"
    rule "java_after_exception, java" "/^[\\t ]+--- End of inner exception stack trace ---$/" "java"
    rule "java_after_exception, java" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java"
    rule "java_after_exception, java" "/^[\\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule "java_after_exception, java" "/^[\\t ]*... \\d+ (?:more|common frames omitted)/" "java"  
```

```
sophieyfang_google_com@debian10-meow:~$ /opt/google-cloud-ops-agent/subagents/fluent-bit/bin/fluent-bit --config fluentbit-java.conf 
Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/01/25 18:20:22] [ info] [engine] started (pid=8290)
[2022/01/25 18:20:22] [ info] [storage] version=1.1.5, initializing...
[2022/01/25 18:20:22] [ info] [storage] in-memory
[2022/01/25 18:20:22] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/01/25 18:20:22] [ info] [cmetrics] version=0.2.2
[2022/01/25 18:20:22] [ info] [input:tail:tail.0] multiline core started
[2022/01/25 18:20:22] [ info] [input:tail:tail.0] inotify_fs_add(): inode=138414 watch_fd=1 name=java.log
[0] tail.0: [1643134822.629361171, {"log"=>"javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
"}]
[1] tail.0: [1643134822.629361171, {"log"=>"    ... 27 common frames omitted
"}]
[2] tail.0: [1643134822.629399298, {"log"=>"java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[3] tail.0: [1643134822.629403820, {"log"=>"com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
"}]
[4] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
"}]
[5] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
"}]
[6] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
"}]
[7] tail.0: [1643134822.629403820, {"log"=>"	at java.util.Optional.ifPresent(Optional.java:159)
"}]
[8] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
"}]
[9] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
"}]
[10] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
"}]
[11] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
"}]
[12] tail.0: [1643134822.629403820, {"log"=>"	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
"}]
[13] tail.0: [1643134822.629403820, {"log"=>"	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
"}]
[14] tail.0: [1643134822.629403820, {"log"=>"	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
"}]
[15] tail.0: [1643134822.629403820, {"log"=>"	at java.base/java.lang.Thread.run(Thread.java:748)
"}]
[16] tail.0: [1643134822.629403820, {"log"=>"Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
"}]
[17] tail.0: [1643134822.629502495, {"log"=>"com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
"}]
[18] tail.0: [1643134822.629502495, {"log"=>"	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
"}]
[19] tail.0: [1643134822.629502495, {"log"=>"	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
"}]
[20] tail.0: [1643134822.629502495, {"log"=>"	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:229)
"}]
[21] tail.0: [1643134822.629502495, {"log"=>"	... 12 more
"}]
```

- Steps to reproduce the problem:
See above

**Expected behavior**
It shall form two log entries.

**Comment by sophieyfang** [comment]
Also, there seem discrepancy between the interface that the build-in language support, e.g. java uses versus the general rules.

I got below rules from https://github.com/fluent/fluent-bit/blob/master/src/multiline/flb_ml_parser_java.c and https://github.com/fluent/fluent-bit/blob/master/src/multiline/flb_ml_mode_java.c. So the build-in java support and the custom rules that i set shall be identical, but if you look at the version 1 V.S. version3, you will see the output is very different.

```
sophieyfang_google_com@debian10-meow:~$ cat parsers_multiline_java.conf
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\\r\\n]/" "java_after_exception"
    rule "java_after_exception" "/^[\\t ]*nested exception is:[\\t ]*/" "java_start_exception"
    rule "java_after_exception" "/^[\\r\\n]*$/" "java_after_exception"
    rule "java_after_exception, java" "/^[\\t ]+(?:eval )?at /" "java"
    rule "java_after_exception, java" "/^[\\t ]+--- End of inner exception stack trace ---$/" "java"
    rule "java_after_exception, java" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java"
    rule "java_after_exception, java" "/^[\\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule "java_after_exception, java" "/^[\\t ]*... \\d+ (?:more|common frames omitted)/" "java" 
```

**Comment by sophieyfang** [comment]
Another thing to mention up, 
`multiline.parser      java,multiline-regex-test`. I checked the code, it seems merging those two into one pile of rules...Am i right? The problem with this set-up is it might wrongly concatenate logs with different personality into one

**Comment by lecaros** [comment]
Hi Sophie,
you can use this configuration for your use cases. Let me know if you have any use case that is not supported by this config.

```
➜  testcase cat config.conf
[SERVICE]
    flush                 1
    log_level             info
    log_file              fluent.log
    parsers_file          parsers_multiline_java.conf

[INPUT]
    name                  tail
    path                  all.log
    read_from_head        true
    multiline.parser      multiline-regex-test


[OUTPUT]
    name                  stdout
    match                 *

```
```
➜  testcase cat parsers_multiline_java.conf
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule "java_nested_exception" "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]*nested exception is:[\\t ]*/" "java_nested_exception"
    rule "java_after_exception" "/^[\r\n]*$/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]+(?:eval )?at /" "java_after_exception"
    rule "java_after_exception" "/^[\t ]+--- End of inner exception stack trace ---$/" "java_after_exception"
    rule "java_after_exception" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]*... \d+ (?:more|common frames omitted)/" "java_after_exception"
```

Notice we're only using multiline parser, not the java one.

**Comment by mbaykara** [comment]
@sophieyfang The actual issue is the `buffer` size, so if you increase the buffer size i.e 16mb, your problem will be solved.
