### ISSUE TITLE
Tail property `key` is not appreciated when using with multiline.parser

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#4795]
## Bug Report

**Describe the bug**
Tail property `key` is not appreciated when using with multiline.parser. It shall be `message` not `log`

**To Reproduce**
```
sophieyfang_google_com@debian10-meow:~$ cat fluentbit-java.conf 
[SERVICE]
    flush                 1
    log_level             debug
    parsers_file          parsers_multiline_java.conf

[INPUT]
    name                  tail
    path                  j.log
    key			  message
    read_from_head        true
    multiline.parser      multiline-regex-test 
[OUTPUT]
    name                  stdout
    match                 *
sophieyfang_google_com@debian10-meow:~$ cat parsers_multiline_java.conf
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule "java_nested_exception" "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]*nested exception is:[\\t ]*/" "java_nested_exception"
    rule "java_after_exception" "/^[\r\n]*$/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]+(?:eval )?at /" "java_after_exception"
    rule "java_after_exception" "/^[\t ]+--- End of inner exception stack trace ---$/" "java_after_exception"
    rule "java_after_exception" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule "java_after_exception" "/^[\t ]*... \d+ (?:more|common frames omitted)/" "java_after_exception"
sophieyfang_google_com@debian10-meow:~$ cat j.log 
Jul 09, 2015 3:23:29 PM com.google.devtools.search.cloud.feeder.MakeLog: RuntimeException: Run from this message!
  at com.my.app.Object.do$a1(MakeLog.java:50)
  at java.lang.Thing.call(Thing.java:10)
javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
    ... 27 common frames omitted
java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.base/java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:229)
	... 12 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied

sophieyfang_google_com@debian10-meow:~$ /opt/google-cloud-ops-agent/subagents/fluent-bit/bin/fluent-bit --config fluentbit-java.conf 
Fluent Bit v1.8.12
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/02/10 17:03:25] [ info] Configuration:
[2022/02/10 17:03:25] [ info]  flush time     | 1.000000 seconds
[2022/02/10 17:03:25] [ info]  grace          | 5 seconds
[2022/02/10 17:03:25] [ info]  daemon         | 0
[2022/02/10 17:03:25] [ info] ___________
[2022/02/10 17:03:25] [ info]  inputs:
[2022/02/10 17:03:25] [ info]      tail
[2022/02/10 17:03:25] [ info] ___________
[2022/02/10 17:03:25] [ info]  filters:
[2022/02/10 17:03:25] [ info] ___________
[2022/02/10 17:03:25] [ info]  outputs:
[2022/02/10 17:03:25] [ info]      stdout.0
[2022/02/10 17:03:25] [ info] ___________
[2022/02/10 17:03:25] [ info]  collectors:
[2022/02/10 17:03:25] [ info] [engine] started (pid=32724)
[2022/02/10 17:03:25] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2022/02/10 17:03:25] [debug] [storage] [cio stream] new stream registered: tail.0
[2022/02/10 17:03:25] [ info] [storage] version=1.1.5, initializing...
[2022/02/10 17:03:25] [ info] [storage] in-memory
[2022/02/10 17:03:25] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/02/10 17:03:25] [ info] [cmetrics] version=0.2.2
[2022/02/10 17:03:25] [ info] [input:tail:tail.0] multiline core started
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] flb_tail_fs_inotify_init() initializing inotify tail input
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] inotify watch fd=24
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] scanning path j.log
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] inode=143377 with offset=0 appended as j.log
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] scan_glob add(): j.log, inode 143377
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] 1 new files found on path 'j.log'
[2022/02/10 17:03:25] [debug] [stdout:stdout.0] created event channels: read=26 write=27
[2022/02/10 17:03:25] [debug] [router] match rule tail.0:stdout.0
[2022/02/10 17:03:25] [debug] [input chunk] update output instances with new chunk size diff=219
[2022/02/10 17:03:25] [debug] [input chunk] update output instances with new chunk size diff=2279
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] [static files] processed 4.3K
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] inode=143377 file=j.log promote to TAIL_EVENT
[2022/02/10 17:03:25] [ info] [input:tail:tail.0] inotify_fs_add(): inode=143377 watch_fd=1 name=j.log
[2022/02/10 17:03:25] [debug] [input:tail:tail.0] [static files] processed 0b, done
[0] tail.0: [1644512605.143422394, {"log"=>"Jul 09, 2015 3:23:29 PM com.google.devtools.search.cloud.feeder.MakeLog: RuntimeException: Run from this message!
  at com.my.app.Object.do$a1(MakeLog.java:50)
  at java.lang.Thing.call(Thing.java:10)
"}]
[1] tail.0: [1644512605.143435339, {"log"=>"javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
    ... 27 common frames omitted
"}]
[2] tail.0: [1644512605.143546594, {"log"=>"java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.base/java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:229)
	... 12 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied

"}]
[2022/02/10 17:03:25] [debug] [input chunk] update output instances with new chunk size diff=1913
[2022/02/10 17:03:25] [debug] [task] created task=0x7f8f24015730 id=0 OK
[2022/02/10 17:03:25] [debug] [out coro] cb_destroy coro_id=0
[2022/02/10 17:03:25] [debug] [task] destroy task=0x7f8f24015730 (task_id=0)
^C[2022/02/10 17:03:29] [engine] caught signal (SIGINT)
[2022/02/10 17:03:29] [ info] [input] pausing tail.0
[2022/02/10 17:03:29] [ warn] [engine] service will shutdown in max 5 seconds
[2022/02/10 17:03:29] [ info] [engine] service has stopped (0 pending tasks)
```

**Comment by qingling128** [comment]
We have a workaround for this that uses an additional filter to rename `log` to `message`. The downside is that it hurts performance.
