### ISSUE TITLE
tail multiline parser + debian11 --> SIGSEGV

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#4944]
## Bug Report

**Describe the bug**
Using multiline parser properting tailing a file in debian11 machine leads to SIGSEGV bug
de
**To Reproduce**
```
$ gcloud compute instances create --image-project debian-cloud --image-family debian-11 --zone us-central1-a debian11
$ gcloud compute ssh debian111
$ cat fluent_bit_main.conf 
[INPUT]
    Key               message
    Name              tail
    Path              /home/sophieyfang_google_com/xiaoo
    Read_from_Head    True
    Tag               p1.files_1
    multiline.parser  multiline.p1.files_1.0_0

[FILTER]
    Match  p1.files_1
    Name   modify
    Rename log message

[FILTER]
    Add   logging.googleapis.com/logName files_1
    Match p1.files_1
    Name  modify

[OUTPUT]
    name                  stdout
    match                 *
$ cat fluent_bit_parser.conf 
[MULTILINE_PARSER]
    flush_timeout 1000
    name          multiline.p1.files_1.0_0
    type          regex
    rule          "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule          "java_nested_exception" "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]*nested exception is:[\\t ]*/" "java_nested_exception"
    rule          "java_after_exception" "/^[\r\n]*$/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]+(?:eval )?at /" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]+--- End of inner exception stack trace ---$/" "java_after_exception"
    rule          "java_after_exception" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]*... \d+ (?:more|common frames omitted)/" "java_after_exception"
$ sudo /opt/google-cloud-ops-agent/subagents/fluent-bit/bin/fluent-bit --config fluent_bit_main.conf --parser  fluent_bit_parser.conf 
Fluent Bit v1.8.12
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/02/28 19:26:57] [engine] caught signal (SIGSEGV)
[2022/02/28 19:26:57] [ info] [engine] started (pid=9701)
[2022/02/28 19:26:57] [ info] [storage] version=1.1.5, initializing...
[2022/02/28 19:26:57] [ info] [storage] in-memory
[2022/02/28 19:26:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/02/28 19:26:57] [ info] [cmetrics] version=0.2.2
[2022/02/28 19:26:57] [ info] [input:tail:tail.0] multiline core started
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)Aborted
```

**Your Environment**
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Additional context**
This block the ops-agent from using this feature

**Comment by patrick-stephens** [comment]
I wonder if this is the bug we found with an uninitialised variable in 1.8.12: https://github.com/fluent/fluent-bit/pull/4852

**Comment by lecaros** [comment]
hi @sophieyfang. I couldn't reproduce this. I've built it from tag v1.8.12 using your steps for VM creation.
I used the following file as input:

```
java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
        at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
        at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
        at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
        at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
        at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
        at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
        at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.base/java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
        at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
        at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:229)
        ... 12 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
```

This is the output I get from execution:
```
lecaros@debian11:~/repro-gh-4944$ sudo ~/fluent-bit/build/bin/fluent-bit -c fluent-bit.conf --parser fluent_bit_parser.conf
Fluent Bit v1.8.12
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/01 14:48:01] [ info] [engine] started (pid=55868)
[2022/03/01 14:48:01] [ info] [storage] version=1.1.5, initializing...
[2022/03/01 14:48:01] [ info] [storage] in-memory
[2022/03/01 14:48:01] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/01 14:48:01] [ info] [cmetrics] version=0.2.2
[2022/03/01 14:48:01] [ info] [input:tail:tail.0] multiline core started
[2022/03/01 14:48:01] [ info] [sp] stream processor started
[2022/03/01 14:48:01] [ info] [input:tail:tail.0] inotify_fs_add(): inode=406821 watch_fd=1 name=sample.log
[0] p1.files_1: [1646146081.768868548, {"message"=>"java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
", "logging.googleapis.com/logName"=>"files_1"}]
...
```

```
lecaros@debian11:~/repro-gh-4944$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

How have you built/installed fluent-bit?

**Comment by sophieyfang** [comment]
![D2FEA450-0A26-4F20-8BCF-8F3A4371D2E5](https://user-images.githubusercontent.com/8354694/156206097-134a2a64-38c3-406f-bbe3-a847d8d63b6a.png)
The file content doesn’t matter much. I also got it reproduced by tailing a mysql log file.

**Comment by lecaros** [comment]
Hi @sophieyfang, that's more than a month old (Jan 24th). However, I just built Fluent Bit from commit 9c2868fc841e1f0d9e0fd96a4bd8da164741906c, but wasn't able to reproduce either.

Is there any extra configuration you may have missed?

**Comment by lecaros** [comment]
The issue is reproducible using the opsagent only.
I tried to run cmake using https://github.com/GoogleCloudPlatform/ops-agent/blob/2.11.0/build.sh#L69-L71, but it's not reproducible either.
Not sure if it's related to the image used to build https://github.com/GoogleCloudPlatform/ops-agent/blob/2.11.0/Dockerfile
This doesn't seem to be an issue with fluent-bit but with the build made inside opsagent.

**Comment by patrick-stephens** [comment]
@lecaros @sophieyfang do you know if it's reproducible with our actual container image or published package for Debian 11?

There are a few deltas with the package selection here: https://github.com/fluent/fluent-bit/blob/887c29486de0c425726794f0addaebc99ab498fa/packaging/distros/debian/Dockerfile#L45-L51

It looks like you've ruled out the cmake configuration so the others are package selection or default compile flags - the issue I linked previously was an uninitialised variable which is nulled on Ubuntu but not other targets. 1.8.13 has the fix for that though now.

**Comment by patrick-stephens** [comment]
Sounds like it might have been https://github.com/fluent/fluent-bit/pull/4853 then. Are you ok to step up?

**Comment by sophieyfang** [comment]
Yes, as 1.8.13 is just released🎉
