### ISSUE TITLE
multiline parser missbehave on mixed logs

### ISSUE THREAD

**Issue by lecaros** [fluent/fluent-bit#4949]
## Bug Report

**Describe the bug**
When mixed langs (i.e., java + python) are consumed from a log file, the parser fails.

**To Reproduce**

- Example log message if applicable:
```
Jul 09, 2015 3:23:29 PM com.google.devtools.search.cloud.feeder.MakeLog: RuntimeException: Run from this message!
  at com.my.app.Object.do$a1(MakeLog.java:50)
  at java.lang.Thing.call(Thing.java:10)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start
    return get()
  File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get
    raise Exception('spam', 'eggs')
Exception: ('spam', 'eggs')
```
- Steps to reproduce the problem:

Run Fluent Bit 1.8.13 (Head from branch 1.8) with the following configuration:
```
[SERVICE]
    flush                 1
    log_level             info

[INPUT]
    name                  tail
    path                  java-python.log
    read_from_head        true
    multiline.parser      java,python


[OUTPUT]
    name                  stdout
    match                 *
```
**Expected behavior**
It should return only 2 log records.

```
Fluent Bit v1.8.13
* Copyright (C) 2015-2021 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/01 07:41:17] [ info] [engine] started (pid=7452)
[2022/03/01 07:41:17] [ info] [storage] version=1.1.6, initializing...
[2022/03/01 07:41:17] [ info] [storage] in-memory
[2022/03/01 07:41:17] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/01 07:41:17] [ info] [cmetrics] version=0.2.2
[2022/03/01 07:41:17] [ info] [input:tail:tail.0] multiline core started
[2022/03/01 07:41:17] [ info] [sp] stream processor started
[2022/03/01 07:41:17] [ info] [output:stdout:stdout.0] worker #0 started
[2022/03/01 07:41:17] [ info] [input:tail:tail.0] inotify_fs_add(): inode=32923930 watch_fd=1 name=java-python.log
[0] tail.0: [1646138477.091741543, {"log"=>"Jul 09, 2015 3:23:29 PM com.google.devtools.search.cloud.feeder.MakeLog: RuntimeException: Run from this message!
  at com.my.app.Object.do$a1(MakeLog.java:50)
  at java.lang.Thing.call(Thing.java:10)
"}]
[1] tail.0: [1646138477.091776481, {"log"=>"Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start
    return get()
  File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get
    raise Exception('spam', 'eggs')
Exception: ('spam', 'eggs')
"}]
[0] tail.0: [1646138477.091803571, {"log"=>"Exception: ('spam', 'eggs')
"}]
```
**Current behavior**
It returns 3 records

**Your Environment**
* Version used: built from tag v1.8.13 
* Configuration: see above
* Operating System and version: ubuntu
* Filters and plugins: None

**Comment by nokute78** [comment]
```
Exception: ('spam', 'eggs')
```
This line also matches below condition of java then it is queued as java string.
https://github.com/fluent/fluent-bit/blob/cc1280b161c0e9249deb9eee5b51dd5c86f6f299/src/multiline/flb_ml_parser_java.c#L61

https://rubular.com/r/cvzqowKR3QMmjc

**Comment by nokute78** [comment]
I sent a patch #4990 to modify regex.
https://rubular.com/r/YghT2SX435cL20

I want java expert to review it.

**Comment by lecaros** [comment]
Hi @nokute78,
Why is the line starting with Exception processed twice?
If it's part of the python multiline log, it should not be processed by any other parser, correct?

**Comment by nokute78** [comment]
@lecaros 
`flb_ml_append` checks if incoming line is matched twice.
It will not canceled even if one of them is matched. 

1. For `cont` cheking. [Block](https://github.com/fluent/fluent-bit/blob/v1.8.13/src/multiline/flb_ml.c#L597-L621)
2. For `start_state` checking. [Block](https://github.com/fluent/fluent-bit/blob/v1.8.13/src/multiline/flb_ml.c#L623-L642)

In this issue case, python parser matches `Exception: ('spam', 'eggs')` as case 1 and java parser matches as case 2.

I added below diff and confirmed.

## Diff

```diff
diff --git a/src/multiline/flb_ml.c b/src/multiline/flb_ml.c
index 3b8a86d37..3a93f9b94 100644
--- a/src/multiline/flb_ml.c
+++ b/src/multiline/flb_ml.c
@@ -698,6 +698,7 @@ int flb_ml_append(struct flb_ml *ml, uint64_t stream_id,
         if (lru_parser && lru_parser->last_stream_id == stream_id) {
             ret = ml_append_try_parser(lru_parser, lru_parser->last_stream_id, type,
                                        tm, buf, size, NULL);
+            printf("%s:ml_append_try_parser(1): ret=%d\n %s\n", lru_parser->ml_parser->name, ret, (char*)buf);
             if (ret == 0) {
                 processed = FLB_TRUE;
                 break;
@@ -724,6 +725,7 @@ int flb_ml_append(struct flb_ml *ml, uint64_t stream_id,
 
             ret = ml_append_try_parser(parser_i, stream_id, type,
                                        tm, buf, size, NULL);
+            printf("%s:ml_append_try_parser(2): ret=%d\n %s\n", parser_i->ml_parser->name, ret, (char*)buf);
             if (ret == 0) {
                 group->lru_parser = parser_i;
                 group->lru_parser->last_stream_id = stream_id;
```

## Log of `flb-it-multiline`

The point is below lines.

```
python:ml_append_try_parser(1): ret=0
 Exception: ('spam', 'eggs')

java:ml_append_try_parser(2): ret=0
 Exception: ('spam', 'eggs')
```

Full log:
```
Test issue_4949...                              
python:ml_append_try_parser(2): ret=0
 Traceback (most recent call last):

python:ml_append_try_parser(1): ret=0
   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__

java:ml_append_try_parser(2): ret=-1
   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__

python:ml_append_try_parser(1): ret=0
     rv = self.handle_exception(request, response, e)

java:ml_append_try_parser(2): ret=-1
     rv = self.handle_exception(request, response, e)

python:ml_append_try_parser(1): ret=0
   File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start

java:ml_append_try_parser(2): ret=-1
   File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start

python:ml_append_try_parser(1): ret=0
     return get()

java:ml_append_try_parser(2): ret=-1
     return get()

python:ml_append_try_parser(1): ret=0
   File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get

java:ml_append_try_parser(2): ret=-1
   File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get

python:ml_append_try_parser(1): ret=0
     raise Exception('spam', 'eggs')

java:ml_append_try_parser(2): ret=-1
     raise Exception('spam', 'eggs')


----- MULTILINE FLUSH -----
[0] [1647041991.423163210, {"log"=>"Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start
    return get()
  File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get
    raise Exception('spam', 'eggs')
Exception: ('spam', 'eggs')
"}]
----------- EOF -----------
python:ml_append_try_parser(1): ret=0
 Exception: ('spam', 'eggs')

java:ml_append_try_parser(2): ret=0
 Exception: ('spam', 'eggs')

java:ml_append_try_parser(1): ret=-1
 hello world, not multiline


----- MULTILINE FLUSH -----
[0] [1647041991.427390706, {"log"=>"Exception: ('spam', 'eggs')
"}]
----------- EOF -----------
[ FAILED ]
  multiline.c:402: Check val.via.str.size == len... failed
expected length: 27, received: 28
== received ==
"Exception: ('spam', 'eggs')
"

== expected ==
hello world, not multiline

```

**Comment by nokute78** [comment]
I think it is weird that a string matches two conditions.
Sometime should it be parsed as a python log, sometime should it be parsed as a java?
It seems to be difficult to describe such conditions. 

It is clear for user that the conditions are exclusive. 
Always a string can match at most one condition.

**Comment by lecaros** [comment]
@nokute78 the PR will need fine tunning to accept as a valid java logline the ones that start with:
Exception in thread

**Comment by nokute78** [comment]
@lecaros I think it works. Could you test the PR or share config and log?

Below is a result of the PR's unit test https://github.com/fluent/fluent-bit/pull/4990

https://github.com/fluent/fluent-bit/runs/5430684744?check_suite_focus=true#step:5:2118
```
Test parser_java...                             [0] [1647987065.684678761, {"log"=>"Exception in thread "main" java.lang.IllegalStateException: ..null property
"}]
[0] [1647987065.685462804, {"log"=>"     at com.example.myproject.Author.getBookIds(xx.java:38)
"}]
[0] [1647987065.685567981, {"log"=>"     at com.example.myproject.Bootstrap.main(Bootstrap.java:14)
"}]
[0] [1647987065.685649912, {"log"=>"Caused by: java.lang.NullPointerException
"}]
[0] [1647987065.685730450, {"log"=>"     at com.example.myproject.Book.getId(Book.java:22)
"}]
[0] [1647987065.685825187, {"log"=>"     at com.example.myproject.Author.getBookIds(Author.java:35)
"}]
[0] [1647987065.685981193, {"log"=>"     ... 1 more
"}]
[0] [1647987065.686085178, {"log"=>"single line
"}]

----- MULTILINE FLUSH -----
[0] [1647987065.684678761, {"log"=>"Exception in thread "main" java.lang.IllegalStateException: ..null property
     at com.example.myproject.Author.getBookIds(xx.java:38)
     at com.example.myproject.Bootstrap.main(Bootstrap.java:14)
Caused by: java.lang.NullPointerException
     at com.example.myproject.Book.getId(Book.java:22)
     at com.example.myproject.Author.getBookIds(Author.java:35)
     ... 1 more
"}]
----------- EOF -----------

----- MULTILINE FLUSH -----
[0] [1647987065.686085178, {"log"=>"single line
"}]
----------- EOF -----------
```

**Comment by lecaros** [comment]
Hi @nokute78. I only checked the regex in rubular (https://rubular.com/r/f6z5Zn72q11QRn). But you're right. It works from the PR. Thanks!
