### ISSUE TITLE
parser: segfault due to incorrect TZ in time_format

### ISSUE THREAD

**Issue by zhenyami** [fluent/fluent-bit#5041]
## Bug Report

**Describe the bug**
When Fluent Bit `[PARSER]` is configured to parse timestamps with TZ name but the timestamps don't actually include it, Fluent Bit will occasionally crash. 

For example, the timestamp looks like this: `2022-03-10 12:18:07,016Z`, and the `timestamp_format` is this: `%Y-%m-%d %H:%M:%S,%L%Z` (note that `%Z` is incorrect, `%z` should be used instead).

Fluent Bit correctly reports parsing errors in logs.
```
[2022/03/10 06:09:30] [error] [parser] cannot parse '2022-03-10 12:18:07,016Z' after %L
[2022/03/10 06:09:30] [ warn] [parser:wrong_time_format] invalid time format %Y-%m-%d %H:%M:%S,%L%Z for '2022-03-10 12:18:07,016Z'
```

However, after a while it also crashes:
```
[2022/03/10 06:09:30] [debug] [output:null:null.0] task_id=0 assigned to thread #0
#0  0x7fcdbaf617e1      in  ???() at s/x86_64/multiarch/strlen-sse2-pminub.S:38
#1  0x50a813            in  _find_string() at src/flb_strptime.c:737
#2  0x509ee9            in  _flb_strptime() at src/flb_strptime.c:494
#3  0x50914a            in  flb_strptime() at src/flb_strptime.c:138
#4  0x4f42b1            in  flb_parser_time_lookup() at src/flb_parser.c:1112
#5  0x4f5bd9            in  flb_parser_json_do() at src/flb_parser_json.c:184
#6  0x4f3be6            in  flb_parser_do() at src/flb_parser.c:914
#7  0x52cdbc            in  process_content() at plugins/in_tail/tail_file.c:462
#8  0x52f3fa            in  flb_tail_file_chunk() at plugins/in_tail/tail_file.c:1313
#9  0x526da4            in  in_tail_collect_pending() at plugins/in_tail/tail.c:90
#10 0x4cdaa8            in  flb_input_collector_fd() at src/flb_input.c:1203
#11 0x4e072d            in  flb_engine_handle_event() at src/flb_engine.c:437
#12 0x4e072d            in  flb_engine_start() at src/flb_engine.c:729
#13 0x4c1eca            in  flb_lib_worker() at src/flb_lib.c:626
#14 0x7fcdbc1bbe74      in  start_thread() at debug/glibc-2.17-c758a686/nptl/pthread_create.c:307
#15 0x7fcdbaef0a2c      in  ???() at s/unix/sysv/linux/x86_64/clone.S:111
#16 0xffffffffffffffff  in  ???() at ???:0
Aborted (core dumped)
```

##### core dump backtrace
```
(gdb) bt
#0  0x00007fcdbae283b7 in raise () from /lib64/libc.so.6
#1  0x00007fcdbae29aa8 in abort () from /lib64/libc.so.6
#2  0x000000000043e81b in flb_signal_handler (signal=11) at /jenkins/src/fluent-bit.c:596
#3  <signal handler called>
#4  0x00007fcdbaf617e1 in __strlen_sse2_pminub () from /lib64/libc.so.6
#5  0x000000000050a814 in _find_string (bp=0x7fcdb91fcae7 "Z", tgt=0x7fcdb91fc9cc, n1=0x7fcdbb1ba000 <tzname>, n2=0x0, c=2) at /jenkins/src/flb_strptime.c:737
#6  0x0000000000509eea in _flb_strptime (buf=0x7fcdb91fcae7 "Z", fmt=0x7fcdb961fdae "", tm=0x7fcdb91fcb90, initialize=1) at /jenkins/src/flb_strptime.c:494
#7  0x000000000050914b in flb_strptime (buf=0x7fcdb91fcae7 "Z", fmt=0x7fcdb961fdac "%Z", tm=0x7fcdb91fcb90) at /jenkins/src/flb_strptime.c:138
#8  0x00000000004f42b2 in flb_parser_time_lookup (time_str=0x7fcdb848f014 "2022-03-10 12:18:07,016Zes_opened\001\254files_closed", tsize=24, now=0, parser=0x7fcdb962c280, tm=0x7fcdb91fcb90, ns=0x7fcdb91fcd68) at /jenkins/src/flb_parser.c:1112
#9  0x00000000004f5bda in flb_parser_json_do (parser=0x7fcdb962c280, in_buf=0x7fcdb847be40 "{\"message\": \"test\", \"time\": \"2022-03-10 12:18:07,016Z\"}\n{\"message\": \"test\", \"time\": \"2022-03-10 12:18:07,016Z\"}\n{\"message\": \"test\", \"time\": \"2022-03-10 12:18:07,016Z\"}\n{\"message\": \"test\", \"time\": \"202"..., in_size=55, out_buf=0x7fcdb91fce78, out_size=0x7fcdb91fce70, out_time=0x7fcdb91fce50) at /jenkins/src/flb_parser_json.c:184
#10 0x00000000004f3be7 in flb_parser_do (parser=0x7fcdb962c280, buf=0x7fcdb847be40 "{\"message\": \"test\", \"time\": \"2022-03-10 12:18:07,016Z\"}\n{\"message\": \"test\", \"time\": \"2022-03-10 12:18:07,016Z\"}\n{\"message\": \"test\", \"time\": \"2022-03-10 12:18:07,016Z\"}\n{\"message\": \"test\", \"time\": \"202"..., length=55, out_buf=0x7fcdb91fce78, out_size=0x7fcdb91fce70, out_time=0x7fcdb91fce50) at /jenkins/src/flb_parser.c:914
#11 0x000000000052cdbd in process_content (file=0x7fcdb842e180, bytes=0x7fcdb91fcfa8) at /jenkins/plugins/in_tail/tail_file.c:462
#12 0x000000000052f3fb in flb_tail_file_chunk (file=0x7fcdb842e180) at /jenkins/plugins/in_tail/tail_file.c:1313
#13 0x0000000000526da5 in in_tail_collect_pending (ins=0x7fcdb960a000, config=0x7fcdb9611b40, in_context=0x7fcdb8461000) at /jenkins/plugins/in_tail/tail.c:90
#14 0x00000000004cdaa9 in flb_input_collector_fd (fd=23, config=0x7fcdb9611b40) at /jenkins/src/flb_input.c:1203
#15 0x00000000004e072e in flb_engine_handle_event (config=0x7fcdb9611b40, mask=1, fd=23) at /jenkins/src/flb_engine.c:437
#16 flb_engine_start (config=0x7fcdb9611b40) at /jenkins/src/flb_engine.c:729
#17 0x00000000004c1ecb in flb_lib_worker (data=0x7fcdb9610000) at /jenkins/src/flb_lib.c:626
#18 0x00007fcdbc1bbe75 in start_thread () from /lib64/libpthread.so.0
#19 0x00007fcdbaef0a2d in clone () from /lib64/libc.so.6
```

**To Reproduce**
- Example log message if applicable:
  ```
  {"message":"test", "time":"2022-03-10 12:18:07,016Z"}
  ```
- Steps to reproduce the problem:
  ##### Main config file, `fluent-bit.conf`
  ```
  [SERVICE]
      Flush           5
      Daemon          off
      Log_Level       debug
      Parsers_File    parsers.conf
  
  [INPUT]
      Name            tail
      Tag             test
      Path            test.log
      Parser          wrong_time_format
  
  [OUTPUT]
      Name            null
      Match           test
  ```
  
  ##### Parsers config file, `parsers.conf`
  ```
  [PARSER]
      Name            wrong_time_format
      Format          json
      Time_Key        time
      Time_Format     %Y-%m-%d %H:%M:%S,%L%Z
  ```

  ##### Bash script to write logs to the tailed log file, `test.log`
  ```bash
  c=1; while [ $c -le 1000000 ] ; do echo '{"message": "test", "time": "2022-03-10 12:18:07,016Z"}' >> test.log ; ((c++)) ; done
  ```

**Expected behavior**
Fluent Bit does not crash. It is expected that the timestamp cannot be parsed in this case but Fluent Bit should handle it gracefully and not cause a _segfault_.

**Your Environment**

* Version used: 1.9.0 (master) and 1.7.4
* Configuration: config included above
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version: Linux
* Filters and plugins: config included above above

**Additional context**
No additional context except this is not a high priority bug for us.

**Comment by ssi444** [comment]
I have the same problem. Version 1.9.2. I tried different versions of the date format, but I did not pick up a working one

invalid time format %Y-%m-%dT%H:%M:%S.%6N%z for '2022-04-22T12:10:01.287422Z'
invalid time format %Y-%m-%d %H:%M:%S.%6N%z for '2022-04-22T12:10:01.287422Z'

invalid time format %Y-%m-%dT%H:%M:%S.%6N%Z for '2022-04-22T12:10:01.287422Z'
invalid time format %Y-%m-%d %H:%M:%S.%6N%Z for '2022-04-22T12:10:01.287422Z'

invalid time format %Y-%m-%dT%H:%M:%S.%L%Z for '2022-04-22T12:10:01.287422Z'
invalid time format %Y-%m-%d %H:%M:%S.%L%Z for '2022-04-22T12:10:01.287422Z'


I tried it like this:
        Time_Format %Y-%m-%d %H:%M:%S.%L
        Time_Strict Off
but that didn't work either
does not occur
