### ISSUE TITLE
Websocket output with TLS doesn't work

### ISSUE THREAD

**Issue by rolandjitsu** [fluent/fluent-bit#5186]
## Bug Report

**Describe the bug**

I wanted to use the websocket output with a HTTPS connection using a self signed cert, but it seems like that doesn't work. Fluent-bit is just restarting itself at every flush interval, but I cannot find any logs explaining why.

On the server, I can see the following:
```
2022/03/25 14:20:25 http: TLS handshake error from 127.0.0.1:51594: EOF
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem: not doing anything special, just configured the websocket output with TLS enabled.

I've actually also tried running a simple server and the docker variant:
```go
package main

import (
	"crypto/tls"
	"flag"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	log "github.com/sirupsen/logrus"
	"golang.org/x/net/websocket"
)

var (
	certPath = flag.String("cert", "", "SSL cert path")
	keyPath  = flag.String("key", "", "SSL cert key path")
)

func main() {
	flag.Parse()

	e := echo.New()

	if *certPath == "" || *keyPath == "" {
		e.Logger.Fatalf("-cert and -key flags are required")
	}

	log.SetLevel(log.DebugLevel)

	e.Pre(middleware.RemoveTrailingSlash())
	e.Use(middleware.CORS())
	e.Use(middleware.Logger())
	e.Use(middleware.Gzip())
	e.Use(middleware.Recover())

	e.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "OK")
	})

	e.GET("/fb", func(c echo.Context) error {
		websocket.Handler(func(ws *websocket.Conn) {
			defer ws.Close()
			for {
				// Read
				msg := ""
				if err := websocket.Message.Receive(ws, &msg); err != nil {
					log.Error(err)
				}
				fmt.Printf("%s\n", msg)
			}
		}).ServeHTTP(c.Response(), c.Request())
		return nil
	})

	s := &http.Server{
		Addr:    "0.0.0.0:8000",
		Handler: e,
		TLSConfig: &tls.Config{
			MinVersion: tls.VersionTLS12,
		},
	}

	e.Logger.Fatal(s.ListenAndServeTLS(*certPath, *keyPath))
}
```

```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes -subj '/CN=localhost'
```

```bash
go run ./cmd/echoserver/. -cert ./cert.pem -key ./key.pem
```

```bash
docker run -ti fluent/fluent-bit -i cpu -o websocket://host.docker.internal:8000/fb -m '*' -p tls=true -p tls.verify=false
```

But getting:
```
* Copyright (C) 2015-2021 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/25 15:09:10] [ info] [engine] started (pid=1)
[2022/03/25 15:09:10] [ info] [storage] version=1.1.6, initializing...
[2022/03/25 15:09:10] [ info] [storage] in-memory
[2022/03/25 15:09:10] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/25 15:09:10] [ info] [cmetrics] version=0.3.0
[2022/03/25 15:09:10] [ info] [out_ws] we have following parameter /fb, host.docker.internal, 8000, 25
[2022/03/25 15:09:10] [ info] [sp] stream processor started
[2022/03/25 15:09:11] [engine] caught signal (SIGSEGV)
#0  0xffffb2834ad0      in  ???() at ???:0
```

But if I have a simple browser client connect and send data it works:
```js
const ws = new WebSocket("wss://localhost:8000/fb")

ws.onopen = function() {
  console.log('Connected')
}

setInterval(function() {
  ws.send('Hello, Server!');
}, 1000);
```

Note that using HTTP works just fine.

**Expected behavior**

Connecting the websocket output to a wss endpoint should work.

**Screenshots**

**Your Environment**

* Version used: v1.8.8
* Configuration:
```
[SERVICE]
  Flush                    5
  Grace                     1
  Daemon                    Off
  Log_Level                 debug
  Log_File                  fb.log

[INPUT]
  Name            cpu
  Alias           cpu_usage
  Tag             cpu

[OUTPUT]
  Name  websocket
  Match *
  Host  localhost
  Port  1323
  URI   /fb
  Format json
  tls on
  tls.verify                  off
```
* Environment name and version (e.g. Kubernetes? What version?):
```
~ uname -a
Linux raspberry-pi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

~ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

I'm building fb with these flags:
```
  cmake -DGNU_HOST=$GNU_HOST \
    -DHOST=$GNU_HOST \
    -DCMAKE_TOOLCHAIN_FILE=$CMAKE_CROSS_TOOLCHAIN_FILE \
    -DFLB_SHARED_LIB=No \
    -DFLB_EXAMPLES=No \
    -DFLB_JEMALLOC=No \
    -DFLB_HTTP_SERVER=Yes \
    -DFLB_LUAJIT=No \
    -DFLB_METRICS=Yes \
    -DFLB_PROXY_GO=Yes \
    -DFLB_RECORD_ACCESSOR=Yes \
    -DFLB_STREAM_PROCESSOR=Yes \
    -DFLB_FILTER_AWS=Off \
    -DFLB_FILTER_KUBERNETES=Off \
    -DFLB_FILTER_LUA=Off \
    -DFLB_FILTER_TENSORFLOW=Off \
    -DFLB_IN_DUMMY=Off \
    -DFLB_IN_FORWARD=Off \
    -DFLB_IN_HEAD=Off \
    -DFLB_IN_KMSG=Off \
    -DFLB_IN_MQTT=Off \
    -DFLB_IN_RANDOM=Off \
    -DFLB_IN_SERIAL=Off \
    -DFLB_IN_SYSLOG=Off \
    -DFLB_IN_STDIN=Off \
    -DFLB_OUT_AZURE=Off \
    -DFLB_OUT_AZURE_BLOB=Off \
    -DFLB_OUT_BIGQUERY=Off \
    -DFLB_OUT_CALYPTIA=Off \
    -DFLB_OUT_COUNTER=Off \
    -DFLB_OUT_DATADOG=Off \
    -DFLB_OUT_EXIT=Off \
    -DFLB_OUT_GELF=Off \
    -DFLB_OUT_HTTP=On \
    -DFLB_OUT_INFLUXDB=Off \
    -DFLB_OUT_NATS=Off \
    -DFLB_OUT_NRLOGS=Off \
    -DFLB_OUT_TCP=On \
    -DFLB_OUT_PLOT=Off \
    -DFLB_OUT_FILE=Off \
    -DFLB_OUT_TD=Off \
    -DFLB_OUT_SLACK=Off \
    -DFLB_OUT_SPLUNK=Off \
    -DFLB_OUT_STACKDRIVER=Off \
    -DFLB_OUT_NULL=Off \
    -DFLB_OUT_FLOWCOUNTER=Off \
    -DFLB_OUT_LOGDNA=Off \
    -DFLB_OUT_LOKI=Off \
    -DFLB_OUT_KAFKA=Off \
    -DFLB_OUT_KAFKA_REST=Off \
    -DFLB_OUT_CLOUDWATCH_LOGS=Off \
    -DFLB_OUT_KINESIS_FIREHOSE=Off \
    -DFLB_OUT_KINESIS_STREAMS=Off \
    -DFLB_OUT_PROMETHEUS_EXPORTER=Off \
    -DFLB_OUT_PROMETHEUS_REMOTE_WRITE=Off \
    -DFLB_OUT_S3=Off \
    -DFLB_OUT_WEBSOCKET=On \
    ../ && \
  make -j `nproc`
```

where the gnu and toolchain are configure for cross-compiling for arm.

If I remove the `tls on`, obviously, I get:
```
[2022/03/25 14:33:20] [debug] [output_ws] Websocket Server Response
Client sent an HTTP request to an HTTPS server.
```
so the server is not allowing HTTP.

**Comment by rolandjitsu** [comment]
I'm looking at https://github.com/fluent/fluent-bit/pull/1476 and I see the `we have following parameter /fb, host.d ...` is in `cb_ws_init`, so maybe somewhere after there's a memory issue.

**Comment by nokute78** [comment]
I think out_websocket doesn't support tls since it doesn't call `flb_tls_create`.
It causes SIGSEGV since `tls` is not initialized.

Backtrace is 
```
[2022/03/26 13:36:44] [ info] [fluent bit] version=1.9.1, commit=1b89b4711b, pid=65430
[2022/03/26 13:36:44] [ info] [storage] version=1.1.6, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/03/26 13:36:44] [ info] [cmetrics] version=0.3.0
[2022/03/26 13:36:46] [ info] [out_ws] we have following parameter /fb, localhost, 8000, 25
[2022/03/26 13:36:46] [ info] [sp] stream processor started

Thread 2 "flb-pipeline" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff79dc700 (LWP 65434)]
0x0000000000000625 in ?? ()
(gdb) bt
#0  0x0000000000000625 in ?? ()
#1  0x000055555563f3b3 in flb_tls_session_create (tls=0x555555e25ea0, u_conn=0x7ffff000b890, co=0x7ffff000b710)
    at /home/taka/git/fluent-bit/src/tls/flb_tls.c:334
#2  0x000055555564ba18 in flb_io_net_connect (u_conn=0x7ffff000b890, coro=0x7ffff000b710)
    at /home/taka/git/fluent-bit/src/flb_io.c:109
#3  0x000055555562801e in create_conn (u=0x7ffff000b3b0) at /home/taka/git/fluent-bit/src/flb_upstream.c:560
#4  0x0000555555628526 in flb_upstream_conn_get (u=0x7ffff000b3b0) at /home/taka/git/fluent-bit/src/flb_upstream.c:705
#5  0x00005555557153c1 in cb_ws_flush (event_chunk=0x7ffff000b670, out_flush=0x7ffff000b6c0, i_ins=0x555555e1fb20, 
    out_context=0x7ffff000b350, config=0x555555e0b300) at /home/taka/git/fluent-bit/plugins/out_websocket/websocket.c:207
#6  0x000055555560bec4 in output_pre_cb_flush () at /home/taka/git/fluent-bit/include/fluent-bit/flb_output.h:517
#7  0x0000555555bc9eab in co_init () at /home/taka/git/fluent-bit/lib/monkey/deps/flb_libco/amd64.c:117
#8  0x0000000000000000 in ?? ()
(gdb)
```

**Comment by muttanna2972** [comment]
Hit the exact same issue, Is this issue getting addressed?  or TLS is not supported in websocket output plugin?

**Comment by ginobiliwang** [comment]
@muttanna2972 , it is not supported yet.
