### ISSUE TITLE
Multiline parser does not working

### ISSUE THREAD

**Issue by merveyilmaz-netrd** [fluent/fluent-bit#5594]
## Bug Report

**Describe the bug**
I am trying to send logs to elastic search using multiline parser of input plugin but it seems like it does not work. Logs are splitting on the elastic search side..

**To Reproduce**
Here some parts of logs that i want to send:
```
2022-06-20 13:37:32,439 ERROR [org.jboss.aspects.tx.TxPolicy] javax.ejb.EJBTransactionRolledbackException: org.hibernate.MappingException: No Dialect mapping for JDBC type: -1
2022-06-20 13:37:32,439 ERROR [com.dfgfdf.fgffhfg.callsvr.registration.RegistrationAuditMgrBean] [registrationAudit] Exception during DB Steps
javax.ejb.EJBTransactionRolledbackException: org.hibernate.MappingException: No Dialect mapping for JDBC type: -1
        at org.jboss.ejb3.tx.Ejb3TxPolicy.handleInCallerTx(Ejb3TxPolicy.java:115)
        at org.jboss.aspects.tx.TxPolicy.invokeInCallerTx(TxPolicy.java:130)
        at org.jboss.aspects.tx.TxInterceptor$Required.invoke(TxInterceptor.java:194)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.aspects.tx.TxPropagationInterceptor.invoke(TxPropagationInterceptor.java:76)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.security.Ejb3AuthenticationInterceptorv2.invoke(Ejb3AuthenticationInterceptorv2.java:186)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.ENCPropagationInterceptor.invoke(ENCPropagationInterceptor.java:41)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.BlockContainerShutdownInterceptor.invoke(BlockContainerShutdownInterceptor.java:67)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.aspects.currentinvocation.CurrentInvocationInterceptor.invoke(CurrentInvocationInterceptor.java:67)
2022-06-20 13:37:32,441 ERROR [cdfgdfgdf.callsvr.registration.RegistrationAuditMgrBean] [auditReRegistration] Exception during DB Steps
.
.
.
```
here is the elastic search side:
![image](https://user-images.githubusercontent.com/82662465/174588388-b587693b-ae62-475f-9c70-cf7fb5a76c3a.png)

**Expected behavior**
Logs begin with timestamp. So “logs” that do not begin with a timestamp should be “merged” with the previous log.  

**Screenshots**

**Your Environment**

* Version used: 1.9.3 also tried same configuration with 1.9.2
* Configuration:

```
[SERVICE]
    Flush     1
    Daemon    off
    Log_Level info
    storage.path /opt/fbit
    storage.sync normal
    storage.backlog.mem_limit 250MB
    storage.max_chunks_up     512
    parsers_file parsers_multiline_server.conf

[INPUT]
    Name  tail
    Path  /var/log/java_server.log
    #Path /var/log/messages
    Tag   test
    storage.type filesystem
    Buffer_Max_Size 256KB
    Mem_Buf_Limit 512MB
    DB   /var/log/db.file
    DB.sync normal
    multiline.parser multiline-regex-server

[OUTPUT]
    Name  es
    Match test
    Index my-index
    Host  XX.XX.XX.XXX
    Port  9200
    Retry_Limit False
    TLS        Off
    TLS.Verify  Off
    Suppress_Type_Name On

[MULTILINE_PARSER]
    name          multiline-regex-server
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule      "start_state"   "/(\d+\-\d+\-\d+ \d+\:\d+\:\d+\,\d)(.*)/"  "cont"
    rule      "cont"          "/^\s+at.*/"                          "cont"
```

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: Centos7.9
* Operating System and version:
* Filters and plugins: Input and Es plugin.

**Additional context**

**Comment by nokute78** [comment]
There is no rule to match 
```
javax.ejb.EJBTransactionRolledbackException: org.hibernate.MappingException: No Dialect mapping for JDBC type: -1
```
You can test at https://rubular.com/ .

How about below config ?
```
[MULTILINE_PARSER]
    name          multiline-regex-server
    type          regex
    flush_timeout 1000
    #
    # Regex  rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
#    rule      "start_state"   "/(\d+\-\d+\-\d+ \d+\:\d+\:\d+\,\d)(.*)/"  "cont"
    rule      "start_state"   "/^[\d]+/"                       "cont"
    rule      "cont"          "/^[^\d]+/"                       "cont"
```

Output is 
```
[0] test: [1657409849.798949963, {"log"=>"2022-06-20 13:37:32,439 ERROR [org.jboss.aspects.tx.TxPolicy] javax.ejb.EJBTransactionRolledbackException: org.hibernate.MappingException: No Dialect mapping for JDBC type: -1
"}]
[1] test: [1657409849.798954722, {"log"=>"2022-06-20 13:37:32,439 ERROR [com.dfgfdf.fgffhfg.callsvr.registration.RegistrationAuditMgrBean] [registrationAudit] Exception during DB Steps
javax.ejb.EJBTransactionRolledbackException: org.hibernate.MappingException: No Dialect mapping for JDBC type: -1
        at org.jboss.ejb3.tx.Ejb3TxPolicy.handleInCallerTx(Ejb3TxPolicy.java:115)
        at org.jboss.aspects.tx.TxPolicy.invokeInCallerTx(TxPolicy.java:130)
        at org.jboss.aspects.tx.TxInterceptor$Required.invoke(TxInterceptor.java:194)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.aspects.tx.TxPropagationInterceptor.invoke(TxPropagationInterceptor.java:76)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.security.Ejb3AuthenticationInterceptorv2.invoke(Ejb3AuthenticationInterceptorv2.java:186)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.ENCPropagationInterceptor.invoke(ENCPropagationInterceptor.java:41)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.ejb3.BlockContainerShutdownInterceptor.invoke(BlockContainerShutdownInterceptor.java:67)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102)
        at org.jboss.aspects.currentinvocation.CurrentInvocationInterceptor.invoke(CurrentInvocationInterceptor.java:67)
"}]
[2] test: [1657409849.798977917, {"log"=>"2022-06-20 13:37:32,441 ERROR [cdfgdfgdf.callsvr.registration.RegistrationAuditMgrBean] [auditReRegistration] Exception during DB Steps
"}]
```
