### ISSUE TITLE
Parsing java stacktrace is not working for docker container logs in JSON format

### ISSUE THREAD

**Issue by venkatnpedada** [fluent/fluent-bit#5707]
## Bug Report

**Describe the bug**
Im trying to group the java stacktrace in single log with fluentbit. My java application is running in docker container and the container logs are stored in JSON format.

**To Reproduce**
- below are docker container logs in JSON format
```
{"log":"2021-04-30 19:45:54.630 [RI: 35a0fad6-fda1-43ad-986f-35240673f25d,testservice,41c3f8b11d622,0dea09294151] ERROR Exception in thread "main" java.lang.RuntimeException:\n","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"at com.myproject.module.MyProject.badMethod(MyProject.java:22\n","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)\n","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)\n","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"2021-04-30 19:45:54.630 [RI: 35a0fad6-fda1-43ad-986f-35240673f25d,testservice,41c3f8b11d622,0dea09294151] INFO Test message","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Configuration 
```
fluent-bit.conf

[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name            systemd
    Tag             host.*
    # all units?
    #Systemd_Filter  _SYSTEMD_UNIT=docker.service

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /var/log/fluent-bit/docker.db
    Mem_Buf_Limit     5MB
    Refresh_Interval  10
    # Re-combine split lines
    Docker_Mode       On
    Ignore_Older      24h
    Skip_Long_Lines   On

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Record ip ${HOST_IP}

[FILTER]
    Name parser
    Match docker.*
    Key_Name log
    Parser java-application
    Reserve_Data On
    Preserve_Key On

[OUTPUT]
    Name          forward
    Match         *
    Upstream      fluentd-upstream.conf
    Self_Hostname {{ env "HOSTNAME" }}
```

```
parsers.conf

[PARSER]
    Name java-application
    Format regex
    Regex ^(\d{4}-\d{2}-\d{2}\s+\d{2}\:\d{2}\:\d{2}.\d+)\s+\[RI:\s+(?<reqid>[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})(.*)\](.*?)( (?<latency>\d+) ?ms)?$
    Types latency:integer
```

- Steps to reproduce the problem:

**Expected behavior**
fluent-bit should able to merge the java stacktrace even the actual raw log file in JSON format.

**Your Environment**

* Version used: 1.9.5
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Docker 20.10.8 + Kubernetes 1.22
* Server type and version: Linux
* Operating System and version: 
* Filters and plugins: 

**Additional context**

We are using same configuration for all docker containers Ex: k8s and non-k8s docker containers which means the log formats will be different for different containers. The java applications are running only in k8s.

**Comment by nandikatlakishore** [comment]
Facing similar issue,
 https://github.com/fluent/fluent-bit/issues/5673
