### ISSUE TITLE
Multiline failure

### ISSUE THREAD

**Issue by kakaNo1** [fluent/fluent-bit#5851]
## Bug Report

I configured multiple rows, but it was not successful
log：
```
[2022-08-08 06:37:32,193] {./ocean/api_1_0/errors.py:104} <2127> (service) ERROR - Internal Server Error
Traceback (most recent call last):
File "./xxx/models/xxx.py", line 799, in run
rets = self.action.do(*args, **kwargs)
File "./xxx/utils/perf.py", line 55, in decorator
return measured(*args, **kwargs)
File "./xxx/models/workflow.py", line 269, in do
deploy_agg, projects, running_aggs, draft_aggs
File "./xxx/models/xxx.py", line 449, in _deploy_to_multiple_workspaces
target_project,
File "./xxx/models/xx.py", line 492, in _push_step_to_multiple_workspace
project, flow_name, exist_draft_flow
File "./xxx/models/xxx.py", line 523, in _create_draft_flow_if_not_exist
schedule_id=0,
File "./xxx/models/xxx.py", line 957, in create_with_template
if kwargs['xxx'] is False: # only create empty folder
KeyError: 'xxx'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/site-packages/xxx/__init__.py", line 477, in wrapper
resp = resource(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/xxx/views.py", line 84, in view
return self.dispatch_request(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/xxx/__init__.py", line 587, in dispatch_request
resp = meth(*args, **kwargs)
File "./xxx/api_1_0/auth.py", line 79, in decorator_function
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 679, in wrapper
resp = f(*args, **kwargs)
File "./xxx/api_1_0/workflow.py", line 46, in post
new_agg_ids = workflow.run()
File "./xxx/models/workflow.py", line 811, in run
message, agg_ids=self.action.agg_ids, action=self.action_name
ocean.exceptions.ActionServerError: 'is_flow'
```
version ： fluent/fluent-bit:1.8.15
fluent-bit-config ：
```
filter-kubernetes.conf
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix     kube.var.log.containers.
    Merge_Log           On
    Merge_Log_Key          log_proces
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Buffer_Size  512k

[FILTER]
    Name   multiline
    Match   *
    multiline.parser multiline_python
    multiline.key_content log

fluent-bit.conf
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

@INCLUDE input-kubernetes.conf
@INCLUDE filter-kubernetes.conf
@INCLUDE output-elasticsearch.conf

input-kubernetes.conf
[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    parser  docker, cri
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     100MB
    Skip_Long_Lines   On
    Refresh_Interval  10

output-elasticsearch.conf
[OUTPUT]
    Name            es
    Match           *
    Host            elasticsearch
    Port            9200
    Logstash_Format On
    Replace_Dots    On
    Retry_Limit     False

parsers.conf
[MULTILINE_PARSER]
    name          multiline_python
    type          regex
    key_content   log
    flush_timeout 2000
    trace_error   on
    # rules   |   state name   | regex pattern                   | next state
    # --------|----------------|---------------------------------------------
    rule       "start_state"    "/^(\[\d{4}-\d{1,2}-\d{1,2}.*\].*)/"       "cont"
    rule       "cont"         "/^((?!\[\d{4}\-\d{1,2}\-\d{1,2}.*\]).*)/"   "cont"
```

es out ： 
```
Aug 8, 2022 @ 14:53:49.393	[2022-08-08 06:53:49,392] {./ocean/api_1_0/errors.py:104} <2127> (service) ERROR - Internal Server Error
Aug 8, 2022 @ 14:53:49.393	Traceback (most recent call last):
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/models/workflow.py", line 799, in run
Aug 8, 2022 @ 14:53:49.393	    rets = self.action.do(*args, **kwargs)
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/utils/perf.py", line 55, in decorator
Aug 8, 2022 @ 14:53:49.393	    return measured(*args, **kwargs)
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/models/workflow.py", line 269, in do
Aug 8, 2022 @ 14:53:49.393	    deploy_agg, projects, running_aggs, draft_aggs
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/models/workflow.py", line 449, in _deploy_to_multiple_workspaces
Aug 8, 2022 @ 14:53:49.393	    target_project,
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/models/workflow.py", line 492, in _push_step_to_multiple_workspace
Aug 8, 2022 @ 14:53:49.393	    project, flow_name, exist_draft_flow
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/models/workflow.py", line 523, in _create_draft_flow_if_not_exist
Aug 8, 2022 @ 14:53:49.393	    schedule_id=0,
Aug 8, 2022 @ 14:53:49.393	  File "./ocean/models/agg.py", line 957, in create_with_template
Aug 8, 2022 @ 14:53:49.393	    if kwargs['is_flow'] is False:  # only create empty folder
Aug 8, 2022 @ 14:53:49.393	KeyError: 'is_flow'
Aug 8, 2022 @ 14:53:49.393	
Aug 8, 2022 @ 14:53:49.393	During handling of the above exception, another exception occurred:
Aug 8, 2022 @ 14:53:49.393	
Aug 8, 2022 @ 14:53:49.393	Traceback (most recent call last):
```

**Comment by kakaNo1** [comment]
Kubernetes pod annotations:

kubernetes.annotations.fluentbit_io/parser: api-log

**Comment by patrick-stephens** [comment]
The 1.8 releases are EOL so can you confirm this issue is still present in 1.9.6?

**Comment by kakaNo1** [comment]
@patrick-stephens  thanks ，I changed it to 1.9.6. It works normally

**Comment by patrick-stephens** [comment]
OK, I'll close then as sounds like it is resolved.
