### ISSUE TITLE
Segfault on remove from empty list

### ISSUE THREAD

**Issue by bgaifullin** [fluent/fluent-bit#5889]
## Bug Report

**Describe the bug**

stack trace
```
(gdb) bt
#0  0x00007f39e851e00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f39e84fd859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004a51ec in flb_signal_handler (signal=<optimized out>) at /-S/contrib/tools/fluent-bit-full/src/fluent-bit.c:581
#3  <signal handler called>
#4  __mk_list_del (prev=0x0, next=0x0) at /-S/contrib/tools/fluent-bit-full/lib/monkey/include/monkey/mk_core/mk_list.h:87
#5  mk_list_del (entry=0x7f39e4190a00) at /-S/contrib/tools/fluent-bit-full/lib/monkey/include/monkey/mk_core/mk_list.h:93
#6  chunk_state_sync (ch=0x7f39e41909c0) at /-S/contrib/tools/fluent-bit-full/lib/chunkio/src/cio_chunk.c:506
#7  cio_chunk_up_force (ch=0x7f39e41909c0) at /-S/contrib/tools/fluent-bit-full/lib/chunkio/src/cio_chunk.c:560
#8  0x0000000000c5717f in input_chunk_get (in=0x7f39e7e49000, tag=0x7f39e4387118 "tail.0", tag_len=6, chunk_size=224134, set_down=<optimized out>) at /home/bulatman/arc/arcadia/contrib/tools/fluent-bit-full/src/flb_input_chunk.c:1127
#9  input_chunk_append_raw (in=0x7f39e7e49000, n_records=359, tag=0x7f39e4387118 "tail.0", tag_len=<optimized out>, buf=0x7f39e4255e40, buf_size=224134) at /home/bulatman/arc/arcadia/contrib/tools/fluent-bit-full/src/flb_input_chunk.c:1408
#10 0x0000000000c57965 in flb_input_chunk_append_raw2 (in=0x0, records=139886675856872, tag=0x1000 <error: Cannot access memory at address 0x1000>, tag_len=0, buf=0x0, buf_size=139886675856432)
    at /home/bulatman/arc/arcadia/contrib/tools/fluent-bit-full/src/flb_input_chunk.c:1600
#11 0x000000000074e38c in process_content (file=<optimized out>, bytes=<optimized out>) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail_file.c:536
#12 flb_tail_file_chunk (file=<optimized out>, file@entry=0x7f39e432fb80) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail_file.c:1315
#13 0x00000000005ccba8 in in_tail_collect_event (file=file@entry=0x7f39e432fb80, config=config@entry=0x7f39e7e0c680) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail.c:310
#14 0x000000000074f760 in tail_fs_event (ins=<optimized out>, config=<optimized out>, in_context=0x7f39e6c2e000) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail_fs_inotify.c:267
#15 0x0000000000c551da in flb_input_collector_fd (fd=<optimized out>, fd@entry=43, config=config@entry=0x7f39e7e0c680) at /-S/contrib/tools/fluent-bit-full/src/flb_input.c:1210
#16 0x0000000000c34599 in flb_engine_handle_event (fd=43, config=0x7f39e7e0c680, mask=<optimized out>) at /-S/contrib/tools/fluent-bit-full/src/flb_engine.c:440
#17 flb_engine_start (config=<optimized out>, config@entry=0x7f39e7e0c680) at /-S/contrib/tools/fluent-bit-full/src/flb_engine.c:763
#18 0x0000000000c5956d in flb_lib_worker (data=0x7f39e7e0b000) at /-S/contrib/tools/fluent-bit-full/src/flb_lib.c:626
#19 0x00007f39e86d5609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007f39e85fa133 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by nokute78** [comment]
Note: A pull request was sent to chunkio project.
https://github.com/calyptia/chunkio/pull/87
