### ISSUE TITLE
Regex parser not supporting multiline

### ISSUE THREAD

**Issue by BlackJohnny** [fluent/fluent-bit#6251]
## Bug Report

**Describe the bug**

I have the following scenario:

```mermaid
graph LR;
    INPUT-->FILTER_MULTILINE;
    FILTER_MULTILINE-->FILTER_PARSER;
    FILTER_PARSER-->OUTPUT
```

The multi-line filter is used to concatenate the log lines and the result is the following:
```
[0] TAG: [1666333150.612081885, {"log"=>"2022-10-21 06:07:45.137, ERROR, service.develop, 36, (<ApiErrorCodes.E_INVALID_INPUT: 550>, 'Invalid entity id 579061861432968382')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/service/flask_call.py", line 176, in view_func
    result = api_func(**arg)
  File "/usr/local/lib/python3.7/site-packages/service/api/entity_api.py", line 50, in get
    return Service.get(self._context, id)
  raise ApiException(ApiErrorCodes.E_INVALID_INPUT, f"Invalid entity id {id}")
.....
", "stream"=>"stdout", "time"=>"2022-10-21T06:19:10.590391647Z"}]
```
From this point, before sending the logs to the output, I would like to extract the fields from the **log** key with a regular expression parser and get a result like bellow, but the FILTER_PARSER fails as it does not support the **`m flag`**:

```
[0] TAG: [1666332665.123000000, {"time"=>"2022-10-21 06:07:45.137", "type"=>"ERROR",
"service"=>"service.develop", "tid"=>"36",
"log_python"=>"(<ApiErrorCodes.E_INVALID_INPUT: 550>, 'Invalid entity id 579061861432968382')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/service/flask_call.py", line 176, in view_func
    result = api_func(**arg)
  File "/usr/local/lib/python3.7/site-packages/service/api/entity_api.py", line 50, in get
    return Service.get(self._context, id)
  raise ApiException(ApiErrorCodes.E_INVALID_INPUT, f"Invalid entity id {id}")
.....
"}]
```
Fluent bit configuration
```
# fluentbit.conf
[OUTPUT]
    Name                    stdout
    Match                   *

[INPUT]
    Name                    tail
    Tag                     TAG
    Path                    /var/log/containers/service-*.log
    DB                      /var/fluent-bit/state/flb_services.db
    Mem_Buf_Limit           50MB
    Skip_Long_Lines         On
    Refresh_Interval        10
    Rotate_Wait             30
    storage.type            filesystem
    Read_from_Head          Off

[FILTER]
    Name                    multiline
    Match                   TAG
    multiline.key_content   log
    multiline.parser        python, multiline_python

[FILTER]
    Name                    parser
    Key_Name                log
    Match                   TAG
    Parser                  service-parser

# parsers.conf
[PARSER]
    Name                docker-log
    Format              json

[PARSER]
    Name                service-parser
    Format              regex
    Regex               /?<time>(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d+)), (?<type>[^,]*), (?<service>[^,]*), (?<tid>[^,]*), (?<log_python>.*)/m
    Time_Key            time
    Time_Format         %Y-%m-%d %H:%M:%S.%L
    Time_Keep           On

[MULTILINE_PARSER]
    Name                multiline_python
    type                regex
    parser              docker-log
    key_content         log
    flush_timeout       1000
    rule                "start_state"   "/^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.*)/"    "cont"
    rule                "cont"          "/^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).+/"  "cont"
```

**Expected behavior**
To allow the regex to capture multiline

**Your Environment**

* Version used: 1.9.9

Is there another way to accomplish my goal and I miss it? Thank you!

**Comment by lecaros** [comment]
I'd say you don't need the `m` flag.
Also, your regex seems wrong; you're missing a `(` at the beginning.
Share the config, log sample, and actual output. It's a good idea to use the bug report template.

**Comment by BlackJohnny** [comment]
> I'd say you don't need the `m` flag. Also, your regex seems wrong; you're missing a `(` at the beginning. Share the config, log sample, and actual output. It's a good idea to use the bug report template.
Thanks for the answer!

Yes, the `(` is a copy paste issue, and yes i can use `(?<log_python>(\S|\s)*)` to achieve multiline however ...

Anyway, I have checked the fluentbit code and it is not actually a bug. The code simply does not parse the expression as a full regex pattern so I suppose it is just not supporting this.

I will close this issue. Best regards!
