### ISSUE TITLE
Multiline parser goes not work for CRI Golang logs

### ISSUE THREAD

**Issue by pfrcks** [fluent/fluent-bit#6355]
## Bug Report

**Describe the bug**

Trying to use multiline parsing for golang stacktrace from container logs. CRI parsing works but unable to get golang multiline parser to work

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
Input container log /opt/test.log:

2022-11-07T23:41:33.876305182Z stderr F 2022-11-07 23:41:33.875986 TRACE /app/main.go:61 main.testTime [] test Time (cost: 200.04504ms)
2022-11-07T23:41:34.276409461Z stderr F 2022-11-07 23:41:34.276252 TRACE /app/main.go:66 main.testTime [] test Timef (cost: 400.181181ms)
2022-11-07T23:41:34.276480862Z stderr F 2022-11-07 23:41:34.276301 INFO  /app/main.go:71 main.testLog [] test Log
2022-11-07T23:41:34.276487763Z stderr F 2022-11-07 23:41:34.276311 WARN  /app/main.go:24 main.main [] test Logf: 1
2022-11-07T23:41:34.276493863Z stderr F 2022-11-07 23:41:34.276316 WARN  /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:171 github.com/gxlog/gxlog/logger.(*Logger).Logf [] test Logf: -1
2022-11-07T23:41:34.276497763Z stderr F 2022-11-07 23:41:34.276323 ERROR /app/main.go:78 main.testLogError [] an error
2022-11-07T23:41:34.276501463Z stderr F 2022-11-07 23:41:34.276331 ERROR /app/main.go:83 main.testLogErrorf [] another error
2022-11-07T23:41:44.276924621Z stderr F 2022-11-07 23:41:44.276525 TRACE /app/main.go:32 main.testLevel [] test Trace
2022-11-07T23:41:44.276978322Z stderr F 2022-11-07 23:41:44.276566 TRACE /app/main.go:33 main.testLevel [] test Tracef
2022-11-07T23:41:44.276984422Z stderr F 2022-11-07 23:41:44.276572 DEBUG /app/main.go:34 main.testLevel [] test Debug
2022-11-07T23:41:44.276988722Z stderr F 2022-11-07 23:41:44.276578 DEBUG /app/main.go:35 main.testLevel [] test Debugf
2022-11-07T23:41:44.276992922Z stderr F 2022-11-07 23:41:44.276583 INFO  /app/main.go:36 main.testLevel [] test Info
2022-11-07T23:41:44.276996922Z stderr F 2022-11-07 23:41:44.276589 INFO  /app/main.go:37 main.testLevel [] test Infof
2022-11-07T23:41:44.277001022Z stderr F 2022-11-07 23:41:44.276594 WARN  /app/main.go:38 main.testLevel [] test Warn
2022-11-07T23:41:44.277004722Z stderr F 2022-11-07 23:41:44.276607 WARN  /app/main.go:39 main.testLevel [] test Warnf
2022-11-07T23:41:44.277008522Z stderr F 2022-11-07 23:41:44.276613 ERROR /app/main.go:40 main.testLevel [] test Error
2022-11-07T23:41:44.277012222Z stderr F 2022-11-07 23:41:44.276618 ERROR /app/main.go:41 main.testLevel [] test Errorf
2022-11-07T23:41:44.277015922Z stderr F 2022-11-07 23:41:44.276645 FATAL /app/main.go:43 main.testLevel [] test Fatal
2022-11-07T23:41:44.277020622Z stderr F goroutine 1 [running]:
2022-11-07T23:41:44.277025122Z stderr F runtime/debug.Stack(0xc00007a000, 0x1, 0x6)
2022-11-07T23:41:44.277029723Z stderr F         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
2022-11-07T23:41:44.277033623Z stderr F github.com/gxlog/gxlog/logger.(*Logger).Log(0xc00007a000, 0x1, 0x6, 0xc00047ce58, 0x1, 0x1)
2022-11-07T23:41:44.277038023Z stderr F         /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:149 +0xc6
2022-11-07T23:41:44.277041923Z stderr F github.com/gxlog/gxlog/logger.(*Logger).Fatal(...)
2022-11-07T23:41:44.277045723Z stderr F         /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:106
2022-11-07T23:41:44.277050323Z stderr F main.testLevel()
2022-11-07T23:41:44.277057723Z stderr F         /app/main.go:43 +0x505
2022-11-07T23:41:44.277061623Z stderr F main.main()
2022-11-07T23:41:44.277065523Z stderr F         /app/main.go:21 +0x36
2022-11-07T23:41:44.277069223Z stderr F 2022-11-07 23:41:44.276663 FATAL /app/main.go:44 main.testLevel [] test Fatalf
2022-11-07T23:41:44.277073023Z stderr F goroutine 1 [running]:
2022-11-07T23:41:44.277076823Z stderr F runtime/debug.Stack(0x0, 0x503b68, 0x2)
2022-11-07T23:41:44.277080623Z stderr F         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
2022-11-07T23:41:44.277086824Z stderr F github.com/gxlog/gxlog/logger.(*Logger).Logf(0xc00007a000, 0x1, 0x6, 0xc00001ac70, 0x5, 0xc00047ce48, 0x1, 0x1)
2022-11-07T23:41:44.277090924Z stderr F         /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:168 +0x14c
2022-11-07T23:41:44.277094724Z stderr F github.com/gxlog/gxlog/logger.(*Logger).Fatalf(...)
2022-11-07T23:41:44.277098724Z stderr F         /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:111
2022-11-07T23:41:44.277116924Z stderr F main.testLevel()
2022-11-07T23:41:44.277120524Z stderr F         /app/main.go:44 +0x578
2022-11-07T23:41:44.277123824Z stderr F main.main()
2022-11-07T23:41:44.277127624Z stderr F         /app/main.go:21 +0x36
2022-11-07T23:41:44.4770611Z stderr F 2022-11-07 23:41:44.476872 TRACE /app/main.go:61 main.testTime [] test Time (cost: 200.17378ms)
2022-11-07T23:41:44.877315559Z stderr F 2022-11-07 23:41:44.877119 TRACE /app/main.go:66 main.testTime [] test Timef (cost: 400.171457ms)
2022-11-07T23:41:44.87735876Z stderr F 2022-11-07 23:41:44.877155 INFO  /app/main.go:71 main.testLog [] test Log
2022-11-07T23:41:44.87736396Z stderr F 2022-11-07 23:41:44.877176 WARN  /app/main.go:24 main.main [] test Logf: 1
2022-11-07T23:41:44.87737246Z stderr F 2022-11-07 23:41:44.877181 WARN  /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:171 github.com/gxlog/gxlog/logger.(*Logger).Logf [] test Logf: -1
2022-11-07T23:41:44.877376761Z stderr F 2022-11-07 23:41:44.877188 ERROR /app/main.go:78 main.testLogError [] an error
2022-11-07T23:41:44.877380461Z stderr F 2022-11-07 23:41:44.877196 ERROR /app/main.go:83 main.testLogErrorf [] another error
```
- Steps to reproduce the problem:

```
Fluent-bit config file
[SERVICE]
    flush                 1
    # parsers_file          parsers_multiline.conf

[INPUT]
    name                  tail
    Path                  /opt/test.log
    read_from_head        true

[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      docker,cri,go,java
#    multiline.parser      docker,go, java
#    multiline.parser      docker, go, multiline-regex-test
#    multiline.parser      go, multiline-regex-test

[OUTPUT]
    name                  stdout
    match                 *
```

**Expected behavior**

Go multiline logs parsed in one entry. Instead I am seeing

```
[12715] tail.0: [1667864493.876305182, {"time"=>"2022-11-07T23:41:33.876305182Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:33.875986 TRACE /app/main.go:61 main.testTime [] test Time (cost: 200.04504ms)"}]
[12716] tail.0: [1667864494.276409461, {"time"=>"2022-11-07T23:41:34.276409461Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:34.276252 TRACE /app/main.go:66 main.testTime [] test Timef (cost: 400.181181ms)"}]
[12717] tail.0: [1667864494.276480862, {"time"=>"2022-11-07T23:41:34.276480862Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:34.276301 INFO  /app/main.go:71 main.testLog [] test Log"}]
[12718] tail.0: [1667864494.276487763, {"time"=>"2022-11-07T23:41:34.276487763Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:34.276311 WARN  /app/main.go:24 main.main [] test Logf: 1"}]
[12719] tail.0: [1667864494.276493863, {"time"=>"2022-11-07T23:41:34.276493863Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:34.276316 WARN  /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:171 github.com/gxlog/gxlog/logger.(*Logger).Logf [] test Logf: -1"}]
[12720] tail.0: [1667864494.276497763, {"time"=>"2022-11-07T23:41:34.276497763Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:34.276323 ERROR /app/main.go:78 main.testLogError [] an error"}]
[12721] tail.0: [1667864494.276501463, {"time"=>"2022-11-07T23:41:34.276501463Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:34.276331 ERROR /app/main.go:83 main.testLogErrorf [] another error"}]
[12722] tail.0: [1667864504.276924621, {"time"=>"2022-11-07T23:41:44.276924621Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276525 TRACE /app/main.go:32 main.testLevel [] test Trace"}]
[12723] tail.0: [1667864504.276978322, {"time"=>"2022-11-07T23:41:44.276978322Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276566 TRACE /app/main.go:33 main.testLevel [] test Tracef"}]
[12724] tail.0: [1667864504.276984422, {"time"=>"2022-11-07T23:41:44.276984422Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276572 DEBUG /app/main.go:34 main.testLevel [] test Debug"}]
[12725] tail.0: [1667864504.276988722, {"time"=>"2022-11-07T23:41:44.276988722Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276578 DEBUG /app/main.go:35 main.testLevel [] test Debugf"}]
[12726] tail.0: [1667864504.276992922, {"time"=>"2022-11-07T23:41:44.276992922Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276583 INFO  /app/main.go:36 main.testLevel [] test Info"}]
[12727] tail.0: [1667864504.276996922, {"time"=>"2022-11-07T23:41:44.276996922Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276589 INFO  /app/main.go:37 main.testLevel [] test Infof"}]
[12728] tail.0: [1667864504.277001022, {"time"=>"2022-11-07T23:41:44.277001022Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276594 WARN  /app/main.go:38 main.testLevel [] test Warn"}]
[12729] tail.0: [1667864504.277004722, {"time"=>"2022-11-07T23:41:44.277004722Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276607 WARN  /app/main.go:39 main.testLevel [] test Warnf"}]
[12730] tail.0: [1667864504.277008522, {"time"=>"2022-11-07T23:41:44.277008522Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276613 ERROR /app/main.go:40 main.testLevel [] test Error"}]
[12731] tail.0: [1667864504.277012222, {"time"=>"2022-11-07T23:41:44.277012222Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276618 ERROR /app/main.go:41 main.testLevel [] test Errorf"}]
[12732] tail.0: [1667864504.277015922, {"time"=>"2022-11-07T23:41:44.277015922Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276645 FATAL /app/main.go:43 main.testLevel [] test Fatal"}]
[12733] tail.0: [1667864504.277020622, {"time"=>"2022-11-07T23:41:44.277020622Z", "stream"=>"stderr", "_p"=>"F", "log"=>"goroutine 1 [running]:"}]
[12734] tail.0: [1667864504.277025122, {"time"=>"2022-11-07T23:41:44.277025122Z", "stream"=>"stderr", "_p"=>"F", "log"=>"runtime/debug.Stack(0xc00007a000, 0x1, 0x6)"}]
[12735] tail.0: [1667864504.277029723, {"time"=>"2022-11-07T23:41:44.277029723Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /usr/local/go/src/runtime/debug/stack.go:24 +0x9d"}]
[12736] tail.0: [1667864504.277033623, {"time"=>"2022-11-07T23:41:44.277033623Z", "stream"=>"stderr", "_p"=>"F", "log"=>"github.com/gxlog/gxlog/logger.(*Logger).Log(0xc00007a000, 0x1, 0x6, 0xc00047ce58, 0x1, 0x1)"}]
[12737] tail.0: [1667864504.277038023, {"time"=>"2022-11-07T23:41:44.277038023Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:149 +0xc6"}]
[12738] tail.0: [1667864504.277041923, {"time"=>"2022-11-07T23:41:44.277041923Z", "stream"=>"stderr", "_p"=>"F", "log"=>"github.com/gxlog/gxlog/logger.(*Logger).Fatal(...)"}]
[12739] tail.0: [1667864504.277045723, {"time"=>"2022-11-07T23:41:44.277045723Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:106"}]
[12740] tail.0: [1667864504.277050323, {"time"=>"2022-11-07T23:41:44.277050323Z", "stream"=>"stderr", "_p"=>"F", "log"=>"main.testLevel()"}]
[12741] tail.0: [1667864504.277057723, {"time"=>"2022-11-07T23:41:44.277057723Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /app/main.go:43 +0x505"}]
[12742] tail.0: [1667864504.277061623, {"time"=>"2022-11-07T23:41:44.277061623Z", "stream"=>"stderr", "_p"=>"F", "log"=>"main.main()"}]
[12743] tail.0: [1667864504.277065523, {"time"=>"2022-11-07T23:41:44.277065523Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /app/main.go:21 +0x36"}]
[12744] tail.0: [1667864504.277069223, {"time"=>"2022-11-07T23:41:44.277069223Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.276663 FATAL /app/main.go:44 main.testLevel [] test Fatalf"}]
[12745] tail.0: [1667864504.277073023, {"time"=>"2022-11-07T23:41:44.277073023Z", "stream"=>"stderr", "_p"=>"F", "log"=>"goroutine 1 [running]:"}]
[12746] tail.0: [1667864504.277076823, {"time"=>"2022-11-07T23:41:44.277076823Z", "stream"=>"stderr", "_p"=>"F", "log"=>"runtime/debug.Stack(0x0, 0x503b68, 0x2)"}]
[12747] tail.0: [1667864504.277080623, {"time"=>"2022-11-07T23:41:44.277080623Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /usr/local/go/src/runtime/debug/stack.go:24 +0x9d"}]
[12748] tail.0: [1667864504.277086824, {"time"=>"2022-11-07T23:41:44.277086824Z", "stream"=>"stderr", "_p"=>"F", "log"=>"github.com/gxlog/gxlog/logger.(*Logger).Logf(0xc00007a000, 0x1, 0x6, 0xc00001ac70, 0x5, 0xc00047ce48, 0x1, 0x1)"}]
[12749] tail.0: [1667864504.277090924, {"time"=>"2022-11-07T23:41:44.277090924Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:168 +0x14c"}]
[12750] tail.0: [1667864504.277094724, {"time"=>"2022-11-07T23:41:44.277094724Z", "stream"=>"stderr", "_p"=>"F", "log"=>"github.com/gxlog/gxlog/logger.(*Logger).Fatalf(...)"}]
[12751] tail.0: [1667864504.277098724, {"time"=>"2022-11-07T23:41:44.277098724Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:111"}]
[12752] tail.0: [1667864504.277116924, {"time"=>"2022-11-07T23:41:44.277116924Z", "stream"=>"stderr", "_p"=>"F", "log"=>"main.testLevel()"}]
[12753] tail.0: [1667864504.277120524, {"time"=>"2022-11-07T23:41:44.277120524Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /app/main.go:44 +0x578"}]
[12754] tail.0: [1667864504.277123824, {"time"=>"2022-11-07T23:41:44.277123824Z", "stream"=>"stderr", "_p"=>"F", "log"=>"main.main()"}]
[12755] tail.0: [1667864504.277127624, {"time"=>"2022-11-07T23:41:44.277127624Z", "stream"=>"stderr", "_p"=>"F", "log"=>"       /app/main.go:21 +0x36"}]
[12756] tail.0: [1667864504.477061100, {"time"=>"2022-11-07T23:41:44.4770611Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.476872 TRACE /app/main.go:61 main.testTime [] test Time (cost: 200.17378ms)"}]
[12757] tail.0: [1667864504.877315559, {"time"=>"2022-11-07T23:41:44.877315559Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.877119 TRACE /app/main.go:66 main.testTime [] test Timef (cost: 400.171457ms)"}]
[12758] tail.0: [1667864504.877358760, {"time"=>"2022-11-07T23:41:44.87735876Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.877155 INFO  /app/main.go:71 main.testLog [] test Log"}]
[12759] tail.0: [1667864504.877363960, {"time"=>"2022-11-07T23:41:44.87736396Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.877176 WARN  /app/main.go:24 main.main [] test Logf: 1"}]
[12760] tail.0: [1667864504.877372460, {"time"=>"2022-11-07T23:41:44.87737246Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.877181 WARN  /go/pkg/mod/github.com/gxlog/gxlog@v0.7.0/logger/logger.go:171 github.com/gxlog/gxlog/logger.(*Logger).Logf [] test Logf: -1"}]
[12761] tail.0: [1667864504.877376761, {"time"=>"2022-11-07T23:41:44.877376761Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.877188 ERROR /app/main.go:78 main.testLogError [] an error"}]
[12762] tail.0: [1667864504.877380461, {"time"=>"2022-11-07T23:41:44.877380461Z", "stream"=>"stderr", "_p"=>"F", "log"=>"2022-11-07 23:41:44.877196 ERROR /app/main.go:83 main.testLogErrorf [] another error"}]
```

**Screenshots**

**Your Environment**

* Version used: Fluent Bit v2.0.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):  k8s v1.22.6
* Server type and version:
* Operating System and version: Ubuntu 18.04
* Filters and plugins: Tail

**Additional context**

**Comment by RicardoAAD** [comment]
Hello @pfrcks 
I just tested the go multiline parser with CRI logs in Fluent-Bit v2.0.3 and master, and it works without any issues, but I couldn't make It work with the log example you provided here; this is why I'd like to see the whole log file used in your example, and we would appreciate it if you could provide a sample of the code that generates that exception, so we can analyze if the go multiline parser is not covering that specific case


The below config is just a working example of go multiline and CRI:

```
[INPUT]
        Name              tail
        Tag               tailed
        Path              logs/test5.log
        multiline.parser  cri
        Read_From_Head    true

[FILTER]
        Name                   multiline
        Match                  *
        multiline.key_content  log
        multiline.parser       go

[OUTPUT]
        Name stdout
        match *
```


Test log Example:

```
2021-12-22T02:36:56.941116989Z stdout F panic: my panic
2021-12-22T02:36:56.94111914Z stdout F
2021-12-22T02:36:56.941122703Z stdout F goroutine 4 [running]:
2021-12-22T02:36:56.941125769Z stdout F panic(0x45cb40, 0x47ad70)
2021-12-22T02:36:56.941128769Z stdout F   /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
2021-12-22T02:36:56.941131055Z stdout F main.main.func1(0xc420024120)
2021-12-22T02:36:56.941133533Z stdout F   foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
2021-12-22T02:36:56.941135853Z stdout F runtime.goexit()
2021-12-22T02:36:56.941138281Z stdout F   /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
2021-12-22T02:36:56.941140724Z stdout F created by main.main
2021-12-22T02:36:56.941142941Z stdout F   foo.go:5 +0x58
2021-12-22T02:36:56.941145054Z stdout F
2021-12-22T02:36:56.9411473

```
Fluent-Bit stdout results:

```
student@ubuntu:~/caliptia/fluent-bit/build-latest/bin$ vi logs/test44.log
student@ubuntu:~/caliptia/fluent-bit/build-latest/bin$ ./fluent-bit -c conf/config-test.conf
Fluent Bit v2.0.5
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/11/10 20:12:52] [ info] [fluent bit] version=2.0.5, commit=d739098da2, pid=83131
[2022/11/10 20:12:52] [ info] [storage] ver=1.1.5, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/11/10 20:12:52] [ info] [cmetrics] version=0.5.7
[2022/11/10 20:12:52] [ info] [ctraces ] version=0.2.5
[2022/11/10 20:12:52] [ info] [input:tail:tail.0] initializing
[2022/11/10 20:12:52] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2022/11/10 20:12:52] [ info] [input:tail:tail.0] multiline core started
[2022/11/10 20:12:52] [ info] [filter:multiline:multiline.0] created emitter: emitter_for_multiline.0
[2022/11/10 20:12:52] [ info] [input:emitter:emitter_for_multiline.0] initializing
[2022/11/10 20:12:52] [ info] [input:emitter:emitter_for_multiline.0] storage_strategy='memory' (memory only)
[2022/11/10 20:12:52] [ info] [output:stdout:stdout.0] worker #0 started
[2022/11/10 20:12:52] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2022/11/10 20:12:52] [ info] [sp] stream processor started
[2022/11/10 20:12:52] [ info] [filter:multiline:multiline.0] created new multiline stream for tail.0_tailed
[2022/11/10 20:12:52] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1293592 watch_fd=1 name=logs/test44.log
[0] tailed: [1640140616.941116989, {"time"=>"2021-12-22T02:36:56.941116989Z", "stream"=>"stdout", "_p"=>"F", "log"=>"panic: my panic

goroutine 4 [running]:
panic(0x45cb40, 0x47ad70)
  /usr/local/go/src/runtime/panic.go:542 +0x46c fp=0xc42003f7b8 sp=0xc42003f710 pc=0x422f7c
main.main.func1(0xc420024120)
  foo.go:6 +0x39 fp=0xc42003f7d8 sp=0xc42003f7b8 pc=0x451339
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003f7e0 sp=0xc42003f7d8 pc=0x44b4d1
created by main.main
  foo.go:5 +0x58

"}]
[1] tailed: [1668111172.832060064, {"log"=>"2021-12-22T02:36:56.9411473"}]
^C[2022/11/10 20:13:07] [engine] caught signal (SIGINT)
[2022/11/10 20:13:07] [ warn] [engine] service will shutdown in max 5 seconds
[2022/11/10 20:13:07] [ info] [input] pausing tail.0
[2022/11/10 20:13:07] [ info] [engine] service has stopped (0 pending tasks)
[2022/11/10 20:13:07] [ info] [input] pausing tail.0
[2022/11/10 20:13:07] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1293592 watch_fd=1
[2022/11/10 20:13:07] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/11/10 20:13:07] [ info] [output:stdout:stdout.0] thread worker #0 stopped
```


I'll be waiting for your next update to take to get more details about this issue.

Thanks!.

**Comment by pfrcks** [comment]
@RicardoAAD here's the golang file that I used to generate the logs

```package main

import (
    "time"
    "github.com/gxlog/gxlog"
    "github.com/gxlog/gxlog/iface"
)

// gxlog.Logger returns the default Logger.
var log = gxlog.Logger()

func main() {
    // gxlog.Formatter returns the default Formatter in Slot0.
    // Coloring is only supported on systems that ANSI escape sequences
    // are supported.
    gxlog.Formatter().EnableColoring()
	for {
		testLevel()
		// testPanic()
		testTime()
		testLog()
		testLogError()
		testLogErrorf()
		time.Sleep(10 * time.Second)
	}
}

func testLevel() {
    log.Trace("test Trace")
    log.Tracef("%s", "test Tracef")
    log.Debug("test Debug")
    log.Debugf("%s", "test Debugf")
    log.Info("test Info")
    log.Infof("%s", "test Infof")
    log.Warn("test Warn")
    log.Warnf("%s", "test Warnf")
    log.Error("test Error")
    log.Errorf("%s", "test Errorf")
    // Fatal and Fatalf will output the stack of current goroutine by default.
    log.Fatal("test Fatal")
    log.Fatalf("%s", "test Fatalf")
}

func testPanic() {
    // The default Level of Panic or Panicf is Fatal.
    // It will always panic when Panic or Panicf is called no matter at which
    // level the Logger is.
    log.Panic("test Panic")
    log.Panicf("%s", "test Panicf")
}

func testTime() {
    // Time or Timef returns a function. When the function is called, it outputs
    // the log as well as the time cost since the call of Time or Timef.
    // The default Level of Time or Timef is Trace.
    done := log.Timing("test Time")
    time.Sleep(200 * time.Millisecond)
    done()
    // Time or Timef works well with defer.
    // Notice the last empty pair of parentheses.
    defer log.Timingf("%s", "test Timef")()
    time.Sleep(400 * time.Millisecond)
}

func testLog() {
    // The calldepth can be specified in Log and Logf. That is useful when you
    // are customizing your own log wrapper function.
    log.Log(0, iface.Info, "test Log")
    log.Logf(1, iface.Warn, "%s: %d", "test Logf", 1)
    log.Logf(-1, iface.Warn, "%s: %d", "test Logf", -1)
}

func testLogError() error {
    // LogError outputs a log and call errors.New to generate an error.
    return log.LogError(iface.Error, "an error")
}

func testLogErrorf() error {
    // LogErrorf outputs a log and call fmt.Errorf to generate an error.
    return log.LogErrorf(iface.Error, "%s", "another error")
}
```


go.mod file

```
module example.com/m/v2

go 1.14
```


complete log file: attached
[test.log](https://github.com/fluent/fluent-bit/files/9993787/test.log)

**Comment by RicardoAAD** [comment]
Hello @pfrcks 

I'm sorry that the built-in go parser is not working for your use case. If you haven't found a solution this might help.
 
This parser uses a regex that searches for a specific pattern that contains the word panic; if not found, it will not parse go multiline logs; this is why for specific use cases, you will need to implement a custom multiline parser in order to match the logs you want to parse.

 
Please check my config:
The first thing we need is to parse the cri logs from the k8s; we can do this by using the built-in cri multiline parser in the input plugin, and then using a custom multiline parser in the multiline filter, you will be able to parse these logs.

```
    [SERVICE]
        Flush                       1
        Daemon                      Off
        parsers_file  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/testgo*.log
        multiline.parser    cri
        read_from_head true

    [FILTER]
      name                  multiline
      match                 *
      multiline.key_content log
      multiline.parser     multiline-regex-test


    [OUTPUT]
       name stdout
       match *
```
Based on our example from the documentation:[Custom Multiline](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace#configuration-example).  The custom multiline parser example that matches the go multiline log from your sample looks like:

```
    [MULTILINE_PARSER]
       name          multiline-regex-test
       type          regex
       flush_timeout 10
       #
       # rules |   state name  | regex pattern                                     | next state
       # ------|---------------|-----------------------------------|----------------------------
       rule      "start_state"        "/^goroutine \d+ \[[^\]]+\]:$/"            "cont"
       rule      "cont"                   "/^(?:[^\s.:]+\.)*[^\s.():]+\(.*\)/"    "cont"
       rule      "cont"                   "/^\s.*/"                               "cont"
       rule      "cont"                   "/.*/"                                  "cont"
```

Regards,
Ricardo
