### ISSUE TITLE
[engine] caught signal (SIGSEGV) with multiline parser and loki output

### ISSUE THREAD

**Issue by maratkomarov** [fluent/fluent-bit#6645]
## Bug Report

**Describe the bug**

We observe several crashes a day.

Trace 1:
```
[logger] [2023/01/04 09:09:20] [engine] caught signal (SIGSEGV)
[logger] #0 0x7fcfdceafaf3 in ???() at ???:0
[logger] #1 0x562342efb592 in flb_sds_cat() at src/flb_sds.c:133
[logger] #2 0x56234321d945 in safe_sds_cat() at plugins/out_loki/loki.c:44
[logger] #3 0x562343221403 in pack_record() at plugins/out_loki/loki.c:1223
[logger] #4 0x562343221922 in loki_compose_payload() at plugins/out_loki/loki.c:1381
[logger] #5 0x562343221a02 in cb_loki_flush() at plugins/out_loki/loki.c:1408
[logger] #6 0x562342f194ca in output_pre_cb_flush() at include/fluent-bit/flb_output.h:524
[logger] #7 0x562343952b06 in co_init() at lib/monkey/deps/flb_libco/amd64.c:117
[logger] #8 0x5623451dbf4f in ???() at ???:0
```

Trace 2:
```
[logger] [2023/01/04 02:36:21] [engine] caught signal (SIGSEGV)
[logger] #0 0x5644e80f742d in flb_sp_do() at src/stream_processor/flb_sp.c:1968
[logger] #1 0x5644e7a05d14 in input_chunk_append_raw() at src/flb_input_chunk.c:1664
[logger] #2 0x5644e7a06318 in flb_input_chunk_append_raw() at src/flb_input_chunk.c:1881
[logger] #3 0x5644e7a09cdc in input_log_append() at src/flb_input_log.c:33
[logger] #4 0x5644e7a09d43 in flb_input_log_append() at src/flb_input_log.c:47
[logger] #5 0x5644e7adc0ad in ml_stream_buffer_flush() at plugins/in_tail/tail_file.c:356
[logger] #6 0x5644e7add1d2 in ml_flush_callback() at plugins/in_tail/tail_file.c:879
[logger] #7 0x5644e79b6e04 in flb_ml_flush_stream_group() at src/multiline/flb_ml.c:1133
[logger] #8 0x5644e79b4dc7 in flb_ml_flush_parser_instance() at src/multiline/flb_ml.c:116
[logger] #9 0x5644e7a1e3ad in flb_ml_stream_id_destroy_all() at src/multiline/flb_ml_stream.c:308
[logger] #10 0x5644e7ade189 in flb_tail_file_remove() at plugins/in_tail/tail_file.c:1169
[logger] #11 0x5644e7ade459 in flb_tail_file_remove_all() at plugins/in_tail/tail_file.c:1240
[logger] #12 0x5644e7ac99c7 in in_tail_exit() at plugins/in_tail/tail.c:479
[logger] #13 0x5644e7938579 in flb_input_instance_exit() at src/flb_input.c:1258
[logger] #14 0x5644e79385e2 in flb_input_exit_all() at src/flb_input.c:1279
[logger] #15 0x5644e796c370 in flb_engine_shutdown() at src/flb_engine.c:1032
[logger] #16 0x5644e796bfe8 in flb_engine_start() at src/flb_engine.c:929
[logger] #17 0x5644e7913bd9 in flb_lib_worker() at src/flb_lib.c:629
[logger] #18 0x7f4861287ea6 in ???() at ???:0
[logger] #19 0x7f4860b57a2e in ???() at ???:0
[logger] #20 0xffffffffffffffff in ???() at ???:0
```

**To Reproduce**

parsers.conf
```
      [MULTILINE_PARSER]
         name          multiline-py
         type          regex
         flush_timeout 1000 # ms
         rule          "start_state"  "^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}" "cont"
         rule          "cont"         "^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}).*" "cont"

      [PARSER]
         Name py-filename-service-extractor
         Format regex
         Regex ^.+/(?<service>.+)\.log$

      [PARSER]
         Name py-log-record
         Format regex
         Regex /^(?<time>[^\|]+) \| (?<level>\w+)\s+\| (?<log>.+)/m
         Time_Key time
         Time_Format %Y-%m-%d %H:%M:%S.%L

      [MULTILINE_PARSER]
         name          multiline-php
         type          regex
         flush_timeout 1000 # ms
         rule          "start_state"  "^\[\d{2}-\w{3}-\d{4} \d{2}:\d{2}:\d{2} \S.*?\]" "cont"
         rule          "cont"         "^(?!\[\d{2}-\w{3}-\d{4} \d{2}:\d{2}:\d{2} \S.*?\]).*" "cont"

      [PARSER]
         Name php-errors-record
         Format regex
         Regex /^\[(?<time>[^\]]+)\] (?<log>.+)/m
         Time_Key time
         Time_Format %d-%b-%Y %H:%M:%S %Z
```

fluent-bit.conf
```
      [SERVICE]
         Daemon Off
         log_level info
         Flush 5
         parsers_file parsers.conf

      [INPUT]
         Name tail
         Path /opt/scalr-server/var/log/service/*.log
         Exclude_Path /opt/scalr-server/var/log/service/php-*
         Path_Key filename
         multiline.parser multiline-py
         Tag py

      [INPUT]
         Name tail
         Path /opt/scalr-server/var/log/php/*.log
         multiline.parser multiline-php
         Tag php

      # php modifier

      [FILTER]
         Name parser
         Match php
         Key_Name log
         Parser php-errors-record
         Reserve_Data on

      [FILTER]
         Name modify
         Match php
         Set service zmq-service
         Set level INFO

      [FILTER]
         Name modify
         Match php
         Condition Key_value_matches log ^PHP\s\w+\serror:\s.*$
         Set level ERROR

      # py modifier

      [FILTER]
         Name parser
         Match py
         Key_Name filename
         Parser py-filename-service-extractor
         Reserve_Data on

      [FILTER]
         Name parser
         Match py
         Key_Name log
         Parser py-log-record
         Reserve_Data on

      [OUTPUT]
         Name        loki
         Match       *
         Host        logs-prod-us-central1.grafana.net
         port        443
         tls         on
         tls.verify  on

         # Log line must contain the single key "log"
         drop_single_key on
         # Default "json" format wraps the log line into extra quotes: e.g. "<log>\n"
         line_format key_value
         remove_keys service, level
         labels      env=foo, app=testenv.scalr.dev, service=$service, level=$level
```

**Expected behavior**

Fluent-but runs smoothly.

**Your Environment**

* Version used: v2.0.6
* Configuration: 
* Environment name and version: Kubernetes, GKE, v1.22.15-gke.100
* Server type and version:
* Operating System and version: Linux 5.10.133+ x86_64
* Filters and plugins: parser, modify, loki

**Comment by ehienabs** [comment]
Hello @maratkomarov does this work for you now?

**Comment by maratkomarov** [comment]
Re-run our test suite several times on the fluent-bit master. The error has gone. Thank you @nokute78 @ehienabs
