### ISSUE TITLE
Python multiline log cant work in k8s env

### ISSUE THREAD

**Issue by xingstudy** [fluent/fluent-bit#6659]
## Bug Report

**Describe the bug**
I want to collect logs via fluent-bit in k8s env. I found the python log can not multiline to one line.

** my log **
```
2023-01-09 10:19:34,311 1,Thread-35629 base.py:39 [D] lang : en-us
2023-01-09 10:19:34,311 1,Thread-35629 vtools.py:612 [I] MH> args_builder == LoginArgsBuilder
2023-01-09 10:19:34,312 1,Thread-35629 vtools.py:113 [I] MH> inspector == MisInspector
2023-01-09 10:19:34,312 1,Thread-35629 vtools.py:120 [I] MH> load method to aber
2023-01-09 10:19:34,312 1,Thread-35629 vtools.py:120 [I] MH> load session_data to aber
2023-01-09 10:19:34,312 1,Thread-35629 vtools.py:120 [I] MH> load langconf to aber
2023-01-09 10:19:34,312 1,Thread-35629 vtools.py:120 [I] MH> load lang_resp to aber
2023-01-09 10:19:34,312 1,Thread-35629 vtools.py:292 [D] set([])
2023-01-09 10:19:34,314 1,Thread-35629 redispool.py:26 [I] server=redis|addr=redis:6379|db=0|cmd=('GET', '_org_portal_hk_login_limit_hkgraysanbox008fa_')|ret=None|time=1369
2023-01-09 10:19:35,031 1,Thread-35629 client.py:146 [I] server=ApolloServer|func=findUsers|addr=apollo:6700/10000|time=660168|framed=False|args=1|kwargs=0
2023-01-09 10:19:35,031 1,Thread-35629 decorator.py:180 [W] Traceback (most recent call last):
  File "/bin/utils/decorator.py", line 171, in __
    return del_func(self, *args, **kwargs)
  File "/bin/handler/user/login.py", line 67, in POST
    raise ParamError(self.lang_resp.WRONG_USERNAME_OR_PASS)
ParamError: [code:2101] errormsg:Wrong user account or wrong password

2023-01-09 10:19:35,044 1,Thread-35630 base.py:86 [I] not login
2023-01-09 10:19:35,057 1,Thread-35630 base.py:131 [I] ===========exec finish task operation_log===========
2023-01-09 10:19:35,057 1,Thread-35630 tools.py:377 [I] request params/org/user/login
10.10.102.196 - - [09/Jan/2023 10:19:35] "POST /user/login HTTP/1.1" 200 125
```

**Screenshots**
![iss-20230109102604](https://user-images.githubusercontent.com/17332086/211232819-a470f74f-7927-468d-b273-3427e3f3e7df.png)

**Expected behavior**
The following multiple lines should be one line, but it's many lines when I query in ES.
```
2023-01-09 10:19:35,031 1,Thread-35629 decorator.py:180 [W] Traceback (most recent call last):
  File "/bin/utils/decorator.py", line 171, in __
    return del_func(self, *args, **kwargs)
  File "/bin/handler/user/login.py", line 67, in POST
    raise ParamError(self.lang_resp.WRONG_USERNAME_OR_PASS)
ParamError: [code:2101] errormsg:Wrong user account or wrong password
```

**Your Environment**
helm: v3.8.2
k8s: v1.23.0 
docker: docker-ce-20.10.12
fluent-bit app.kubernetes.io/version: 2.0.8                                                                                                                                                              
helm.sh/chart: fluent-bit-0.21.7 

**helm value config**
```
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser python-multiline-regex, python, cri, go, java, docker
        Tag kube.*
        Mem_Buf_Limit 500MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On


  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Logstash_Format On
        Retry_Limit False
        Port 9200
        HTTP_User user
        HTTP_Passwd passwd
        tls On
        tls.verify Off
        Replace_Dots On
        Logstash_Prefix kube
        Suppress_Type_Name On
        Generate_ID On
        Trace_Error On
        Buffer_Size 250M
        Retry_Limit 5


    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Port 9200
        HTTP_User user
        HTTP_Passwd passwd
        tls On
        tls.verify Off
        Replace_Dots On

  upstream: {}

  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [MULTILINE_PARSER]
        Name          python-multiline-regex
        Type          regex
        flush_timeout 1000
        rule "start_state" "^([0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]+)" "cont"
        rule       "cont"            ".*"     "cont"
 ```

**Comment by RicardoAAD** [comment]
Hello @xingstudy 

The built-in python parser uses a regex to match the start of the python multiline log; unfortunately, this regex doesn't match the log example you have provided, and neither your custom python-multiline-regex parser does.
The regex in the built-in python parser searches for the start of the multiline using the word Traceback as the start of the line, but in your log the word Traceback has a blank space that causes the issue.

Could you please provide a sample code that generates this python log?

In the meantime, you could give it a try to the below custom multiline parser?

 multiline-python.conf:
```
[MULTILINE_PARSER]
    Name          python-multiline-regex
    Type          regex
    flush_timeout 1000
    rule "start_state" "^([0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]+).*Traceback \(most recent call last\):$" "cont"
    rule "cont" "^[\t ]+.*" "cont"
    rule "cont" "^(?:[^\s.():]+\.)*[^\s.():]+:" "cont"
```

We encourage our users to simplify the configuration of regular expressions by using Rubular web site.
https://rubular.com/r/NDuyKwlTGOvq2g


Please let us know if the custom multiline parser worked for you.

Thanks.
