### ISSUE TITLE
LogEntry using multiline parser and Path_Key gets dropped

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#6662]
## Bug Report

**Describe the bug**
LogEntry using multiline parser and Path_Key gets dropped. The problem is "solved" if i remove `path_key`

**To Reproduce**

```
sophieyfang_google_com@debian10-multiline:~$ cat fluentbit-all.conf 
[SERVICE]
    flush                 1
    log_level             debug
    parsers_file          parsers_multiline_all.conf

[INPUT]
    name                  tail
    path_key              woof
    path                  /home/sophieyfang_google_com/err.logs
    read_from_head        true
    multiline.parser      multiline.my_error_pipeline.my_app_errors.0


[OUTPUT]
    name                  stdout
    match                 *

sophieyfang_google_com@debian10-multiline:~$ cat parsers_multiline_all.conf 
[MULTILINE_PARSER]
    flush_timeout 1000
    name          multiline.my_error_pipeline.my_app_errors.0
    type          regex
    rule          "start_state, java_start_exception"  "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule          "java_nested_exception" "/(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]*nested exception is:[\\t ]*/" "java_nested_exception"
    rule          "java_after_exception" "/^[\r\n]*$/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]+(?:eval )?at /" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]+--- End of inner exception stack trace ---$/" "java_after_exception"
    rule          "java_after_exception" "/^--- End of stack trace from previous (?x:)location where exception was thrown ---$/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    rule          "java_after_exception" "/^[\t ]*... \d+ (?:more|common frames omitted)/" "java_after_exception"
sophieyfang_google_com@debian10-multiline:~$ cat err.logs 
java.lang.Exception: Something wrong happened!
        at com.google.example.App.main(App.java:22)









java.lang.Exception: Somethign elsehappened!
	at com.google.example.App.main(App.java:22)

java.lang.Exception: Something wrong happened!
        at com.google.example.App.main(App.java:22)









java.lang.Exception: Somethign elsehappened!
	at com.google.example.App.main(App.java:22)

java.lang.Exception: Something wrong happened!
        at com.google.example.App.main(App.java:22)









java.lang.Exception: Somethign elsehappened!
	at com.google.example.App.main(App.java:22)

java.lang.Exception: Something wrong happened!
        at com.google.example.App.main(App.java:22)









java.lang.Exception: Somethign elsehappened!
	at com.google.example.App.main(App.java:22)

java.lang.Exception: Something wrong happened!
        at com.google.example.App.main(App.java:22)









java.lang.Exception: Somethign elsehappened!
	at com.google.example.App.main(App.java:22)


do I need [info] stuff?

Maybe I do?

Caused by: my.exception.Bar
	at hipster.doFus(Dumb.java:10)

sophieyfang_google_com@debian10-multiline:~$ sudo /opt/google-cloud-ops-agent/subagents/fluent-bit/bin/fluent-bit --config fluentbit-all.conf 

```

**Expected behavior**
The logEntry shall at least appear in the console but none has been seen.

**Screenshots**

**Your Environment**

sophieyfang_google_com@debian10-multiline:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Additional context**

**Comment by RicardoAAD** [comment]
Hi @sophieyfang 

Thank you for reporting this issue. I reproed this issue using Fluent-Bit v1.9.8 and v1.9.9 and I can confirm that this issue was solved with this PR https://github.com/fluent/fluent-bit/commit/01134e879457ca1b3151a775f87cbac2f5ec442e in Fluent-Bit v2.0.0.

Could you please confirm that this is working for you in Fluent-Bit v2.0.x?

Thank you for your support and for being a part of our community. 

Best Regards,
Ricardo
