### ISSUE TITLE
Unable to Parse MultiLine Python Exceptions with MultiLine Parser

### ISSUE THREAD

**Issue by gh-arashok** [fluent/fluent-bit#6747]
I've set up a multiline parser from the official documentation. I have a service setup that reads from my custom parsers file, a tail input which captures my logs; which i also set to use the custom multiline parser i created. I also created a standard filter, and am outputting to stdout.  I've also linked a sample log from my app, and the fluentbit log. The exceptions start with Traceback. One of the main issues i'm facing is that with the current setup multiline logs are not flowing, and coming as seperate logs. 

```text
    [SERVICE]
        flush                 1
        log_level             debug
        parsers_file          parsers_multiline.conf

    [INPUT]
        Name tail
        Path /var/log/containers/helloworld-v2-*.log
        Tag kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        read_from_head true
        multiline.parser multiline-regex-test
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.
        Merge_Log On
        Merge_Log_Key  log_processed
        Merge_Log_Trim On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Regex_Parser kubernetes-tag
    [OUTPUT]
        name  stdout
        match *
```
```
      [MULTILINE_PARSER]
          name          multiline-regex-test
          type          regex
          flush_timeout 1000
              #
              # Regex rules for multiline parsing
              # ---------------------------------
              #
              # configuration hints:
              #
              #  - first state always has the name: start_state
              #  - every field in the rule must be inside double quotes
              #
              # rules |   state name  | regex pattern                  | next state
              # ------|---------------|--------------------------------------------
          rule      "start_state"   "/^Traceback\ \(most\ recent\ call\ last\):.*$/"  "cont"
          rule      "cont"          "/^\s+File.*/m"                     "cont"  
```

```text
ERROR:main:crash route
INFO:werkzeug:127.0.0.1 - - [24/Jan/2023 20:50:19] "GET /crash HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/python-test-app/main.py", line 34, in crash
    num3=num1/num2
ZeroDivisionError: division by zero
```

```
        "log_processed"=>{
            "log"=>"Traceback (most recent call last):",
        "log_processed"=>{
            "log"=>"    return self.wsgi_app(environ, start_response)",

```

**Comment by patrick-stephens** [comment]
This is on 1.9.9-debug I believe after a Slack discussion: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1674758191707099

**Comment by gh-arashok** [comment]
Upgraded to 2.0.8-debug

**Comment by lecaros** [comment]
Hi @gh-arashok 
I assume this is the output you're seeing during your test.

```text
        "log_processed"=>{
            "log"=>"Traceback (most recent call last):",
        "log_processed"=>{
            "log"=>"    return self.wsgi_app(environ, start_response)",
```

If you have full output it will be more useful, since it doesn't match the config you've provided.

However, I've noticed that you only have 2 rules in your parser. One that will match the starting state and a second one for the one that starts with `File`. You should have a third one to match the rest of the lines.

```text
          rule      "start_state"   "/^Traceback\ \(most\ recent\ call\ last\):.*$/"  "cont"
          rule      "cont"          "/^\s+File.*/m"                     "cont"
          rule      "cont"          "/[^\t ]/" "cont"
```

This will then be the output:
```text
[0] tail.0: [1675107752.203666059, {"log"=>"Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/python-test-app/main.py", line 34, in crash
    num3=num1/num2
ZeroDivisionError: division by zero
"}]
```

**Comment by gh-arashok** [comment]
I tried the output and getting single line still
`[2] kube.test.helloworld-v2-64488c58b9-vbc42.helloworld: [1675181065.031406242, {"log_processed"=>{"log"=>"Traceback (most recent call last):", "stream"=>"stderr", "time"=>"2023-01-31T16:04:25.031314569Z"}, "kubernetes"=>{"pod_name"=>"helloworld-v2-64488c58b9-vbc42", "namespace_name"=>"test", "pod_id"=>
`

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/116193654/215814738-f3c7b73c-10f8-46d1-b090-31e6f45e773e.png">

**Comment by gh-arashok** [comment]
`
[0] kube.test.helloworld-v2-64488c58b9-vbc42.helloworld: [1675181426.751781899, {"log_processed"=>{"log"=>"ERROR:main:crash route", "stream"=>"stderr", "time"=>"2023-01-31T16:10:26.751583014Z"}, "kubernetes"=>{"pod_name"=>"helloworld-v2-64488c58b9-vbc42", "namespace_name"=>"test"
[1] kube.test.helloworld-v2-64488c58b9-vbc42.helloworld: [1675181426.765800975, {"log_processed"=>{"log"=>"INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 16:10:26] "GET /crash HTTP/1.1" 500 -", "stream"=>"stderr", "time"=>"2023-01-31T16:10:26.761718987Z"}, 
[2] kube.test.helloworld-v2-64488c58b9-vbc42.helloworld: [1675181426.765811115, {"log_processed"=>{"log"=>"Traceback (most recent call last):", "stream"=>"stderr", "time"=>"2023-01-31T16:10:26.762213361Z"}
`

**Comment by gh-arashok** [comment]
```
[9051] tail.0: [1675181722.125647177, {"log"=>"{"log":"    response = self.handle_exception(e)\n","stream":"stderr","time":"2023-01-31T16:10:26.762297254Z"}
"}]
[9052] tail.0: [1675181722.125648455, {"log"=>"{"log":"  File \"/usr/lib/python3.10/site-packages/flask/app.py\", line 2525, in wsgi_app\n","stream":"stderr","time":"2023-01-31T16:10:26.762307292Z"}
"}]
[9053] tail.0: [1675181722.125649730, {"log"=>"{"log":"    response = self.full_dispatch_request()\n","stream":"stderr","time":"2023-01-31T16:10:26.76231751Z"}
"}]
[9054] tail.0: [1675181722.125651030, {"log"=>"{"log":"  File \"/usr/lib/python3.10/site-packages/flask/app.py\", line 1822, in full_dispatch_request\n","stream":"stderr","time":"2023-01-31T16:10:26.762327614Z"}
"}]
[9055] tail.0: [1675181722.125652260, {"log"=>"{"log":"    rv = self.handle_user_exception(e)\n","stream":"stderr","time":"2023-01-31T16:10:26.762337863Z"}
"}]
[9056] tail.0: [1675181722.125653526, {"log"=>"{"log":"  File \"/usr/lib/python3.10/site-packages/flask/app.py\", line 1820, in full_dispatch_request\n","stream":"stderr","time":"2023-01-31T16:10:26.762365388Z"}
"}]
[9057] tail.0: [1675181722.125654748, {"log"=>"{"log":"    rv = self.dispatch_request()\n","stream":"stderr","time":"2023-01-31T16:10:26.76237655Z"}
"}]
[9058] tail.0: [1675181722.125656039, {"log"=>"{"log":"  File \"/usr/lib/python3.10/site-packages/flask/app.py\", line 1796, in dispatch_request\n","stream":"stderr","time":"2023-01-31T16:10:26.762386554Z"}
"}]
[9059] tail.0: [1675181722.125657315, {"log"=>"{"log":"    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n","stream":"stderr","time":"2023-01-31T16:10:26.762396708Z"}
"}]
[9060] tail.0: [1675181722.125658599, {"log"=>"{"log":"  File \"/python-test-app/main.py\", line 34, in crash\n","stream":"stderr","time":"2023-01-31T16:10:26.762406909Z"}
"}]
[9061] tail.0: [1675181722.125659856, {"log"=>"{"log":"    num3=num1/num2\n","stream":"stderr","time":"2023-01-31T16:10:26.762417008Z"}
"}]
[9062] tail.0: [1675181722.125661129, {"log"=>"{"log":"ZeroDivisionError: division by zero\n","stream":"stderr","time":"2023-01-31T16:10:26.762426691Z"}
```

**Comment by RicardoAAD** [comment]
Hello @gh-arashok 
I'm using an almost identical configuration as yours, and as you can see, my multiline parser works fine. Please describe how you are getting the Python exception from your sample log. Could you please share the code that is generating this exception?
What runtime are you using in this cluster?

Config map:
```
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 4
        Log_Level debug
        Parsers_File parsers.conf
        Parsers_file custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/test.log
        read_from_head true
        multiline.parser multiline-regex-test
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.
        Merge_Log On
        Time_Keep On
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Name        s3_logs
        Format      json
        Time_Key    requestReceivedTimestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On
    [PARSER]
        Name        kubernetes-tag
        Format      regex
        Regex       (?<namespace_name>.+)\.(?<pod_name>.+)\.(?<container_name>.+)
```

Test log:
```
:~/fluent-bit$ cat /var/log/test.log
ERROR:main:crash route
INFO:werkzeug:127.0.0.1 - - [24/Jan/2023 20:50:19] "GET /crash HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/python-test-app/main.py", line 34, in crash
    num3=num1/num2
ZeroDivisionError: division by zero
```
Fluent-bit multiline log ouput?:
```
ricardo@support-visa-ricardo:~/fluent-bit$ k logs -f fluent-fluent-bit-vzbrv
Fluent Bit v2.1.2
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/05/09 14:01:57] [ info] [fluent bit] version=2.1.2, commit=113c7c00d2, pid=1
[2023/05/09 14:01:57] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/05/09 14:01:57] [ info] [cmetrics] version=0.6.1
[2023/05/09 14:01:57] [ info] [ctraces ] version=0.3.0
[2023/05/09 14:01:57] [ info] [input:tail:tail.0] initializing
[2023/05/09 14:01:57] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2023/05/09 14:01:57] [ info] [input:tail:tail.0] multiline core started
[2023/05/09 14:01:57] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2023/05/09 14:01:57] [ info] [filter:kubernetes:kubernetes.0]  token updated
[2023/05/09 14:01:57] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2023/05/09 14:01:57] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2023/05/09 14:01:57] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2023/05/09 14:01:57] [ info] [output:stdout:stdout.0] worker #0 started
[2023/05/09 14:01:57] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2023/05/09 14:01:57] [ info] [sp] stream processor started
[2023/05/09 14:01:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=2385 watch_fd=1 name=/var/log/test.log
[0] tail.0: [[1683640917.729707738, {}], {"log"=>"ERROR:main:crash route
"}]
[1] tail.0: [[1683640917.729739329, {}], {"log"=>"INFO:werkzeug:127.0.0.1 - - [24/Jan/2023 20:50:19] "GET /crash HTTP/1.1" 500 -
"}]
[0] tail.0: [[1683640917.729741837, {}], {"log"=>"Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/python-test-app/main.py", line 34, in crash
    num3=num1/num2
ZeroDivisionError: division by zero
"}]
```
