### ISSUE TITLE
Is there any way to override the "key" when multiline parser is set?

### ISSUE THREAD

**Issue by waynec86** [fluent/fluent-bit#7592]
## Bug Report

**Describe the bug**
I'm not 100% sure this is a bug, but when the `multiline.parser` is set with the `key` in the tail plugin, all the messages get put in the "log" field. Is there any way to override this?

**To Reproduce**

```
Some Log Message
```

will become 
```
{"log":"Some Log Message", ...}
```
when the `multiline.parser` is set. We would like a way to override the "key" that the log gets written to
- Steps to reproduce the problem:
Specify `multiline.parser` in the tail input along with the "key" (or could be a feature request and to override this key for multiline parser).

**Expected behavior**
What is specified in the "key" should be what the parsed multiline message or non-multiline message gets written to. 

**Your Environment**

* Version used: 2.1.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): docker
* Server type and version: 
* Operating System and version: Ubuntu 22.04
* Filters and plugins: tail input + lua filter + kafka output

**Comment by patrick-stephens** [comment]
Can you clarify with full config and an example? 

The keys after parsing are defined by the actual parser, i.e. the capture groups in the regex for example. It would help to see the config you're using and an example. 

Is it one of the built in ones? Maybe that's the ask, to change that default? 

If parsing fails then the log key is the default too.

You can always rename keys afterwards too.

**Comment by waynec86** [comment]
Sure, here's a repro example (this is completely hypothetical):

test_exception.in
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
    at com.example.MyClass.myMethod(MyClass.java:15)
    at com.example.MyClass.main(MyClass.java:8)
```

test_parser.conf
```
[MULTILINE_PARSER]
    name          java-exception
    type          regex
    flush_timeout 1000
    rule  "start_state"  "^Exception.+"  "cont"
    rule  "cont"  "^\s+at.+"  "cont"
```

test_fluent_bit.conf
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File test_parser.conf

[INPUT]
    Name tail
    Tag test
    Path test_exception.in
    Path_Key file_path
    Key message
    Read_from_Head true
    multiline.parser java-exception

[OUTPUT]
    Name         stdout
    Match        *
```


Output of test:
```
/fluent-bit/bin/fluent-bit -c test_fluent_bit.conf
Fluent Bit v2.1.4
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/06/21 16:27:28] [ info] [fluent bit] version=2.1.4, commit=, pid=459
[2023/06/21 16:27:28] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/06/21 16:27:28] [ info] [cmetrics] version=0.6.1
[2023/06/21 16:27:28] [ info] [ctraces ] version=0.3.1
[2023/06/21 16:27:28] [ info] [input:tail:tail.0] initializing
[2023/06/21 16:27:28] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2023/06/21 16:27:28] [ info] [input:tail:tail.0] multiline core started
[2023/06/21 16:27:28] [ info] [sp] stream processor started
[2023/06/21 16:27:28] [ info] [output:stdout:stdout.0] worker #0 started
[2023/06/21 16:27:28] [ info] [input:tail:tail.0] inotify_fs_add(): inode=8029 watch_fd=1 name=test_exception.in
[0] test: [[1687364848.915849563, {}], {"log"=>"Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
    at com.example.MyClass.myMethod(MyClass.java:15)
    at com.example.MyClass.main(MyClass.java:8)
", "file_path"=>"test_exception.in"}]
^C[2023/06/21 16:27:36] [engine] caught signal (SIGINT)
[2023/06/21 16:27:36] [ warn] [engine] service will shutdown in max 5 seconds
[2023/06/21 16:27:36] [ info] [input] pausing tail.0
[2023/06/21 16:27:37] [ info] [engine] service has stopped (0 pending tasks)
[2023/06/21 16:27:37] [ info] [input] pausing tail.0
[2023/06/21 16:27:37] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=8029 watch_fd=1
[2023/06/21 16:27:37] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2023/06/21 16:27:37] [ info] [output:stdout:stdout.0] thread worker #0 stopped
```


I expected since I set "Key" to message, the output should be:
```
{"message"=>"Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
    at com.example.MyClass.myMethod(MyClass.java:15)
    at com.example.MyClass.main(MyClass.java:8)
", "file_path"=>"test_exception.in"}
```
keyed by "message" instead of log.

For example, if I don't set a parser at all (Added # on the multiline.parser part of the conf and rerun):
I get:
```
[0] test: [[1687365105.715400950, {}], {"file_path"=>"test_exception.in", "message"=>"Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5"}]
[1] test: [[1687365105.715459101, {}], {"file_path"=>"test_exception.in", "message"=>"    at com.example.MyClass.myMethod(MyClass.java:15)"}]
[2] test: [[1687365105.715461131, {}], {"file_path"=>"test_exception.in", "message"=>"    at com.example.MyClass.main(MyClass.java:8)"}]
```

which has the key as message.

As another test, I set a "parser"

```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File test_parser.conf
    Parsers_File parsers.conf

[INPUT]
    Name tail
    Tag test
    Path test_exception.in
    Path_Key file_path
    Key message
    Read_from_Head true
    parser json
    # multiline.parser java-exception

[OUTPUT]
    Name         stdout
    Match        *
```

and got the same output.

I think it is a bug that if we set `multiline.parser` that it does not respect the "key"

**Comment by patrick-stephens** [comment]
It's not a bug I'd say, the `key` value is used when a parser is not applied (or fails): https://docs.fluentbit.io/manual/pipeline/inputs/tail
```
When a message is unstructured (no parser applied), it's appended as a string under the key name log. This option allows to define an alternative name for that key.
```
In this case a parser is being used and is successful, `log` is likely used because it is the default for others as well (e.g. the K8S filter).

I think what you're requesting is actually a new option to specify the output key for a multiline parser? https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#configurable-multiline-parsers
At the moment you can specify the input key to combine from as `key_content`. I'm not sure if output key can be configured currently @lecaros ?

**Comment by patrick-stephens** [comment]
And of course you can always rename or copy the key with a filter after input: https://docs.fluentbit.io/manual/pipeline/filters/modify#configuration-file

Something like:
```toml
[FILTER]
  name modify
  match *
  rename log message
```

Just as a workaround for now.

**Comment by waynec86** [comment]
I don't think multiline parser currently supports capture groups natively. From https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing it seems like you would need a separate filter (parser) to do so.

I think I can make do with the workaround, but it just seems like unexpected behavior. It seems like it should be a relatively simple fix hopefully. I look forward to it in a future release. Thanks!

**Comment by patrick-stephens** [comment]
It's all OSS so feel free to submit a PR too. :+1:

**Comment by waynec86** [comment]
@patrick-stephens sounds good! I actually have the repo checked out. I'll take a look when I have time
