### ISSUE TITLE
how to parse Multiline JSON 

### ISSUE THREAD

**Issue by ibrahimjelliti** [fluent/fluent-bit#7770]
Hi,
I have logs from opensearch containers that is multiline json:

I am using this conf but its combining multiple json together
```
  opensearch-log.conf: |
    [INPUT]
        Name                tail
        Tag                 opensearch.*
        Path                /var/log/containers/opensearch-cluster-master*
        multiline.parser    json-opensearch-multiline
        DB                  /var/fluent-bit/state/flb_opensearch.db
        Mem_Buf_Limit       60MB
        Buffer_Chunk_Size   10MB
        Buffer_Max_Size     20MB
        Skip_Long_Lines     Off
        Skip_Empty_Lines    Off
        Refresh_Interval    10
        Read_from_Head      ${READ_FROM_HEAD}


    [OUTPUT]
        Name                cloudwatch_logs
        Match               opensearch.*
        region              ${AWS_REGION}
        log_group_name      /aws/containerinsights/${CLUSTER_NAME}/opensearch
        log_stream_prefix   ${HOST_NAME}.
        auto_create_group   true
        extra_user_agent    container-insights


----
  parsers.conf: |
    [MULTILINE_PARSER]
        Name                json-opensearch-multiline
        type                regex
        flush_timeout       1000
        rule                "start_state"  "/{(.*)/"  "cont"
        rule                "cont"         "/.*/"             "cont"
```

```
{"type": "server", "timestamp": "2023-07-29T06:28:11,324Z", "level": "INFO", "component": "o.o.i.i.ManagedIndexRunner", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Executing attempt_rollover for playable_events_jfwgxpeyd9y-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
{"type": "server", "timestamp": "2023-07-29T06:28:11,326Z", "level": "INFO", "component": "o.o.i.i.ManagedIndexRunner", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Finished executing attempt_rollover for playable_events_jfwgxpeyd9y-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
{"type": "server", "timestamp": "2023-07-29T06:28:16,085Z", "level": "INFO", "component": "o.o.j.s.JobScheduler", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Will delay 104540 miliseconds for next execution of job playable_events_zc5p6djrsjf-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
{"type": "server", "timestamp": "2023-07-29T06:28:16,896Z", "level": "ERROR", "component": "o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Exception during establishing a SSL connection: java.net.SocketException: Connection reset", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g" ,
"stacktrace": ["java.net.SocketException: Connection reset",
"at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]",
"at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]",
"at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:155) ~[transport-netty4-client-2.8.0.jar:2.8.0]",
"at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:140) ~[transport-netty4-client-2.8.0.jar:2.8.0]",
"at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.91.Final.jar:4.1.91.Final]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.91.Final.jar:4.1.91.Final]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.91.Final.jar:4.1.91.Final]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.91.Final.jar:4.1.91.Final]",
"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.91.Final.jar:4.1.91.Final]",
"at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.91.Final.jar:4.1.91.Final]",
"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.91.Final.jar:4.1.91.Final]",
"at java.lang.Thread.run(Thread.java:833) [?:?]"] }
{"type": "server", "timestamp": "2023-07-29T06:28:17,091Z", "level": "INFO", "component": "o.o.i.i.ManagedIndexRunner", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Executing attempt_rollover for playable_events_zc5p6djrsjf-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
{"type": "server", "timestamp": "2023-07-29T06:28:17,093Z", "level": "INFO", "component": "o.o.i.i.ManagedIndexRunner", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Finished executing attempt_rollover for playable_events_zc5p6djrsjf-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
{"type": "server", "timestamp": "2023-07-29T06:28:19,500Z", "level": "INFO", "component": "o.o.j.s.JobScheduler", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Will delay 72055 miliseconds for next execution of job playable_events_gbqt37xfwvk-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
{"type": "server", "timestamp": "2023-07-29T06:28:20,394Z", "level": "INFO", "component": "o.o.i.i.ManagedIndexRunner", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Executing attempt_rollover for playable_events_gbqt37xfwvk-2023.07.12-000001", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }
```

in cloudwatch, I am getting one json object with log as key contains multiple jsons malformed, ideally it should be one json not stringified
```
{
    "log": "2023-07-29T19:33:26.527517102Z stdout F {\"type\": \"server\", \"timestamp\": \"2023-07-29T19:33:26,526Z\", \"level\": \"ERROR\", \"component\": \"o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport\", \"cluster.name\": \"opensearch-cluster\", \"node.name\": \"opensearch-cluster-master-2\", \"message\": \"Exception during establishing a SSL connection: java.net.SocketException: Connection reset\", \"cluster.uuid\": \"ybe8lbVIQfqVOuvUcFXCKA\", \"node.id\": \"yRHnnTQqSceWH4KviLrGow\" , \n2023-07-29T19:33:26.527557528Z stdout F \"stacktrace\": [\"java.net.SocketException: Connection reset\",\n2023-07-29T19:33:26.527561934Z stdout F \"at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]\",\n2023-07-29T19:33:26.527564896Z stdout F \"at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]\",\n2023-07-29T19:33:26.527569244Z stdout F \"at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:155) ~[transport-netty4-client-2.8.0.jar:2.8.0]\",\n2023-07-29T19:33:26.527572239Z stdout F \"at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:140) ~[transport-netty4-client-2.8.0.jar:2.8.0]\",\n2023-07-29T19:33:26.527574857Z stdout F \"at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.527577335Z stdout F \"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.527580042Z stdout F \"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.527582775Z stdout F \"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.527585466Z stdout F \"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.527588091Z stdout F \"at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.527590832Z stdout F \"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.91.Final.jar:4.1.91.Final]\",\n2023-07-29T19:33:26.52760908Z stdout F \"at java.lang.Thread.run(Thread.java:833) [?:?]\"] }\n2023-07-29T19:33:27.007598306Z stdout F {\"type\": \"server\", \"timestamp\": \"2023-07-29T19:33:27,007Z\", \"level\": \"INFO\", \"component\": \"o.o.j.s.JobScheduler\", \"cluster.name\": \"opensearch-cluster\", \"node.name\": \"opensearch-cluster-master-2\", \"message\": \"Will delay 118877 miliseconds for next execution of job playable_events_pjjz4yefgth-2023.07.12-000001\", \"cluster.uuid\": \"ybe8lbVIQfqVOuvUcFXCKA\", \"node.id\": \"yRHnnTQqSceWH4KviLrGow\"  }\n"
}
```

**Comment by waynec86** [comment]
I didn't test this, but I think your multiline regexes try to capture too much. 

try changing your rules to something like:
```
        rule                "start_state"  "/{(.*),$/"  "cont"
        rule                "cont"         "/^[^{].*/"             "cont"
```

Make it so it matches when the start state ends with a comma (invalid json), then the continues matching each subsequent line that does not start with a curly bracket. Hope that helps.

**Comment by ibrahimjelliti** [comment]
hi @waynec86,
I updated with your suggestion, fluentbit starts to push line by line to cloudwatch

**Comment by waynec86** [comment]
@ibrahimjelliti what do you mean? can you show me the output? If I have time I might be able to try this out locally later

**Comment by ibrahimjelliti** [comment]
@waynec86, this was the output.
![image](https://github.com/fluent/fluent-bit/assets/9965888/6496ba74-b578-4515-8ad1-2d2e0de1faea)

the JSON log has `stacktrace` property only when the level is ERROR.
I tried this rules.:
1. start with `{` and match until`"node.id": "sN04VXeURROEG9pLhKos3g" `
2. cont will continue to match `stacktrace` field if available and in both case match `}` at the end
```
        # rules           |   state name  | regex pattern                               | next state  #
        # ----------------|---------------|-----------------------------------------------------------#
        rule                "start_state"   "/^\{(.*)node.id\W:\s\W\w+\W\s*$/"                "cont"
        rule                "cont"          "/(,?\s*\Wstacktrace\W.*(\s*(.*))*])?\s*}$/"      "cont"
```
theoretically it should combine multiline stacktrace json if exists, it works when Level is not Error for now.
