### ISSUE TITLE
use a parser after a multiline parser truncates messages at first carriage return

### ISSUE THREAD

**Issue by squalou** [fluent/fluent-bit#7821]
## Bug Report

**Describe the bug**

I'm trying to use multiline parser THEN a parser to extract data from obtained "reconstituted" message.

multiline part works great, as in the example. I get all lines regrouped in a "log" entry.

When I add a parser filter, only the first line of each message is parsed is sent to output, other lines seems lost. As if "parser" was not able to keep newlines.

**To Reproduce**

- Steps to reproduce the problem:

here's my conf files

```
[SERVICE]
    flush                 1
    log_level             debug
    parsers_file          /fluent-bit/etc/boxtal-fluent-bit-parsers.conf

[INPUT]
    name tail
    path /test.log
    read_from_head true

[FILTER]
        Name                  multiline
        Match                 *
        multiline.key_content log
        multiline.parser      multiline-jenkins


# below is the parser I try to add :  comment out to test the multiline only (which works)
[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       jenkins
    

[OUTPUT]
    Name stdout
    Match *
```
    
```
[PARSER]
    Name   jenkins
    Format regex
    regex   /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+\+\d{4})(\s)+(.id\=)(?<id>[^\s]+).(\s)+(?<level>[^\s]+)(\s)+(?<category>[^:]+):(?<message>.*)/
    Time_Key   time
    Time_Format  %Y-%m-%d %H:%M:%S.%L%z
    Time_Keep   On

[MULTILINE_PARSER]
    name          multiline-jenkins
    type          regex
    flush_timeout 300
    rule      "start_state"   "/(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+\+\d{4})(.*)/"  "cont"
    rule      "cont"          "/^([a-z]+|\s+at).*/"                     "cont"

```

here is a test.log  content to reproduce

```
2023-08-11 08:16:58.832+0000 [id=67096]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.plugins.sonar.SonarRunnerIn
2023-08-02 10:23:37.033+0000 [id=40277]	WARNING	c.c.j.p.amazonecs.ECSLauncher#launch: [factory-jenkins-agent-j9td7]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[factory-jenkins-agent-j9td7]
hudson.AbortException: Failed to run agent container factory-jenkins-agent-j9td7
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.runECSTask(ECSLauncher.java:220)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:149)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-08-02 10:23:45.014+0000 [id=40]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: Asked to provision 1 agent(s) for: jenkins-agent
  ```

**Expected behavior**

In the end I would like to get a log entry with "time" parsed from original message, "level", etc... AND message including all lines.

**Screenshots**

If I comment out the "parser", leaving only the multiline part, result is nicely regrouped, but data not parsed

```
[2023/08/11 14:00:40] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tail.0: [1691762439.792283917, {"log"=>"2023-08-11 07:01:57.533+0000 [id=66216]     WARNING o.j.p.w.s.s.ExecutorStepExecution$AnomalousStatus#lambda$doRun$4: do not know about CpsStepContext[3:node]:Owner[si/factory/snapshot-factory-ebs/119:si/factory/snapshot-factory-ebs #119]"}]
[1] tail.0: [1691762439.792297928, {"log"=>"2023-08-11 07:31:57.535+0000 [id=66568]     WARNING o.j.p.w.s.s.ExecutorStepExecution$AnomalousStatus#lambda$doRun$4: do not know about CpsStepContext[3:node]:Owner[si/factory/snapshot-factory-ebs/119:si/factory/snapshot-factory-ebs #119]"}]
[2] tail.0: [1691762439.792298203, {"log"=>"2023-08-11 08:01:57.535+0000 [id=66915]     WARNING o.j.p.w.s.s.ExecutorStepExecution$AnomalousStatus#lambda$doRun$4: do not know about CpsStepContext[3:node]:Owner[si/factory/snapshot-factory-ebs/119:si/factory/snapshot-factory-ebs #119]"}]
[3] tail.0: [1691762439.792298408, {"log"=>"2023-08-11 08:16:57.968+0000 [id=67096]     INFO    h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller"}]
[4] tail.0: [1691762439.792298608, {"log"=>"2023-08-11 08:16:58.401+0000 [id=67096]     INFO    h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.plugins.sonar.MsBuildSonarQubeRunnerInstaller"}]
[5] tail.0: [1691762439.792298772, {"log"=>"2023-08-11 08:16:58.832+0000 [id=67096]     INFO    h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.plugins.sonar.SonarRunnerIn"}]
[6] tail.0: [1691762439.792298930, {"log"=>"2023-08-02 10:23:37.033+0000 [id=40277]     WARNING c.c.j.p.amazonecs.ECSLauncher#launch: [factory-jenkins-agent-j9td7]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[factory-jenkins-agent-j9td7]
hudson.AbortException: Failed to run agent container factory-jenkins-agent-j9td7
        at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.runECSTask(ECSLauncher.java:220)
        at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:149)
        at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:48)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:82)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)"}]
[2023/08/11 14:00:40] [debug] [out flush] cb_destroy coro_id=0
```

BUT

if I add the parser then ... things are parsed but I loose the stacktrace

```
[2023/08/11 14:02:37] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tail.0: [1691737317.533000000, {"time"=>"2023-08-11 07:01:57.533+0000", "id"=>"66216", "level"=>"WARNING", "category"=>"o.j.p.w.s.s.ExecutorStepExecution$AnomalousStatus#lambda$doRun$4", "message"=>" do not know about CpsStepContext[3:node]:Owner[si/factory/snapshot-factory-ebs/119:si/factory/snapshot-factory-ebs #119]"}]
[1] tail.0: [1691739117.535000000, {"time"=>"2023-08-11 07:31:57.535+0000", "id"=>"66568", "level"=>"WARNING", "category"=>"o.j.p.w.s.s.ExecutorStepExecution$AnomalousStatus#lambda$doRun$4", "message"=>" do not know about CpsStepContext[3:node]:Owner[si/factory/snapshot-factory-ebs/119:si/factory/snapshot-factory-ebs #119]"}]
[2] tail.0: [1691740917.535000000, {"time"=>"2023-08-11 08:01:57.535+0000", "id"=>"66915", "level"=>"WARNING", "category"=>"o.j.p.w.s.s.ExecutorStepExecution$AnomalousStatus#lambda$doRun$4", "message"=>" do not know about CpsStepContext[3:node]:Owner[si/factory/snapshot-factory-ebs/119:si/factory/snapshot-factory-ebs #119]"}]
[3] tail.0: [1691741817.968000000, {"time"=>"2023-08-11 08:16:57.968+0000", "id"=>"67096", "level"=>"INFO", "category"=>"h.m.DownloadService$Downloadable#load", "message"=>" Obtained the updated data file for hudson.tasks.Maven.MavenInstaller"}]
[4] tail.0: [1691741818.401000000, {"time"=>"2023-08-11 08:16:58.401+0000", "id"=>"67096", "level"=>"INFO", "category"=>"h.m.DownloadService$Downloadable#load", "message"=>" Obtained the updated data file for hudson.plugins.sonar.MsBuildSonarQubeRunnerInstaller"}]
[5] tail.0: [1691741818.832000000, {"time"=>"2023-08-11 08:16:58.832+0000", "id"=>"67096", "level"=>"INFO", "category"=>"h.m.DownloadService$Downloadable#load", "message"=>" Obtained the updated data file for hudson.plugins.sonar.SonarRunnerIn"}]
[6] tail.0: [1690971817.033000000, {"time"=>"2023-08-02 10:23:37.033+0000", "id"=>"40277", "level"=>"WARNING", "category"=>"c.c.j.p.amazonecs.ECSLauncher#launch", "message"=>" [factory-jenkins-agent-j9td7]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[factory-jenkins-agent-j9td7]"}]
[2023/08/11 14:02:37] [debug] [out flush] cb_destroy coro_id=0
[2023/08/11 14:02:37] [debug] [task] destroy task=0x7f2e5f244700 (task_id=0)
[2023/08/11 14:02:40] [debug] [input chunk] update output instances with new chunk size diff=185
[2023/08/11 14:02:40] [debug] [task] created task=0x7f2e5f244700 id=0 OK
[2023/08/11 14:02:40] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] tail.0: [1690971825.014000000, {"time"=>"2023-08-02 10:23:45.014+0000", "id"=>"40", "level"=>"INFO", "category"=>"c.c.j.plugins.amazonecs.ECSCloud#provision", "message"=>" Asked to provision 1 agent(s) for: jenkins-agent-openjdk-8"}]
[2023/08/11 14:02:40] [debug] [out flush] cb_destroy coro_id=1
```

**Your Environment**
* Version used: 2.31.11
* Configuration: local docker (linux) 
* Environment name and version : target environment : AWS ECS
* Server type and version: laptop :)
* Operating System and version: linux 6.4.6
* Filters and plugins:

**Additional context**

Trying to get and parse jenkins logs to EKS in the end.

I don't even know if what I'm trying to do is possible, no example found beyond "here's how multiline works" and "here's how a parser work".

**Comment by squalou** [comment]
Solved it !

I think the documentation should mention that in the 'regex parser' part for instance : 

With the regex dialect in use, "." does not include newline chars.

So, in my case, I have to use `(?<message>(.|\n)*)`  instead of `(?<message>(.)*)`
to get the whole 'end' of log message.
