### ISSUE TITLE
ASP .net core Log parser for fluent Bit

### ISSUE THREAD

**Issue by ayushk048-Tandem** [fluent/fluent-bit#7892]
I have the following logs in my pods. but when I see logs in the new relic logs are separated by new lines. So, those logs are not usable..

```logs
[40m[32minfo[39m[22m[49m: Logging_Demo.Controllers.WeatherForecastController[0]
      Request comes for Endpoint /getone
[40m[32minfo[39m[22m[49m: Logging_Demo.Services.WeatherForecastService[0]
      response sent with summary : Freezing
[40m[32minfo[39m[22m[49m: Logging_Demo.Controllers.WeatherForecastController[0]
      Response with Summary : Freezing
[40m[32minfo[39m[22m[49m: Logging_Demo.Controllers.WeatherForecastController[0]
      Request comes for Endpoint /exception
[40m[32minfo[39m[22m[49m: Logging_Demo.Services.WeatherForecastService[0]
      New Random number generated : System.Random
[41m[30mfail[39m[22m[49m: Logging_Demo.Services.WeatherForecastService[0]
      Oppss Error with random number System.ApplicationException: Crashed with System.Random
         at Logging_Demo.Services.WeatherForecastService.TestKnownExceptionHandling() in /src/Services/WeatherForecastService.cs:line 52
[41m[30mfail[39m[22m[49m: Logging_Demo.Middleware.Exceptions.ExceptionHandlingMiddleware[0]
      An Exception occurred while processing the request
      Logging_Demo.Exceptions.CustomException: Oppss Error with random numberSystem.ApplicationException: Crashed with System.Random
         at Logging_Demo.Services.WeatherForecastService.TestKnownExceptionHandling() in /src/Services/WeatherForecastService.cs:line 52
         at Logging_Demo.Services.WeatherForecastService.TestKnownExceptionHandling() in /src/Services/WeatherForecastService.cs:line 56
         at Logging_Demo.Controllers.WeatherForecastController.Exception() in /src/Controllers/WeatherForecastController.cs:line 64
         at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Logging_Demo.Middleware.Exceptions.ExceptionHandlingMiddleware.Invoke(HttpContext context, IWebHostEnvironment env) in /src/Middlewares/Exceptions/ExceptionHandlingMiddleware.cs:line 39
```

my parser
```
[PARSER]
    Name   dotnet_parser
    Format regex
    Regex  ^(?<loglevel>info|warn|fail): (?<namespace>[\w\.-]+)\[(?<index>\d+)\]\s+(?<message>.*)$
    Match  none
    Multiline true
```

Can anyone help me set up the parser so that I can get the whole log in a single parsed message?

new relic logs look like

![image](https://github.com/fluent/fluent-bit/assets/113418592/d61ee57b-b272-4234-816d-4386be4ee0a5)

**Comment by patrick-stephens** [comment]
Can you make sure to follow the template to capture the rest of your config and version?

I think you want to set up multiline parsing either directly in `tail` or via the filter
- https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support
- https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace

Look at the logs on disk for the kubelet in `/var/log/[containers|pods]` or similar (not what a call to `kubectl logs` returns) to see that on disk I bet they're split with separate lines. When you consume those logs you need to consume them into a single entry or combine them later.
