### ISSUE TITLE
Stackdriver MULTILINE Config not working

### ISSUE THREAD

**Issue by Asmokin11** [fluent/fluent-bit#8001]
## Bug Report

**Describe the bug**
I am trying to parse multiline logging using the stackdriver plugin on GCP however the parsing does not work as expected. When I am running the same configuration on my local using "stdout" pluging then the parsing is perfect as needed. However, on GCP it does not work.

**To Reproduce**
**fluentbit.conf**
```
[SERVICE]
    Flush                     5
    Grace                     10
    Log_Level                 debug
    Log_File                  /var/log/fluentbit_custom.log
    storage.path              /var/log/flb-storage/
    storage.max_chunks_up     2048
    storage.backlog.mem_limit 256M
    storage.sync              full
    Daemon                    off
    Parsers_File              parsers.conf
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_Port                 12020

[INPUT]
    Name             tail
    Alias            kube_containers
    Tag              kube.*
    Path             /var/log/containers/*.log
    Exclude_Path     /var/log/containers/*gke-*.log;/var/log/containers/*fluentbit*.log;/var/log/containers/*_kube-system_*.log,/var/log/containers/*_logging_*.log,/var/log/containers/*_ingress-nginx_*.log,/var/log/containers/*_kube-node-lease_*.log,/var/log/containers/*_kube-public_*.log,/var/log/containers/*_cert-manager_*.log,/var/log/containers/*_prometheus-operator_*.log,/var/log/containers/*_istio-system_*.log,/var/log/containers/*_knative-serving_*.log,/var/log/containers/*_gke-system_*.log,/var/log/containers/*_config-management-system_*.log      
    DB               /var/run/flb_kube_custom.db
    storage.type     filesystem
    Refresh_Interval 5
    read_from_head   true
    multiline.parser multiline_stacktrace

[FILTER] #0
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix     kube.var.log.containers.
    tls.vhost           kubernetes.default.svc
    Buffer_Size         0
    Merge_Log           On
    tls.debug           4

[FILTER]
    Name    lua
    Match   *
    script  filters.lua
    call    cb_copy_kubernetes_labels

[FILTER] 
    Name         parser
    Match        kube.*
    Key_Name     log
    Reserve_Data True
    Parser       docker
    Parser       containerd

[FILTER]
    Name        modify
    Match       *
    Hard_rename log message

[FILTER]
    Name         parser
    Match_Regex  kube\.(.*)(gossip|mailserver|reporting)(.*)
    Key_Name     message
    Reserve_Data True
    Parser       containerd_xs2a_default

[FILTER]
    Name        modify
    Match       kube.*
    Copy        level severity

[OUTPUT]
    Name                  stackdriver
    Match                 *
    severity_key          severity
    k8s_cluster_name      gke-cluster
    k8s_cluster_location  europe-west1
    resource              k8s_container
    labels_key            labels
    tag_prefix            kube.var.log.containers.
    workers               0

```
**parsers.conf**
```
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name        containerd
    Format      regex
    Regex       ^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name        containerd_xs2a_routingservice
    Format      regex
    Regex       ^(?<time>([0-9, ,\-,\,,.,:]){19,23})[ ,|,;]*\[\]\s+\[(?<severity>([A-Z,a-z])*)\][ ,|,;]*\s+\[(?<source>([^\]]*))\][ ,|,;]*(?<message>(.)*)$

[PARSER]
    Name        containerd_xs2a_cryptoserver
    Format      regex
    Regex       ^(?<time>([0-9, ,\-,\,,.,:]){19,23})[ ,|,;]*(?<severity>([A-Z,a-z])*)[ ,|,;]*(?<source>([A-Z,a-z,.,0-9,\_])*)[ ,|,;]*(?<message>(.)*)$

[PARSER]
    Name        containerd_xs2a_default
    Format      regex
    Regex       ^(?<message>(.)*)$

[MULTILINE_PARSER]
    name          multiline_stacktrace
    type          regex
    flush_timeout 1000
    rule          "start_state"     "/^(?<time>([0-9, ,\-,\,,.,:]){19,23})[ ,|,;]*\[\]\s+\[(?<severity>([A-Z,a-z])*)\][ ,|,;]*\s+\[(?<source>([^\]]*))\][ ,|,;]*(?<message>(.)*)/" "cont"
    rule          "cont"            "/^\s+at.*/" "cont"                                                                                                                              "cont"
```
**Example logfile.log**
```
2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
Dec 14 06:41:08 Exception [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)

```
**Example logfile-2.log**
```
2023-10-03 15:17:14,006 [] [FINE] [org.apache.cxf.phase.PhaseInterceptorChain] [default task-23] - Invoking handleMessage on interceptor net.atos.wlp.core.messaging.rest.logging.CustomLoggingInInterceptor$LoggingInFaultInterceptor@34c2dd3a
2023-10-03 15:17:14,007 [] [FINE] [org.apache.cxf.phase.PhaseInterceptorChain] [default task-23] - Invoking handleMessage on interceptor org.apache.cxf.transport.https.CertConstraintsInterceptor@70e7b24d
2023-10-03 15:17:14,007 [] [FINE] [org.apache.cxf.phase.PhaseInterceptorChain] [default task-23] - Invoking handleMessage on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor@281e1a96
2023-10-03 15:17:14,013 [] [ERROR] [com.equensworldline.genericRS.webservice.error.RuntimeExceptionMapper] [default task-23] - WebApplicationException: HTTP 401 Unauthorized: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
        at org.apache.cxf.jaxrs.utils.SpecExceptions.toNotAuthorizedException(SpecExceptions.java:94)
        at org.apache.cxf.jaxrs.utils.ExceptionUtils.toNotAuthorizedException(ExceptionUtils.java:136)
        at org.apache.cxf.rs.security.oauth2.utils.AuthorizationUtils.throwAuthorizationFailure(AuthorizationUtils.java:117)
        at org.apache.cxf.rs.security.oauth2.utils.AuthorizationUtils.throwAuthorizationFailure(AuthorizationUtils.java:92)
        at org.apache.cxf.rs.security.oauth2.utils.AuthorizationUtils.getAuthorizationParts(AuthorizationUtils.java:83)
        at org.apache.cxf.rs.security.oauth2.utils.AuthorizationUtils.getAuthorizationParts(AuthorizationUtils.java:67)
        at com.equensworldline.webservice.api.internal.oauth.OAuthRequestFilter.getAuthorizationParts(OAuthRequestFilter.java:279)
        at com.equensworldline.webservice.api.internal.oauth.OAuthRequestFilter.validateRequest(OAuthRequestFilter.java:141)
        at com.equensworldline.webservice.api.internal.oauth.OAuthRequestFilter.filter(OAuthRequestFilter.java:84)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerRequestFilters(JAXRSUtils.java:1883)
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:110)
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:79)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
```
**Òutput using stdout on my local**
```
[2023/10/03 14:29:03] [debug] [input chunk] update output instances with new chunk size diff=1277, records=1, input=emitter_for_multiline.0
[2023/10/03 14:29:04] [debug] [task] created task=0x7ff37006d160 id=0 OK
[2023/10/03 14:29:04] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] my_multiline_logs: [[1696343339.992064400, {}], {"log"=>"2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
"}]
[1] my_multiline_logs: [[1696343339.992083600, {}], {"log"=>"2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
"}]
[2] my_multiline_logs: [[1696343339.992098100, {}], {"log"=>"2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
"}]
[3] my_multiline_logs: [[1696343339.992108500, {}], {"log"=>"2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
"}]
[4] my_multiline_logs: [[1696343339.992114100, {}], {"log"=>"2023-09-26 10:25:48,492 [] [ERROR] [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
"}]
[5] my_multiline_logs: [[1696343339.992114100, {}], {"log"=>"Dec 14 06:41:08 Exception [org.apache.activemq.artemis.core.client] [Thread-8 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@2e310110)] - AMQ214016: Failed to create netty connection: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /100.85.8.39:8081
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
"}]
[2023/10/03 14:29:04] [debug] [out flush] cb_destroy coro_id=0
[2023/10/03 14:29:04] [debug] [task] destroy task=0x7ff37006d160 (task_id=0)
^C[2023/10/03 14:29:12] [engine] caught signal (SIGINT)
[2023/10/03 14:29:12] [ warn] [engine] service will shutdown in max 10 seconds
[2023/10/03 14:29:12] [ info] [input] pausing tail.0
[2023/10/03 14:29:12] [ info] [engine] service has stopped (0 pending tasks)
```
- Steps to reproduce the problem:
1. Deploy custom fluentbit as a helm chart on GKE with the above configurations.
2. Generate test log for the application.

**Expected behavior**
Each multiline should be parsed with the multiline parser but it is not the case.

**Screenshots**
**Output when seen on GCP Stackdriver**
![image](https://github.com/fluent/fluent-bit/assets/56644272/b153330d-8ec2-4aa2-af1b-f6ea7fb663da)

**Your Environment**

* Version used: Fluent Bit v2.1.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v 1.27.3-gke.100
* Server type and version:
* Operating System and version: Container optimized OS
* Filters and plugins: Attached above

**Additional context**

The log parser is only able to parse single line log entries and treats the multiline logs as separate log entries. There are also different type of multiline logs generated which also need to be parsed correctly.

**Comment by Asmokin11** [comment]
Anyone ? The error in the pod itself also doesnt show anything, only `[2023/11/17 09:58:04] [error] [lib] backend failed`
