### ISSUE TITLE
SIGABRT on realloc() in Elasticsearch 

### ISSUE THREAD

**Issue by gavenkoa** [fluent/fluent-bit#8388]
Installed from RHEL subscription repositories:

```
bash# fluent-bit --version
Fluent Bit v1.9.7

bash# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
```

Crashes a few times everyday on all servers:

```
bash# sudo coredumpctl list
TIME                            PID UID GID SIG     COREFILE EXE                   SIZE
Tue 2023-11-28 13:13:37 IST     987   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Tue 2023-11-28 15:18:07 IST  280427   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Tue 2023-11-28 16:53:12 IST  562054   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Wed 2023-11-29 12:07:42 IST  776742   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Thu 2023-11-30 06:47:07 IST 3395063   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Thu 2023-11-30 17:38:37 IST 1741756   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Thu 2023-11-30 18:53:17 IST 3218104   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Fri 2023-12-01 09:10:52 IST 3386931   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Fri 2023-12-01 12:16:27 IST 1138251   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Fri 2023-12-01 16:13:32 IST 1559030   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Fri 2023-12-01 16:20:22 IST 2093981   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Sat 2023-12-02 18:02:32 IST 2109509   0   0 SIGABRT none     /usr/bin/fluent-bit      -
Sun 2023-12-03 05:41:37 IST 1405488   0   0 SIGABRT none     /usr/bin/fluent-bit      -
```

During the crash in `/var/log/messages`:

```
Jan 12 21:45:27 prod-1 fluent-bit[394261]: Fatal glibc error: malloc.c:2496 (sysmalloc): assertion failed:
  (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
```

or more frequently:

```
Jan 15 11:10:32 prod-1 fluent-bit[3547615]: realloc(): invalid next size
```

Stacktrace is without line numbers - the servers are restricted:

```
(gdb) info threads
  Id   Target Id                           Frame
* 1    Thread 0x7f02bebec640 (LWP 1317125) 0x00007f02c06a154c in __pthread_kill_implementation () from /lib64/libc.so.6
  2    Thread 0x7f02bfbee640 (LWP 1317123) 0x00007f02c074e84e in epoll_wait () from /lib64/libc.so.6
  3    Thread 0x7f02c0892ac0 (LWP 1317121) 0x00007f02c0713975 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  4    Thread 0x7f02be3eb640 (LWP 1317126) 0x00007f02c074e84e in epoll_wait () from /lib64/libc.so.6
  5    Thread 0x7f02bf3ed640 (LWP 1317124) 0x00007f02c074e84e in epoll_wait () from /lib64/libc.so.6
  6    Thread 0x7f02c03ef640 (LWP 1317122) 0x00007f02c074e84e in epoll_wait () from /lib64/libc.so.6
  7    Thread 0x7f02bd3e9640 (LWP 1317128) 0x00007f02c074e84e in epoll_wait () from /lib64/libc.so.6
  8    Thread 0x7f02bdbea640 (LWP 1317127) 0x00007f02c0713975 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f02c06a154c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f02c0654d06 in raise () from /lib64/libc.so.6
#2  0x00007f02c06287f3 in abort () from /lib64/libc.so.6
#3  0x00007f02c0629130 in __libc_message.cold () from /lib64/libc.so.6
#4  0x00007f02c06ab617 in malloc_printerr () from /lib64/libc.so.6
#5  0x00007f02c06aef7c in _int_realloc () from /lib64/libc.so.6
#6  0x00007f02c06afc2b in realloc () from /lib64/libc.so.6
#7  0x000056381c245930 in es_bulk_append ()
#8  0x000056381c2497fc in elasticsearch_format.lto_priv ()
#9  0x000056381c24a49b in cb_es_flush.lto_priv ()
#10 0x000056381c3fba40 in ?? ()
#11 0x00007f02b4006ee0 in ?? ()
#12 0x0000000000000021 in ?? ()
#13 0x00007f02b40412c0 in ?? ()
#14 0x00007f02b4000090 in ?? ()
```

It could be that the problem is fixed by #5770, the fix missed v1.9.8 and we are using RHEL package v1.9.7. I'm trying to update to 2.x

**Comment by nokute78** [comment]
Could you try latest version ?

See also:
https://github.com/fluent/fluent-bit/issues/4412
