### ISSUE TITLE
log_file may be used after free which cause generating garbage files

### ISSUE THREAD

**Issue by hiroyha1** [fluent/fluent-bit#8429]
## Bug Report

**Describe the bug**

`flb_free(config->log_file)` is called in [flb_config_exit](https://github.com/fluent/fluent-bit/blob/master/src/flb_config.c#L394) without waiting for stopping the child worker (`pthread_join(log->tid, NULL)`). Because of that, it may write log to a file with a corrupted filename.

**To Reproduce**

It is difficult to reproduce in the latest version because it is a timing issue. However, we can easily confirm this issue under certain conditions (see **Your Environment**).

1. `systemctl stop azuremonitor-agentlauncher.service`
   - This operation terminates fluent-bit.
   - I am using azure monitor agent which depends on fluent-bit, but I don't think it is an azure monitor.
2. Garbage files are generated in the root directory.

```sh
[root@vm2 azureuser]# find / -maxdepth 1 -type f -name "p*"
/pF??
/p65?
/pf??
/p&?
/p6?
[root@vm2 azureuser]# find / -maxdepth 1 -type f -name "p*" | xargs cat
cat: /pF: No such file or directory
cat: : No such file or directory
[2024/01/28 03:02:17] [ warn] [engine] service will stop in 5 seconds
[2024/01/28 03:02:17] [ warn] [engine] service will stop in 5 seconds
[2024/01/28 03:02:21] [ info] [engine] service stopped
[2024/01/28 03:02:21] [ info] [input] pausing tail.0
[2024/01/28 03:13:14] [ info] [engine] service stopped
[2024/01/28 03:13:14] [ info] [input] pausing tail.0
```

After investigation, I found that the following code has overwritten the `flb_config.log_file` (it points the same address with `flb_log.out`).

```
(gdb) x/56c *0xae2870
0xae2000:       47 '/'  118 'v' 97 'a'  114 'r' 47 '/'  111 'o' 112 'p' 116 't'
0xae2008:       47 '/'  109 'm' 105 'i' 99 'c'  114 'r' 111 'o' 115 's' 111 'o'
0xae2010:       102 'f' 116 't' 47 '/'  97 'a'  122 'z' 117 'u' 114 'r' 101 'e'
0xae2018:       109 'm' 111 'o' 110 'n' 105 'i' 116 't' 111 'o' 114 'r' 97 'a'
0xae2020:       103 'g' 101 'e' 110 'n' 116 't' 47 '/'  108 'l' 111 'o' 103 'g'
0xae2028:       47 '/'  102 'f' 108 'l' 117 'u' 101 'e' 110 'n' 116 't' 98 'b'
0xae2030:       105 'i' 116 't' 46 '.'  108 'l' 111 'o' 103 'g' 0 '\000'        0 '\000'
(gdb) c 
Continuing.
[Switching to Thread 0x7f002e1ea980 (LWP 1235)]
Hardware watchpoint 8: *(char*)0xae2000

Old value = 47 '/'
New value = 112 'p'
0x00007f002d149f03 in _int_free () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f002d149f03 in _int_free () from /lib64/libc.so.6
#1  0x000000000043560c in flb_config_exit ()
#2  0x0000000000438338 in flb_engine_shutdown ()
#3  0x000000000043886e in flb_engine_start ()
#4  0x0000000000427ac2 in main ()
(gdb) x/56c *0xae2870
0xae2000:       112 'p' 54 '6'  -82 '\256'      0 '\000'        0 '\000'        0 '\000'     0 '\000'        0 '\000'                                                     │
0xae2008:       47 '/'  109 'm' 105 'i' 99 'c'  114 'r' 111 'o' 115 's' 111 'o'
0xae2010:       102 'f' 116 't' 47 '/'  97 'a'  122 'z' 117 'u' 114 'r' 101 'e'
0xae2018:       109 'm' 111 'o' 110 'n' 105 'i' 116 't' 111 'o' 114 'r' 97 'a'
0xae2020:       103 'g' 101 'e' 110 'n' 116 't' 47 '/'  108 'l' 111 'o' 103 'g'
0xae2028:       47 '/'  102 'f' 108 'l' 117 'u' 101 'e' 110 'n' 116 't' 98 'b'
0xae2030:       105 'i' 116 't' 46 '.'  108 'l' 111 'o' 103 'g' 0 '\000'        0 '\000'
```

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: v1.3.11 (included in Azure Monitor Agent v1.28.11)
  * The reason we are using an older version is that the latest version has changed where [the log](https://github.com/fluent/fluent-bit/blob/e42448524507a42287d4c0d8cc391f757f89e2dc/src/flb_engine.c#L535) is output. But I think the potential problem still exists.
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: RHEL 7.9
* Filters and plugins:

**Additional context**

**Comment by hiroyha1** [comment]
It can be reproduced in the latest main branch code.

```sh
$ cd build/
$ cmake ../ -DFLB_VALGRIND=Yes
$ make
$ cat test.sh
#!/bin/bash

while true
do
  valgrind --log-file=valgrind.log ./bin/fluent-bit -i cpu -o stdout -f 1 -l fluent-bit.log &
  pid=$!
  random_seconds=$((RANDOM % 21 + 10))
  sleep $random_seconds
  kill -15 $pid
  sleep 10
  grep -q unaddressable valgrind.log
  [[ $? -eq 0 ]] && break
done
$ ./bin/fluent-bit --version
Fluent Bit v3.0.0
Git commit: 9c3978cdaf932ca3756bd7d015c978d016544b04
$ ./test.sh
```

```
$ cat valgrind.log
==25657== Memcheck, a memory error detector
==25657== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25657== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==25657== Command: ./bin/fluent-bit -i cpu -o stdout -f 1 -l fluent-bit.log
==25657== Parent PID: 25648
==25657==
==25657== Thread 3 flb-logger:
==25657== Syscall param openat(filename) points to unaddressable byte(s)
==25657==    at 0x4FA15B4: open (open64.c:41)
==25657==    by 0x1E91CD: log_push (flb_log.c:74)
==25657==    by 0x1E9326: log_read (flb_log.c:107)
==25657==    by 0x1E943D: log_worker_collector (flb_log.c:134)
==25657==    by 0x277BDF: step_callback (flb_worker.c:43)
==25657==    by 0x4F21AC2: start_thread (pthread_create.c:442)
==25657==    by 0x4FB2A03: clone (clone.S:100)
==25657==  Address 0x50ed9c0 is 0 bytes inside a block of size 15 free'd
==25657==    at 0x484B27F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==25657==    by 0x22E694: flb_free (flb_mem.h:127)
==25657==    by 0x2362C3: flb_config_exit (flb_config.c:394)
==25657==    by 0x1E7A6A: flb_destroy (flb_lib.c:242)
==25657==    by 0x1D24BA: flb_main (fluent-bit.c:1445)
==25657==    by 0x1D24FB: main (fluent-bit.c:1456)
==25657==  Block was alloc'd at
==25657==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==25657==    by 0x22E647: flb_malloc (flb_mem.h:80)
==25657==    by 0x22E6B7: flb_strndup (flb_str.h:34)
==25657==    by 0x22E71E: flb_strdup (flb_str.h:46)
==25657==    by 0x236D98: flb_config_set_property (flb_config.c:681)
==25657==    by 0x237871: flb_config_load_config_format (flb_config.c:924)
==25657==    by 0x1D1000: service_configure (fluent-bit.c:765)
==25657==    by 0x1D2163: flb_main (fluent-bit.c:1298)
==25657==    by 0x1D24FB: main (fluent-bit.c:1456)
==25657==
==25657==
==25657== HEAP SUMMARY:
==25657==     in use at exit: 0 bytes in 0 blocks
==25657==   total heap usage: 1,957 allocs, 1,957 frees, 4,718,453 bytes allocated
==25657==
==25657== All heap blocks were freed -- no leaks are possible
==25657==
==25657== For lists of detected and suppressed errors, rerun with: -s
==25657== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by hiroyha1** [comment]
not stale
