### ISSUE TITLE
fluent-bit 2.1.4 SIGSEGV on cio_file_is_up, cf=0.

### ISSUE THREAD

**Issue by oleg-45435** [fluent/fluent-bit#8482]
## Bug Report

**Describe the bug**
I am running fluent-bit as a deployment in k3s environment. Pod - s6, fluent-bit.  On delete pod sometimes receive segmentation fault. 

**To Reproduce**

from the fluent-bit log:

```
[engine] caught signal (SIGSEGV)
#0  0x557d70581600      in  cio_file_is_up() at lib/chunkio/src/cio_file.c:1253
#1  0x557d7057d2d0      in  cio_chunk_is_up() at lib/chunkio/src/cio_chunk.c:520
#2  0x557d7057e3a2      in  cio_stats_get() at lib/chunkio/src/cio_stats.c:55
#3  0x557d6fdbe1bf      in  dump_storage() at src/flb_dump.c:210
#4  0x557d6fdbe325      in  flb_dump() at src/flb_dump.c:254
#5  0x557d6fdb9227      in  flb_signal_handler() at src/fluent-bit.c:605
#6  0x7fad12e7451f      in  ???() at ???:0
#7  0x557d6fdb8d33      in  flb_signal_handler_break_loop() at src/fluent-bit.c:500
#8  0x7fad12e7451f      in  ???() at ???:0
#9  0x557d7057f225      in  crc_init() at lib/chunkio/deps/crc32/crc32.h:75
#10 0x557d70580320      in  cio_file_open() at lib/chunkio/src/cio_file.c:596
#11 0x557d7057c884      in  cio_chunk_open() at lib/chunkio/src/cio_chunk.c:81
#12 0x557d6fdf5b55      in  flb_input_chunk_create() at src/flb_input_chunk.c:964
#13 0x557d6fdf664f      in  input_chunk_get() at src/flb_input_chunk.c:1268
#14 0x557d6fdf7128      in  input_chunk_append_raw() at src/flb_input_chunk.c:1639
#15 0x557d6fdf7cba      in  flb_input_chunk_append_raw() at src/flb_input_chunk.c:1989
#16 0x557d6fee68b0      in  input_log_append() at src/flb_input_log.c:71
#17 0x557d6fee6a1a      in  flb_input_log_append_records() at src/flb_input_log.c:119
#18 0x557d6ffd1bab      in  process_content() at plugins/in_tail/tail_file.c:603
#19 0x557d6ffd4747      in  flb_tail_file_chunk() at plugins/in_tail/tail_file.c:1413
#20 0x557d6ffbcdfe      in  in_tail_collect_event() at plugins/in_tail/tail.c:331
#21 0x557d6ffc1eae      in  tail_fs_event() at plugins/in_tail/tail_fs_inotify.c:276
#22 0x557d6fdf0118      in  flb_input_collector_fd() at src/flb_input.c:1924
#23 0x557d6fe3024b      in  flb_engine_handle_event() at src/flb_engine.c:503
#24 0x557d6fe3024b      in  flb_engine_start() at src/flb_engine.c:866
#25 0x557d6fdcfb75      in  flb_lib_worker() at src/flb_lib.c:638
#26 0x7fad12ec6ac2      in  ???() at ???:0
#27 0x7fad12f5884f      in  ???() at ???:0
#28 0xffffffffffffffff  in  ???() at ???:0
```

from the coredump:

```
(gdb) frame 8
#8  0x0000557d7057d2d1 in cio_chunk_is_up (ch=0x7fad0c24faf0) at ./lib/chunkio/src/cio_chunk.c:520
520             return cio_file_is_up(ch, cf);
(gdb) l
515         if (type == CIO_STORE_MEM) {
516             return CIO_TRUE;
517         }
518         else if (type == CIO_STORE_FS) {
519             cf = ch->backend;
520             return cio_file_is_up(ch, cf);
521         }
522
523         return CIO_FALSE;
524     }
(gdb) p cf
$34 = (struct cio_file *) 0x0
(gdb) frame 7
#7  0x0000557d70581600 in cio_file_is_up (ch=0x7fad0c24faf0, cf=0x0) at ./lib/chunkio/src/cio_file.c:1253
1253        if (cio_file_native_is_open(cf) &&
(gdb) p cf
$35 = (struct cio_file *) 0x0
(gdb) p cf->fd
Cannot access memory at address 0x0
```

`cio_file_native_is_open` define as 
```
./lib/chunkio/include/chunkio/cio_file_native.h:
#define cio_file_native_is_open(cf) (cf->fd != -1)
```

This issue related to https://github.com/fluent/fluent-bit/issues/6492

**Your Environment**
* Version used: 2.1.4
* Configuration: pod - s6, fluent-bit.
* Environment name and version (e.g. Kubernetes? What version?): k3s
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Comment by YukkiKaze** [comment]
encounter same problem:

```
(gdb) bt
#0  0x00007f30670b61f7 in raise () from /lib64/libc.so.6
#1  0x00007f30670b78e8 in abort () from /lib64/libc.so.6
#2  0x0000000000438d25 in flb_signal_handler ()
#3  <signal handler called>
#4  0x0000000000744bb9 in cio_file_is_up ()
#5  0x0000000000741065 in cio_chunk_is_up ()
#6  0x0000000000742098 in cio_stats_get ()
#7  0x000000000043a910 in dump_storage ()
#8  0x000000000043aa56 in flb_dump ()
#9  0x0000000000438d3b in flb_signal_handler ()
#10 <signal handler called>
#11 0x0000000000438adf in flb_signal_handler ()
#12 <signal handler called>
#13 0x00007f3067101ab0 in calloc () from /lib64/libc.so.6
#14 0x0000000000743942 in cio_file_open ()
#15 0x000000000074083c in cio_chunk_open ()
#16 0x000000000047b897 in flb_input_chunk_create ()
#17 0x000000000047be2c in input_chunk_get ()
#18 0x000000000047c363 in flb_input_chunk_append_raw ()
#19 0x00000000004947cf in process_content ()
#20 0x00000000004964b7 in flb_tail_file_chunk ()
#21 0x0000000000490d5f in in_tail_collect_event ()
#22 0x000000000049b4bf in tail_fs_event ()
#23 0x000000000044f4b5 in flb_input_collector_fd ()
#24 0x000000000045f8cd in flb_engine_start ()
#25 0x0000000000444ff6 in flb_lib_worker ()
#26 0x00007f3067d6fe25 in start_thread () from /lib64/libpthread.so.0
#27 0x00007f306717934d in clone () from /lib64/libc.so.6
```

**Comment by scheinbash** [comment]
Any update? This is waiting for triage for over a month.

**Comment by scheinbash** [comment]
Update? Now, over 2 months, waiting for an answer.
