### ISSUE TITLE
fluent-bit 2.1.4 SIGSEGV on cio_chunk_is_up, cf - incorrect memory address.

### ISSUE THREAD

**Issue by oleg-45435** [fluent/fluent-bit#8483]
## Bug Report

**Describe the bug**
I am running fluent-bit as a deployment in k3s environment. Pod - s6, fluent-bit. On delete pod fluent-bit sometimes receive SIGSEGV.

**To Reproduce**

from the coredump:

```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139720705674048) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139720705674048) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139720705674048, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f13430bf476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f13430a57f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000556e34db1240 in flb_signal_handler (signal=11) at ./src/fluent-bit.c:602
#6  <signal handler called>
#7  0x0000556e35576e86 in cio_chunk_is_up (ch=0xffffffffffffffb0) at ./lib/chunkio/src/cio_chunk.c:514
#8  0x0000556e35577f93 in cio_stats_get (ctx=0x7f133c00c780, stats=0x7fff1deba7b0)
    at ./lib/chunkio/src/cio_stats.c:55
#9  0x0000556e34db61e8 in dump_storage (ctx=0x556e35e17430) at ./src/flb_dump.c:210
#10 0x0000556e34db634e in flb_dump (ctx=0x556e35e17430) at ./src/flb_dump.c:254
#11 0x0000556e34db1250 in flb_signal_handler (signal=18) at ./src/fluent-bit.c:605
#12 <signal handler called>
#13 flb_signal_handler_break_loop (signal=32531) at ./src/fluent-bit.c:500
#14 <signal handler called>
...

(gdb) frame 7
#7  0x0000556e35576e86 in cio_chunk_is_up (ch=0xffffffffffffffb0) at ./lib/chunkio/src/cio_chunk.c:514
514         type = ch->st->type;
(gdb) p ch
$4 = (struct cio_chunk *) 0xffffffffffffffb0
(gdb) p ch->st
Cannot access memory at address 0xffffffffffffffe0
```

**Your Environment**

* Version used: 2.1.4
* Configuration:  s6, fluent-bit.
* Environment name and version (e.g. Kubernetes? What version?): k3s
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Comment by scheinbash** [comment]
Any update? This is waiting for triage for over a month.

**Comment by scheinbash** [comment]
Update? Now, over 2 months, waiting for an answer.
