### ISSUE TITLE
Can't fetch messages  when using multiline  parsers of  input 

### ISSUE THREAD

**Issue by jackchen-2014** [fluent/fluent-bit#8520]
## Bug Report

**Describe the bug**

I hope to collect the following log information. There is a line of spaces in the log information. In the multi-line configuration of the tail plug-in using fluent-bit, an exception message appears
```
[2024/02/26 01:40:56] [debug] [input:tail:tail.0] 0 new files found on path '/tmp/app/log/default.log'
[2024/02/26 01:40:56] [debug] [input:tail:tail.0] inode=190579818, /tmp/app/log/console.log, events: IN_MODIFY
[2024/02/26 01:40:56] [error] [input:tail:tail.0] error packing event : -4
[2024/02/26 01:40:57] [debug] [input:tail:tail.0] inode=190579818, /tmp/app/log/console.log, events: IN_MODIFY
```
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:

Log Message：
```
2024-02-24 17:31:18.606 ERROR [im-cloudnative-consumer,76beb9edd2f711eeb16f093add71abd4,2e3b1343e4374c00,] 246 --- [   s-biz-work-9] c.b.c.s.core.rpc.RpcServiceInvoker       : Failed to execute method genMetricData, caused by

    java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

- Steps to reproduce the problem:

**Expected behavior**

I hope to be able to extract
time: `2024-02-24 17:31:18.606`
level: `ERROR`
traceid: `76beb9edd2f711eeb16f093add71abd4`
spanId:`2e3b1343e4374c00`
appName:`im-cloudnative-consumer`
threadName: `s-biz-work-9`
log: 
```
2024-02-24 17:31:18.606 ERROR [im-cloudnative-consumer,76beb9edd2f711eeb16f093add71abd4,2e3b1343e4374c00,] 246 --- [   s-biz-work-9] c.b.c.s.core.rpc.RpcServiceInvoker       : Failed to execute method genMetricData, caused by

    java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Screenshots**

**Your Environment**

* Version used:  fluent-bit-2.2.2
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):  Kubernetes 1.8.9 
* Server type and version:
* Operating System and version:  centos7 
* Filters and plugins:

The configuration in fluent-bit is as follows：
input.conf
```
[INPUT]
    name              tail
    tag               file-log
    path              /tmp/app/log/console.log,/tmp/app/log/error.log,/tmp/app/log/default.log
    Multiline         On
    Multiline_Flush   20
    Parser_Firstline  multiline-start-parser
    Parser_1          multiline-parser
    mem_Buf_Limit     50MB
    skip_Long_Lines   On
    refresh_Interval  10
```

PARSER.conf
```
[PARSER]
    Name          multiline-parser
    Format        regex
    Regex         (?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s+(?<level>\w+)\s+\[(?:(?<appName>[^,\]]*),)?(?:(?<traceId>[^,\]]*),)?(?:(?<spanId>[^,\]]*),)?(?:[^,\]]*)?\]\s+\d+\s+---\s+\[(?<threadName>[^\]]*)\]\s+(?<log>(\s|\S)+)
    Time_Key      time
    Time_Format   %Y-%m-%d %H:%M:%S.%L

[PARSER]
    Name          multiline-start-parser
    Format        regex
    Regex         (?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s+(?<level>\w+)\s+\[(?:(?<appName>[^,\]]*),)?(?:(?<traceId>[^,\]]*),)?(?:(?<spanId>[^,\]]*),)?(?:[^,\]]*)?\]\s+\d+\s+---\s+\[(?<threadName>[^\]]*)\]\s+(?<log>.*)$
    Time_Key      time
    Time_Format   %Y-%m-%d %H:%M:%S.%L
```
fluent-bit.conf
```
[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        1

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    debug
    log_file     /home/work/fluent-bit/log/console.log

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  On
    http_listen  0.0.0.0
    http_port    2020
    # Hot Reload    curl -X POST -d '{}' localhost:2020/api/v2/reload  内容必须是空的
    # 或者 PUT /api/v2/reload
    Hot_Reload   On

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    # storage.path /tmp/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    # storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    # storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    # storage.backlog.mem_limit 5M

```
output.conf
```
[OUTPUT]
    Name             loki
    Match            file-log
    host               ${loki}
    port               ${port}
    labels           appName=${EM_APP},podIp=${EM_IP},podName=${EM_INSTANCE_ID},podPort=${EM_PORT},traceId=$traceId,spanId=$spanId
    uri              /insert/loki/api/v1/push?_stream_fields=appName,podIp,podName,podPort&_msg_field=log&_time_field=time&debug=1
    line_format      json
```

Currently, the collection is abnormal and sending to the remote service fails. How can I configure it to correctly obtain and extract the information I need?

**Additional context**

**Comment by jiping-s** [comment]
the problem still exists in v3.2.9
