### ISSUE TITLE
Adding "\n" while using multiline.parser with Tail

### ISSUE THREAD

**Issue by duj4** [fluent/fluent-bit#8914]
## Bug Report

**Describe the bug**
“\n” will be added when using multiline.parser.

**To Reproduce**
The simplest one is the official one:
before:
```
single line...
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
another line...
```
 after:
```
[0] tail.0: [0.000000000, {"log"=>"single line...
"}]
[1] tail.0: [1626634867.472226330, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)
"}]
[2] tail.0: [1626634867.472226330, {"log"=>"another line...
"}]
```

**Expected behavior**
Both single line and multi-line logs should be as still, no "\n" is added:
```
[0] tail.0: [0.000000000, {"log"=>"single line..."}]
[1] tail.0: [1626634867.472226330, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)"}]
[2] tail.0: [1626634867.472226330, {"log"=>"another line..."}]
```
![image](https://github.com/fluent/fluent-bit/assets/19278537/56ed868a-85af-42f5-af04-9a22250f0e51)

**Screenshots**
Another example in my own case:

multiline-parser:
![image](https://github.com/fluent/fluent-bit/assets/19278537/5e41630f-b9bd-4a85-a224-4dc53acfab3c)

parser:
![image](https://github.com/fluent/fluent-bit/assets/19278537/d00c1070-831f-4bab-8ba5-435b154cfe5e)

before:
![image](https://github.com/fluent/fluent-bit/assets/19278537/c512a094-7320-4068-b8fe-598b9284721c)

after:
![image](https://github.com/fluent/fluent-bit/assets/19278537/b5cfe1eb-557a-404c-a832-83c14d15cabb)

**Your Environment**
* Version used: v3.0.6
* Configuration: as screenshot above
* Environment name and version (e.g. Kubernetes? What version?): VM
* Server type and version: Linux
* Operating System and version: RHEL8

**Comment by duj4** [comment]
Same issue had been opened in https://github.com/fluent/fluent-bit/issues/4227 but without any further update.

**Comment by duj4** [comment]
Thanks @patrick-stephens 's suggestion, Lua can remove the last "\n" but it will twist the record order:
![image](https://github.com/fluent/fluent-bit/assets/19278537/3886a1e6-ddf1-4c4e-9078-39f5944c3fcf)

Any further suggestion would be appreciated.

**Comment by lecaros** [comment]
hi there.
What's the impact of this issue other than the visualization in stdout?

**Comment by duj4** [comment]
hi @lecaros , thanks for the reply.

The impact I could see for now is the visualization in either output or Grafana, but that's not a big deal, you may close this one for now.

**Comment by patrick-stephens** [comment]
Is it actually impacting Grafana though? New lines should be displayed as they are present - I think that would be a visualisation option for Grafana though to deal with, not Fluent Bit which should pass the data as-is and leave to whatever is downstream to cope with.

**Comment by trallnag** [comment]
@patrick-stephens while it only impacts visuals, isn't it a bug nevertheless? For me it is unexpected that turning on multiline parser introduces newline at the end of log statements, whereas without multiline parser the newline is stripped away silently

**Comment by trallnag** [comment]
@duj4 can you share how you solved it with a custom parser? Your screenshot indicates that you used a parser pipeline step?

**Comment by trallnag** [comment]
@duj4 ok, i see. I missed that you were using a custom parser, I encountered the issue with a built in multiline parser.

I've now set up the Lua workaround and with that for me it looks alright. 

Can you share what you meant by Lua twisting around records?

**Comment by trallnag** [comment]
@duj4 thanks, now I understand. For example without Lua tid was in third place, with Lua it's last. I think that's just how Lua works after googling around a bit. Thankfully for me that's not a problem

**Comment by duj4** [comment]
@trallnag glad to know that :D
