### ISSUE TITLE
Missing time field when multiline parsing

### ISSUE THREAD

**Issue by luki530** [fluent/fluent-bit#9378]
## Bug Report

**Problem Description**:
In Fluent Bit version 3.1 (1.9.10 as well), when using a multiline parser configured through a custom regex, I am experiencing an issue where only the first parsed multiline log entry retains its unique timestamp. Subsequent multiline log entries processed by the multiline parser are all stamped with the same timestamp as the first multiline log entry. It is similar to https://github.com/fluent/fluent-bit/issues/6948. 

**Steps to Reproduce**:
1. Setup Fluent Bit with the provided configuration which includes a custom regex multiline parser.
2. Generate and monitor logs that fit the multiline pattern designed in the parsers configuration, particularly those that start with "Exception in ASGI application" and follow the specified exception stack trace format.
3. Observe that all subsequent log entries after the first log entry share the same timestamp as the first.

**Expected behavior**:
Each multiline log entry should maintain its own correct timestamp.

**Configuration**:
```plaintext
fluent-bit.conf:

[SERVICE]
  Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
  Name tail
  Path /fluent-bit/etc/fluentbit-input.txt

[FILTER]
  Name multiline
  Match *
  Multiline_Parser multiline-custom-regex

[OUTPUT]
  Name stdout
  Match *


parsers.conf:

[MULTILINE_PARSER]
  name          multiline-custom-regex
  type          regex
  key_content   log
  flush_timeout 500
  rule          "start_state"  "/^.*Exception in ASGI application.*/"  "python_error"
  rule          "python_error" "/^(?!\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\]).*/"  "python_error"
```

Logs/Screenshots: 
Here is the input demonstrating the timestamp issue with multiline logs:
```
[2024-09-07 04:55:37,380] ERROR: "X-Request-Id: " 'url' must be provided in the request parameters                                                                                                                                                                  ─╯
 Exception in ASGI application
Traceback (most recent call last):
  File "/path/to/python_app/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app
  File "/path/to/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/path/to/application/app/main.py", line 323, in handle_request
    process_data = await response.json()
  File "/path/to/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype', url=URL('/fake/url')
[2024-09-07 04:55:37,695] INFO: "X-Request-Id: " "GET /fake/uri" 200
[2024-09-07 04:55:37,380] ERROR: "X-Request-Id: " 'url' must be provided in the request parameters                                                                                                                                                                  ─╯
 Exception in ASGI application
Traceback (most recent call last):
  File "/path/to/python_app/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app
  File "/path/to/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/path/to/application/app/main.py", line 323, in handle_request
    process_data = await response.json()
  File "/path/to/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype', url=URL('/fake/url')
[2024-09-07 04:55:37,695] INFO: "X-Request-Id: " "GET /fake/uri" 200
```
Here is the output demonstrating the timestamp issue with multiline logs:
```
[2024/09/11 12:47:29] [ info] [output:stdout:stdout.0] worker #0 started
[2024/09/11 12:47:44] [ info] [filter:multiline:multiline.0] created new multiline stream for tail.0_tail.0
[0] tail.0: [[1726058864.425684716, {}], {"log"=>"[2024-09-07 04:55:37,380] ERROR: X-Request-Id:  'url' must be provided in the request parameters"}]
[1] tail.0: [[1726058864.425705549, {}], {"log"=>" Exception in ASGI application
Traceback (most recent call last):
  File /path/to/python_app/protocols/http/h11_impl.py, line 407, in run_asgi
    result = await app
  File /path/to/middleware/proxy_headers.py, line 78, in __call__
    return await self.app(scope, receive, send)
  File /path/to/application/app/main.py, line 323, in handle_request
    process_data = await response.json()
  File /path/to/client_reqrep.py, line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype', url=URL('/fake/url')"}]
[2] tail.0: [[1726058864.425724257, {}], {"log"=>"[2024-09-07 04:55:37,695] INFO: X-Request-Id:  GET /fake/uri 200"}]
[0] tail.0: [[1726058868.287700467, {}], {"log"=>"[2024-09-07 04:55:37,380] ERROR: X-Request-Id:  'url' must be provided in the request parameters"}]
[1] tail.0: [[1726058864.425705549, {}], {"log"=>" Exception in ASGI application
Traceback (most recent call last):
  File /path/to/python_app/protocols/http/h11_impl.py, line 407, in run_asgi
    result = await app
  File /path/to/middleware/proxy_headers.py, line 78, in __call__
    return await self.app(scope, receive, send)
  File /path/to/application/app/main.py, line 323, in handle_request
    process_data = await response.json()
  File /path/to/client_reqrep.py, line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype', url=URL('/fake/url')"}]
[2] tail.0: [[1726058868.287784801, {}], {"log"=>"[2024-09-07 04:55:37,695] INFO: X-Request-Id:  GET /fake/uri 200"}]
```

**Additional Context**:
- The parsing of multiline logs itself is correct, and the logs appear structured as expected.
- I have tried various configurations including using `Time_Key` and other settings aiming to differentiate timestamps among multiline log entries, but these attempts have not resolved the issue.
- Single-line logs are being processed correctly with distinct and accurate timestamps for each entry.

**Comment by wodyjowski** [comment]
+1

**Comment by davewhit3** [comment]
+1

**Comment by luki530** [comment]
Hi @edsiper maybe you could take a look on this?

**Comment by luki530** [comment]
Still an issue for us.

**Comment by KrisMaister** [comment]
+1
