### ISSUE TITLE
Java multiline parser is invalid

### ISSUE THREAD

**Issue by xiaopanggege** [fluent/fluent-bit#9507]
## Bug Report

**Describe the bug**
Because I didn't know that the built-in Java multiline parser couldn't match my k8s environment, I customized the Java multiline parser, but it seems to have no effect

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
192.168.56.1 2024-10-17 16:36:04,764 [http-nio-9003-exec-7] ERROR [UserLogAspect.java:97]- >:
java.lang.ArithmeticException: / by zero
        at com.ruijie.rgci.device.bed.controller.out.DeviceOutController.updateDeviceUseStatus(DeviceOutController.java:215)
        at com.ruijie.rgci.device.bed.controller.out.DeviceOutController$$FastClassBySpringCGLIB$$68406b55.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.ruijie.rgci.utils.log.aspect.UserLogAspect.logAround(UserLogAspect.java:93)
        at sun.reflect.GeneratedMethodAccessor487.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.ruijie.rgci.device.bed.controller.out.DeviceOutController$$EnhancerBySpringCGLIB$$b6763c41.updateDeviceUseStatus(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)

```
- Steps to reproduce the problem:

**Screenshots**
![image](https://github.com/user-attachments/assets/36119d08-3b31-4f6b-afa1-9d695ba3a766)

**Your Environment**

* Version used:fluent-bit 3.0
* Configuration:
``` 
vim fluent-bit.yaml

---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: efk
  labels:
    helm.sh/chart: fluent-bit-0.46.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: efk
  labels:
    helm.sh/chart: fluent-bit-0.46.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [MULTILINE_PARSER]
        name            java_multiline01
        type            regex
        flush_timeout   1000
        # 以2024-10-18 08:50:39日期开头
        rule            "start_state" "/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.*/" "cont"
        rule            "cont"        "/^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*/" "cont"

    [MULTILINE_PARSER]
        name            java_multiline02
        type            regex
        flush_timeout   1000
        # 以Dec开头的日期
        rule            "start_state" "/^Dec \d+ \d+:\d+:\d+.*/" "cont"
        rule            "cont"        "/^(?!Dec \d+ \d+:\d+).*/" "cont"

    [MULTILINE_PARSER]
        name            java_multiline03
        type            regex
        flush_timeout   1000
        # 以192.168.1.1 2024-10-18 08:50:39这种IP+时间开头
        rule            "start_state" "/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3} \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.*/" "cont"
        rule            "cont"        "/^\s+at\s+.*|Caused by: .*/" "cont"

  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser java_multiline01, java_multiline02, java_multiline03, java, docker, cri
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On
        Ignore_Older 1h

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On


    [OUTPUT]
        Name es
        Match kube.*
        Host 10.97.2.200
        HTTP_User elastic
        HTTP_Passwd 123456
        tls On
        tls.verify Off
        index k8s-pod-%Y%m
        ##Logstash_Format On
        Retry_Limit 3
        Suppress_Type_Name On
        Replace_Dots On
    [OUTPUT]
        Name es
        Match host.*
        Host 10.97.2.200
        HTTP_User elastic
        HTTP_Passwd 123456
        tls On
        tls.verify Off
        index k8s-kubelet-%Y%m
        ##Logstash_Format On
        ##Logstash_Prefix node
        Retry_Limit 3
        Suppress_Type_Name On
        Replace_Dots On

```
* Environment name and version (e.g. Kubernetes? What version?):k8s v1.22.6
* Server type and version: centos7.9
* Operating System and version:centos7.9
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
I think you have a fundamental issue here in that you're not handling the actual log format on disk which will be the kubelet format. This is unrelated to your application log format, first of all you must parse the kubelet format and then you can do your application log parsing.

Have a look at the incorrect parsers section here: https://chronosphere.io/learn/fluent-bit-kubernetes-filter/

I'd also caution not to debug via some other stack which may introduce some additional changes or concerns to cope with, instead use the stdout output to see the actual data as Fluent Bit is dealing with it. This will likely highlight things better to work with and once it is correct here then you can send it to the output, then any further issues you know are to do with that output processing it.

https://chronosphere.io/learn/fluent-bit-tips-tricks/
