### ISSUE TITLE
Incorrect Backslash Escaping in Array Elements in GELF Output

### ISSUE THREAD

**Issue by ishulgan** [fluent/fluent-bit#9638]
## Bug Report

**Describe the bug**
When processing log messages containing strings with backslashes (\\) inside arrays using Fluent Bit’s GELF output plugin, the backslashes are incorrectly converted into single backslashes (\). This leads to malformed log messages in Graylog, causing errors or unexpected behavior due to the incorrect formatting of the message field.

**To Reproduce**
Example log message:
```
2024-11-22T16:28:55.518280367+03:00 stdout F {"message":[{"class":"Test\\Test"}]} 
```
Output in Graylog:
```
{"version":"1.1", "short_message":"class=Test\Test", "_time":"2024-11-22T16:28:55.518280367+03:00", "_stream":"stdout", "__p":"F", "timestamp":1732282135.518}
```
Steps to reproduce the problem:
1.	Configure Fluent Bit with the GELF output plugin.
2.	Send a log message containing double backslashes (\\) in a string field.
3.	Observe the output in Graylog where double backslashes are incorrectly replaced with single backslashes.

**Expected behavior**
Double backslashes (\\) in the input message should be preserved in the output. 

**Your Environment**
* Version used: 3.2.0
* Configuration:
```
[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    parsers_file  /fluent-bit/etc/parsers.conf


[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    multiline.parser  cri
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Skip_Empty_Lines  On

[FILTER]
    Name    parser
    Match   *
    Parser  json
    Key_Name log
    Unescape_Key False
    Reserve_Data True
    Preserve_Key False

[OUTPUT]
    Name    gelf
    Match   *
    Host    graylog.example.com
    Port    12201
    Mode    udp
    Gelf_Short_Message_Key message

```
* Filters and plugins: gelf, tail

**Comment by ulexxander** [comment]
I have similar issue:

GELF output incorrectly handles arrays of strings containing double quotes - not escaping them and producing invalid JSON, that ends up rejected by Graylog.

Dummy input:

```json
{
  "log": "info",
  "time": "2025-01-07T08:44:05+00:00",
  "description": "Example message",
  "some_list": [
    "{\"project\":\"FluentBit\",\"description\":\"Great\"}",
    "{\"project\":\"Grafana\",\"description\":\"Great too\"}"
  ]
}
```

Becomes this when serialized to GELF:

```json
{
  "version": "1.1",
  "_log": "info",
  "_time": "2025-01-07T08:44:05+00:00",
  "short_message": "Example message",
  "_some_list": "{"project":"FluentBit","description":"Great"}, {"project":"Grafana","description":"Great too"}",
  "timestamp": 1736252577.548
}
```

`_some_list` value breaks JSON, as items get joined with comma+space and quotes inside are not escaped.

Graylog error log:

```
12:27:10.549 [processbufferprocessor-0] ERROR org.graylog2.inputs.codecs.GelfCodec - Could not parse JSON, first 400 characters: {"version":"1.1", "_log":"info", "_time":"2025-01-07T08:44:05+00:00", "short_message":"Example message", "_some_list":"{"project":"FluentBit","description":"Great"}, {"project":"Grafana","description":"Great too"}", "timestamp":1736252829.548}
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('p' (code 112)): was expecting comma to separate Object entries
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 122]
        at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2648) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:685) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2430) ~[graylog.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:925) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:539) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4947) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3280) ~[graylog.jar:?]
        at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:133) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:156) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:94) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:104) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:52) [graylog.jar:?]
        at org.graylog2.shared.buffers.PartitioningWorkHandler.onEvent(PartitioningWorkHandler.java:52) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:167) [graylog.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:122) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

Graylog Docker image: `graylog/graylog:6.1.4`

OpenSearch Docker image: `opensearchproject/opensearch:2.15.0`

FluentBit Docker Compose:

```yml
services:
  fluent-bit:
    image: fluent/fluent-bit:3.2.4
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
```

`fluent-bit.conf`

```
[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf
    Plugins_File  plugins.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name      dummy
    Dummy     {"log":"info","time":"2025-01-07T08:44:05+00:00","description":"Example message","some_list":["{\"project\":\"FluentBit\",\"description\":\"Great\"}","{\"project\":\"Grafana\",\"description\":\"Great too\"}"]}

[OUTPUT]
    Name                    gelf
    Match                   *
    Host                    example.com
    Port                    12201
    Mode                    tcp
    Gelf_Short_Message_Key  description
```
